### ISSUE TITLE
mamba install fails due to RuntimeError: Permission denied: <global conda>/pkgs/cache

### ISSUE THREAD

**Issue by skwde** [mamba-org/mamba#1098]
After updating mamba in the global base environment (only accessible via elevated priviliges)
```
conda activate <some local environment>
mamba install <some package>
# the same is true if I try
mamba create -n <some new env> <some packages>
```
fails with
```
RuntimeError: Permission denied: '/opt/conda/pkgs/cache/9ee0c365'
```
The global `.condarc` I have
```
pkg_dirs:
  - /opt/conda/pkgs
  - $HOME/.conda/pkgs
envs_dirs:
  - /opt/conda/envs
  - $HOME/.conda/envs
```
while my USER `.condarc` has
```
pkg_dirs:
  - $HOME/.conda/pkgs
envs_dirs:
  - $HOME/.conda/envs
```
In the printed report coming after the error I noticed that
```
package cache : <global conda>/pkgs
                         $USER/.conda/pkgs
envs directories : $USER/.conda/envs
                          <global conda>/envs
```
the order of package cache is reversed while the envs directries look fine.
I also tried installing via
```
CONDA_PKGS_DIRS=$HOME/.conda/pkgs mamba install <some package>
```
which fails with the same issue but in the report after the rror
```
package cache : $USER/.conda/pkgs
envs directories : $USER/.conda/envs
                          <global conda>/envs
```
which suggests that
> `mamba` seems to use only the global package cache and ignores settings in the `rcfiles` or via environment variables

I have the following versions
```
mamba --version
# mamba 0.15.2
# conda 4.10.3
```
tested on centos7.

**Comment by adriendelsalle** [comment]
Hi @skwde thanks for this issue!

Did you tried replacing `$HOME` by `~` in your rc files?
The paths are transformed several times to get absolute value, expanded the "home directory" symbol `~`, etc. but I don't think that `$HOME` is valid. I would be expanded by the shell if passing it as a CLI argument, which is not the case here.

Let me know!

**Comment by brevans** [comment]
Just want to chime in on this issue. We are seeing the same behavior for a shared miniconda+mamba install (mamba v0.15.2, conda v4.10.3) where we set the `CONDA_PKGS_DIRS` variable to a user-specific absolute path where they do have write privileges, e.g. `/home/username/projects/conda_pkgs`. 

The next most recent version of Mamba we have that respects this setting is v 0.7.6 in a conda v4.9.2 environment. I haven't tried anything in between yet, but am happy to share more info / testing if that'd be helpful.

**Comment by tdhopper** [comment]
I think I'm seeing a similar issue using mamba in jupyterhub 

I have this environment:

```yaml
name: docker_dashboard_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - plotly::jupyter-dash
```

and am running `mamba env update` and get 

```
...
Looking for: ['python=3.8', 'plotly::jupyter-dash']


INFO    installed: reading repo file /tmp/tmpmd4shx5i
INFO    loading from json /tmp/tmpmd4shx5i
INFO    Parsing MatchSpec python=3.8
INFO    Parsing MatchSpec python=3.8
INFO    Adding job: python =3.8*
        
INFO    Parsing MatchSpec plotly::jupyter-dash
INFO    Parsing MatchSpec plotly::jupyter-dash
DEBUG conda.base.context:root_writable(501): [Errno 13] Permission denied: '/opt/conda/conda-meta/history'
DEBUG conda.base.context:root_writable(501): [Errno 13] Permission denied: '/opt/conda/conda-meta/history'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main_update.py", line 123, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "/opt/conda/lib/python3.8/site-packages/mamba/mamba_env.py", line 109, in mamba_install
        solver.add_jobs(install_specs, api.SOLVER_INSTALL)
    RuntimeError: Permission denied: '/opt/conda/pkgs/cache/626b4b11'

`$ /opt/conda/bin/mamba update -vv`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/conda/bin/conda
             CONDA_PREFIX=/opt/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/conda/bin/python
               CONDA_ROOT=/opt/conda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                  EFSPath=/mnt/efs-userdata
                     PATH=/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr
                          /local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/envs/system/suns/bin:/bi
                          n:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/tim.hopper/.condarc
 populated config files : /etc/conda/condarc
                          /home/tim.hopper/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://name.jfrog.io/artifactory/api/conda/conda/name/linux-64
                          https://name.jfrog.io/artifactory/api/conda/conda/name/noarch
                          https://name.jfrog.io/artifactory/api/conda/conda/linux-64
                          https://name.jfrog.io/artifactory/api/conda/conda/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/userenvs/tim.hopper/pkgs
       envs directories : /opt/userenvs/tim.hopper
                          /opt/envs/shared
                          /opt/conda
                          /home/tim.hopper/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.24.0 CPython/3.8.5 Linux/5.4.0-1009-aws ubuntu/20.04.2 glibc/2.31
                UID:GID : 2002:2002
             netrc file : /home/tim.hopper/.netrc
           offline mode : False
```

The weird thing is that this works fine if I run reinstall mamba in a conda env (instead of using mamba in the base image).

**Comment by skwde** [comment]
@adriendelsalle, I don't think that this is the issue because I can list my environments just fine using `mamba env list`.
In any case, I tried your suggestion and replaced `$HOME` in the `pkg_dirs` with `~`, but the issue remains. 

Besides that, if I do `mamba info` all the variables (actually it is only `$HOME`) in the `.condarc` are properly expanded.
It just looks like that `pkg_dirs` from the `.condarc` is ignored or overwritten by the global `.condarc`.

Hope this helps. Let me know if you need more information.

**Comment by adriendelsalle** [comment]
Thanks a lot, I'll take a look at this

**Comment by Maarten-vd-Sande** [comment]
I don't want to add more noise to the discussion, but we've seemingly been having the exact same issue as @brevans reports: a shared miniconda+mamba install (mamba v0.15.2, conda v4.10.3)

**Comment by adriendelsalle** [comment]
Hi @skwde @tdhopper @Maarten-vd-Sande !

Thanks for the details provided, it helped me to reproduce the bug. I just opened a PR to fix it.
Sorry for the delay, the patch is only a line of code but it took me some time to understand when it was introduced.

We should cut a patch release for that, ok for you @wolfv ?

**Comment by tdhopper** [comment]
A release would be very helpful. Thanks for jumping on this.
