### ISSUE TITLE
Concurrent mamba builds errors with cache and package downloads

### ISSUE THREAD

**Issue by costrouc** [mamba-org/mamba#1104]
At Quansight I'm building a service [conda-store](https://github.com/Quansight/conda-store) to build conda environments and distribute them in as many ways as possible. Currently I'm running into issues when I try to run `mamba env create ...` concurrently in multiple processes. I've seen issues pop up in two places:
  - when the repodata is being cached I see the following error if both processes are trying to download and read the repodata at the same time
  - the other one is much harder to reproduce but I see it when the same package is being downloaded by two mamba processes

I realize this is an edge case usage of mamba but was wondering if there are steps that I could take to protect multiple mamba processes from each other when building environments. Below are logs of a failed mamba environment build when two start at the same time with no cache.

```
conda-forge/noarch        
conda-forge/linux-64      

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python3.9/site-packages/mamba/mamba_env.py", line 45, in mamba_install
        index = load_channels(
      File "/opt/conda/lib/python3.9/site-packages/mamba/utils.py", line 142, in load_channels
        repo = subdir.create_repo(pool)
    RuntimeError: Could not read JSON repodata file (/opt/conda/pkgs/cache/b556ea5a.json) parse error line 2313941

`$ /opt/conda/condabin/mamba create -p /var/lib/conda-store/bcfb7b66708f93d61b8684deaffcb5cd8f783a0735ddc9c516dceb755296d4de-20210728-011202-666365-2-python-flask-env -f /tmp/tmp9_feu12t/environment.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
                CONDA_DIR=/opt/conda
               CONDA_ROOT=/opt/conda
           CURL_CA_BUNDLE=<not set>
                     PATH=/opt/conda/condabin:/opt/conda/envs/conda-store-server/bin:/opt/conda/
                          bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/
                          conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=5.10.32=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/5.10.32 ubuntu/20.04.1 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by wolfv** [comment]
@costrouc indeed, there is an issue with multiple mamba's running in parallel. We've solved this for micromamba where we use a lockfile to prevent other processes to write to the same cache. We should use a lockfile for mamba as well.

I think conda has a lockfile method, so we just need to use it from mamba (we can do that from the Python api) to lock `pkgs/cache` during repodata.json download and `pkgs` during package download & extraction.

**Comment by wolfv** [comment]
I am currently on vacation but happy to review a PR once I am back :)

**Comment by jaimergp** [comment]
I am going to give this a try!

**Comment by jaimergp** [comment]
FWIW, I tried replacing mamba with micromamba and it also runs into concurrency issues. Trying to create two environments in two celery workers, both using sqlite, results in these separate logs:

```

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/noarch        
conda-forge/linux-64      

Transaction

  Prefix: /var/lib/conda-store/583dd55140491c6b4cfa46e36c203e10280fe7e180190aa28c13f6fc35702f8f-20210729-101541-894703-2-python-numpy-env

  Updating specs:

   - python==3.8
   - numpy


  Package               Version  Build                Channel                    Size
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  Install:
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  + _libgcc_mutex           0.1  conda_forge          conda-forge/linux-64       3 KB
  + _openmp_mutex           4.5  1_gnu                conda-forge/linux-64      22 KB
  + ca-certificates   2021.5.30  ha878542_0           conda-forge/linux-64     136 KB
  + certifi           2021.5.30  py38h578d9bd_0       conda-forge/linux-64     141 KB
  + ld_impl_linux-64     2.36.1  hea4e1c9_2           conda-forge/linux-64     667 KB
  + libblas               3.9.0  10_openblas          conda-forge/linux-64      11 KB
  + libcblas              3.9.0  10_openblas          conda-forge/linux-64      11 KB
  + libffi                3.2.1  he1b5a44_1007        conda-forge/linux-64      47 KB
  + libgcc-ng            11.1.0  hc902ee8_3           conda-forge/linux-64     905 KB
  + libgfortran-ng       11.1.0  h69a702a_0           conda-forge/linux-64      18 KB
  + libgfortran5         11.1.0  h6c583b3_0           conda-forge/linux-64       2 MB
  + libgomp              11.1.0  hc902ee8_3           conda-forge/linux-64     426 KB
  + liblapack             3.9.0  10_openblas          conda-forge/linux-64      11 KB
  + libopenblas          0.3.17  pthreads_h8fe5266_1  conda-forge/linux-64       9 MB
  + libstdcxx-ng         11.1.0  h56837e0_3           conda-forge/linux-64       4 MB
  + ncurses                 6.2  h58526e2_4           conda-forge/linux-64     985 KB
  + numpy                1.21.1  py38h9894fe3_0       conda-forge/linux-64       6 MB
  + openssl              1.1.1k  h7f98852_0           conda-forge/linux-64       2 MB
  + pip                  21.2.1  pyhd8ed1ab_0         conda-forge/noarch         1 MB
  + python                3.8.0  h357f687_5           conda-forge/linux-64      38 MB
  + python_abi              3.8  2_cp38               conda-forge/linux-64       4 KB
  + readline                8.1  h46c0cb4_0           conda-forge/linux-64     295 KB
  + setuptools           49.6.0  py38h578d9bd_3       conda-forge/linux-64     929 KB
  + sqlite               3.36.0  h9cd32fc_0           conda-forge/linux-64       1 MB
  + tk                   8.6.10  h21135ba_1           conda-forge/linux-64       3 MB
  + wheel                0.36.2  pyhd3deb0d_0         conda-forge/noarch        31 KB
  + xz                    5.2.5  h516909a_1           conda-forge/linux-64     343 KB
  + zlib                 1.2.11  h516909a_1010        conda-forge/linux-64     106 KB

  Summary:

  Install: 28 packages

  Total download: 73 MB

â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

Confirm changes: [Y/n] Finished _libgcc_mutex                        (00m:00s)               3 KB      8 KB/s
Finished ca-certificates                      (00m:00s)             136 KB    332 KB/s
Finished zlib                                 (00m:00s)             106 KB    213 KB/s
Finished liblapack                            (00m:00s)              11 KB     20 KB/s
Finished ld_impl_linux-64                     (00m:00s)             667 KB      1 MB/s
Finished python_abi                           (00m:00s)               4 KB      6 KB/s
Finished wheel                                (00m:00s)              31 KB     42 KB/s
Finished ncurses                              (00m:00s)             985 KB      1 MB/s
Finished libgomp                              (00m:00s)             426 KB    416 KB/s
Finished libgfortran5                         (00m:01s)               2 MB      2 MB/s
Finished readline                             (00m:00s)             295 KB    220 KB/s
Finished libgcc-ng                            (00m:00s)             905 KB    590 KB/s
Finished _openmp_mutex                        (00m:00s)              22 KB     11 KB/s
Finished libffi                               (00m:00s)              47 KB     23 KB/s
Finished pip                                  (00m:00s)               1 MB    568 KB/s
Finished tk                                   (00m:02s)               3 MB      2 MB/s
Finished openssl                              (00m:01s)               2 MB   1003 KB/s
Finished xz                                   (00m:00s)             343 KB    133 KB/s
Finished certifi                              (00m:00s)             141 KB     51 KB/s
Finished libgfortran-ng                       (00m:00s)              18 KB      6 KB/s
Finished libcblas                             (00m:00s)              11 KB      4 KB/s
Finished libstdcxx-ng                         (00m:02s)               4 MB      2 MB/s
Finished libblas                              (00m:00s)              11 KB      3 KB/s
Finished setuptools                           (00m:00s)             929 KB    284 KB/s
Finished sqlite                               (00m:01s)               1 MB    446 KB/s
Finished numpy                                (00m:02s)               6 MB      1 MB/s
Finished libopenblas                          (00m:02s)               9 MB      2 MB/s
Finished python                               (00m:09s)              38 MB      5 MB/s


Transaction starting
Linking ld_impl_linux-64-2.36.1-hea4e1c9_2
Linking _libgcc_mutex-0.1-conda_forge
Linking libstdcxx-ng-11.1.0-h56837e0_3
Linking ca-certificates-2021.5.30-ha878542_0
Linking libgfortran5-11.1.0-h6c583b3_0
Linking libgomp-11.1.0-hc902ee8_3
Linking libgfortran-ng-11.1.0-h69a702a_0
Linking _openmp_mutex-4.5-1_gnu
Linking libgcc-ng-11.1.0-hc902ee8_3
Linking libopenblas-0.3.17-pthreads_h8fe5266_1
Linking zlib-1.2.11-h516909a_1010
Linking xz-5.2.5-h516909a_1
Linking openssl-1.1.1k-h7f98852_0
Linking ncurses-6.2-h58526e2_4
Linking libffi-3.2.1-he1b5a44_1007
Linking libblas-3.9.0-10_openblas
Linking tk-8.6.10-h21135ba_1
Linking readline-8.1-h46c0cb4_0
Linking libcblas-3.9.0-10_openblas
Linking liblapack-3.9.0-10_openblas
Linking sqlite-3.36.0-h9cd32fc_0
ERROR   Cannot find cache for sqlite-3.36.0-h9cd32fc_0.tar.bz2
```

```

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

WARNING Cannot lock file "/root/micromamba/pkgs/cache/mamba.lock"
        Waiting for other mamba process to finish.
        
conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache

Transaction

  Prefix: /var/lib/conda-store/bcfb7b66708f93d61b8684deaffcb5cd8f783a0735ddc9c516dceb755296d4de-20210729-101541-652658-1-python-flask-env

  Updating specs:

   - python==3.9
   - flask


  Package               Version  Build               Channel                    Size
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  Install:
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  + _libgcc_mutex           0.1  conda_forge         conda-forge/linux-64       3 KB
  + _openmp_mutex           4.5  1_gnu               conda-forge/linux-64      22 KB
  + ca-certificates   2021.5.30  ha878542_0          conda-forge/linux-64     136 KB
  + certifi           2021.5.30  py39hf3d152e_0      conda-forge/linux-64     141 KB
  + click                 8.0.1  py39hf3d152e_0      conda-forge/linux-64     146 KB
  + dataclasses             0.8  pyhc8e2a94_1        conda-forge/noarch         7 KB
  + flask                 2.0.1  pyhd8ed1ab_0        conda-forge/noarch        70 KB
  + itsdangerous          2.0.1  pyhd8ed1ab_0        conda-forge/noarch        17 KB
  + jinja2                3.0.1  pyhd8ed1ab_0        conda-forge/noarch        99 KB
  + ld_impl_linux-64     2.36.1  hea4e1c9_2          conda-forge/linux-64     667 KB
  + libffi                  3.3  h58526e2_2          conda-forge/linux-64      51 KB
  + libgcc-ng            11.1.0  hc902ee8_3          conda-forge/linux-64     905 KB
  + libgomp              11.1.0  hc902ee8_3          conda-forge/linux-64     426 KB
  + libstdcxx-ng         11.1.0  h56837e0_3          conda-forge/linux-64       4 MB
  + markupsafe            2.0.1  py39h3811e60_0      conda-forge/linux-64      22 KB
  + ncurses                 6.2  h58526e2_4          conda-forge/linux-64     985 KB
  + openssl              1.1.1k  h7f98852_0          conda-forge/linux-64       2 MB
  + pip                  21.2.1  pyhd8ed1ab_0        conda-forge/noarch         1 MB
  + python                3.9.0  hffdb5ce_5_cpython  conda-forge/linux-64      29 MB
  + python_abi              3.9  2_cp39              conda-forge/linux-64       4 KB
  + readline                8.1  h46c0cb4_0          conda-forge/linux-64     295 KB
  + setuptools           49.6.0  py39hf3d152e_3      conda-forge/linux-64     943 KB
  + sqlite               3.36.0  h9cd32fc_0          conda-forge/linux-64       1 MB
  + tk                   8.6.10  h21135ba_1          conda-forge/linux-64       3 MB
  + tzdata                2021a  he74cb21_1          conda-forge/noarch       121 KB
  + werkzeug              2.0.1  pyhd8ed1ab_0        conda-forge/noarch       219 KB
  + wheel                0.36.2  pyhd3deb0d_0        conda-forge/noarch        31 KB
  + xz                    5.2.5  h516909a_1          conda-forge/linux-64     343 KB
  + zlib                 1.2.11  h516909a_1010       conda-forge/linux-64     106 KB

  Summary:

  Install: 29 packages

  Total download: 46 MB

â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

Confirm changes: [Y/n] Finished _libgcc_mutex                        (00m:00s)               3 KB      5 KB/s
Finished ca-certificates                      (00m:00s)             136 KB    219 KB/s
Finished libgomp                              (00m:00s)             426 KB    609 KB/s
Finished ld_impl_linux-64                     (00m:00s)             667 KB    881 KB/s
Finished readline                             (00m:00s)             295 KB    339 KB/s
Finished dataclasses                          (00m:00s)               7 KB      8 KB/s
Finished werkzeug                             (00m:00s)             219 KB    198 KB/s
Finished flask                                (00m:00s)              70 KB     58 KB/s
Finished zlib                                 (00m:00s)             106 KB     79 KB/s
Finished libffi                               (00m:00s)              51 KB     38 KB/s
Finished wheel                                (00m:00s)              31 KB     21 KB/s
Finished ncurses                              (00m:00s)             985 KB    778 KB/s
Finished tzdata                               (00m:00s)             121 KB     83 KB/s
Finished markupsafe                           (00m:00s)              22 KB     15 KB/s
Finished _openmp_mutex                        (00m:00s)              22 KB     14 KB/s
Finished itsdangerous                         (00m:00s)              17 KB     11 KB/s
Finished setuptools                           (00m:00s)             943 KB    636 KB/s
Finished python_abi                           (00m:00s)               4 KB      2 KB/s
Finished libgcc-ng                            (00m:00s)             905 KB    465 KB/s
Finished click                                (00m:00s)             146 KB     69 KB/s
Finished jinja2                               (00m:00s)              99 KB     39 KB/s
Finished certifi                              (00m:00s)             141 KB     53 KB/s
Finished openssl                              (00m:01s)               2 MB    885 KB/s
Finished xz                                   (00m:00s)             343 KB    123 KB/s
SHA256 sum validation error.
ERROR   File not valid: SHA256 sum doesn't match expectation "/root/micromamba/pkgs/sqlite-3.36.0-h9cd32fc_0.tar.bz2"
        Expected: 648090a8022eaad4bc6964ddd200f1e4871d01fdd18b058541f146a320c48c4e
        
Finished libstdcxx-ng                         (00m:02s)               4 MB      2 MB/s
Finished pip                                  (00m:00s)               1 MB    359 KB/s
Finished tk                                   (00m:01s)               3 MB      1 MB/s
Finished python                               (00m:08s)              29 MB      4 MB/s
ERROR   Found incorrect download: sqlite. Aborting
```

**Comment by adriendelsalle** [comment]
@costrouc @jaimergp 
We replaced conda file locks with libmamba ones but also use them during extraction. We maybe also need to use them for downloading to avoid wasting bandwidth and collision when moving from tmp directory to the cache one.
Mamba and micromamba rely on the same implementation
Could you give it a new try using master branch or share a snippet for testing it?

**Comment by jaimergp** [comment]
Sure thing! Do you have nightly conda packages we can try easily off a channel?

**Comment by jaimergp** [comment]
I used this to debug repodata cache issues, not sure if downloads are hit too:

```
mamba clean -i
mamba update --all -y --debug & mamba update --all -y --debug
```

**Comment by jonashaag** [comment]
I've created a new similar issue here https://github.com/mamba-org/mamba/issues/2666
