### ISSUE TITLE
Download filed: File size/SHA256 sum validation error.

### ISSUE THREAD

**Issue by Direct-A** [mamba-org/mamba#1125]
It's weird, whatever I run `mamba update`/`install`/`create` or `conda`, I'll got ERRORs like

```
Downloading  [=============================>                 ] (00m:00s)    5.93 MB/s
Extracting   [>                                                            ] (--:--)
ERROR   File not valid: file size doesn't match expectation "/home/xxx/mambaforge-pypy3/pkgs/libstdcxx-ng-11.1.0-h56837e0_8.tar.bz2"
File size validation error.
SHA256 sum validation error.
```

and the full report is

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/xxx/mambaforge-pypy3/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/xxx/mambaforge-pypy3/site-packages/mamba/mamba.py", line 920, in exception_converter
        raise e
      File "/home/xxx/mambaforge-pypy3/site-packages/mamba/mamba.py", line 914, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/xxx/mambaforge-pypy3/site-packages/mamba/mamba.py", line 873, in _wrapped_main
        result = do_call(args, p)
      File "/home/xxx/mambaforge-pypy3/site-packages/mamba/mamba.py", line 755, in do_call
        exit_code = create(args, parser)
      File "/home/xxx/mambaforge-pypy3/site-packages/mamba/mamba.py", line 658, in create
        return install(args, parser, "create")
      File "/home/xxx/mambaforge-pypy3/site-packages/mamba/mamba.py", line 608, in install
        downloaded = transaction.prompt(repos)
    RuntimeError: Found incorrect download: libgfortran5. Aborting

`$ /home/xxx/mambaforge-pypy3/bin/mamba create -n bio-info python=3.7 r-base=4.1`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/xxx/mambaforge-pypy3/bin/conda
             CONDA_PREFIX=/home/xxx/mambaforge-pypy3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/xxx/mambaforge-pypy3/bin/python
               CONDA_ROOT=/home/xxx/mambaforge-pypy3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/xxx/mambaforge-pypy3/bin:/home/xxx/mambaforge-pypy3/condabin:/ho
                          me/xxx/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm
                          /default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_per
                          l:/usr/local/go/bin:/home/xxx/.local/texlive/2021/texmf-
                          dist/doc/man:/home/xxx/.local/texlive/2021/texmf-dist/doc/info:/home/s
                          yc/.local/texlive/2021/bin/x86_64-linux:/home/xxx/.fzf/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1

     active environment : base
    active env location : /home/xxx/mambaforge-pypy3
            shell level : 1
       user config file : /home/xxx/.condarc
 populated config files : /home/xxx/mambaforge-pypy3/.condarc
                          /home/xxx/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.7.10.final.0
       virtual packages : __linux=5.10.56=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/xxx/mambaforge-pypy3  (writable)
      conda av data dir : /home/xxx/mambaforge-pypy3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/xxx/mambaforge-pypy3/pkgs
                          /home/xxx/.conda/pkgs
       envs directories : /home/xxx/mambaforge-pypy3/envs
                          /home/xxx/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 PyPy/3.7.10 Linux/5.10.56-1-lts arch/rolling glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

I'm useing `Mambaforge-pypy3-4.10.3-4`, and `mamba -V` returns `conda 4.10.3`.

**Comment by wolfv** [comment]
There are two things:

- do you have enough free disk space?
- You're using many channels and some seem like duplicate mirrrors. Could you try to reduce the number?

Sorry for the troubles.

**Comment by Direct-A** [comment]
@wolfv 

```
❯ df ~
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       164G   53G  103G  34% /
```

I've commit some mirrors in my `.condarc`

```
ssl_verify: true
channels:
  # - https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/
  # - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r
  - defaults
show_channel_urls: true
```

And, it disssappear.

Thanks a lot!

**Comment by Whale-fall** [comment]
Same problem, but I think the reason why this error happens is something wrong with the mirror BFSU.Have you investigated that?

**Comment by Whale-fall** [comment]
When I update via conda with mirror BFSU no error happens, but mamba went wrong

**Comment by Direct-A** [comment]
> Same problem, but I think the reason why this error happens is something wrong with the mirror BFSU.Have you investigated that?

Nope, I just changed proxy to globle, and commit bfsu mirrors.

And this is my `.condarc`.

```
❯ cat .condarc
ssl_verify: true
channels:
  # - https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/
  # - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r
  - conda-forge
  - bioconda
  - free
  - defaults
show_channel_urls: true
```

**Comment by Direct-A** [comment]
> Same problem, but I think the reason why this error happens is something wrong with the mirror BFSU.Have you investigated that?

Nope, I just changed proxy to globle, and commit bfsu mirrors.

And this is my `.condarc`.

```
❯ cat .condarc
ssl_verify: true
channels:
  # - https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/
  # - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  # - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r
  - conda-forge
  - bioconda
  - free
  - defaults
show_channel_urls: true
```

**Comment by Scelta** [comment]
The same issue when I used the BFSU mirror. The mirror works for `conda` but always failed for `mamba`. That's so weired.


An instance:

```bash
mamba install -c conda-forge dvc-ssh

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.7.6) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['dvc-ssh']

pkgs/main/noarch         [====================] (00m:04s) Done
pkgs/msys2/linux-64      [====================] (00m:00s) Done
pkgs/free/linux-64       [====================] (00m:05s) Done
pkgs/free/noarch         [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:02s) Done
pkgs/pro/noarch          [====================] (00m:00s) Done
pkgs/main/linux-64       [====================] (00m:32s) Done
pkgs/pro/linux-64        [====================] (00m:00s) Done
bioconda/linux-64        [====================] (00m:29s) Done
pkgs/msys2/noarch        [====================] (00m:00s) Done
bioconda/noarch          [====================] (00m:26s) Done
pkgs/r/linux-64          [====================] (00m:04s) Done
conda-forge/noarch       [====================] (00m:45s) Done
conda-forge/linux-64     [====================] (01m:13s) Done
Transaction

  Prefix: /█████/█████/SHR

  Updating specs:

   - dvc-ssh


  Package                  Version  Build           Channel                                                       Size
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  aiohttp                    3.8.1  py37h540881e_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     561 KB
  aiohttp-retry              2.4.6  pyhd8ed1ab_1    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        10 KB
  aiosignal                  1.2.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        12 KB
  async-timeout              4.0.2  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch         9 KB
  asyncssh                  2.10.1  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch       225 KB
  asynctest                 0.13.0  py_0            mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        24 KB
  atpublic                   3.0.1  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch         8 KB
  c-ares                    1.18.1  h7f98852_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     113 KB
  cached-property            1.5.2  hd8ed1ab_1      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch         4 KB
  cached_property            1.5.2  pyha770c72_1    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        11 KB
  charset-normalizer        2.0.12  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        35 KB
  commonmark                 0.9.1  py_0            mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        46 KB
  configobj                  5.0.6  py_0            mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        31 KB
  dataclasses                  0.8  pyhc8e2a94_3    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        10 KB
  dictdiffer                 0.9.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        17 KB
  diskcache                  5.4.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        37 KB
  distro                     1.6.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        22 KB
  dpath                      2.0.6  py37h89c1867_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      23 KB
  dulwich                  0.20.40  py37h540881e_0  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     726 KB
  dvc                       2.10.2  py37h89c1867_0  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     569 KB
  dvc-render                 0.0.5  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        18 KB
  dvc-ssh                   2.10.2  py37h89c1867_0  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      10 KB
  dvclive                    0.8.2  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        29 KB
  flatten-dict               0.4.2  pyhd8ed1ab_1    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        12 KB
  flufl.lock                   7.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        13 KB
  frozenlist                 1.3.0  py37h540881e_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      43 KB
  ftfy                       6.1.1  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        57 KB
  funcy                       1.17  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        30 KB
  gitdb                      4.0.9  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        46 KB
  gitpython                 3.1.27  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch       123 KB
  grandalf                     0.6  py_0            mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        42 KB
  importlib_resources        5.7.1  pyhd8ed1ab_1    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        22 KB
  keyutils                   1.6.1  h166bdaf_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     115 KB
  libev                       4.33  h516909a_1      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     104 KB
  libgit2                    1.4.3  h6529ace_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     725 KB
  libnghttp2                1.47.0  h727a467_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     808 KB
  libzlib                   1.2.11  h166bdaf_1014   mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      60 KB
  mailchecker               4.1.17  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch       238 KB
  multidict                  6.0.2  py37h540881e_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      49 KB
  nanotime                   0.5.2  py_0            mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch         6 KB
  pcre2                      10.37  h032f7d1_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64       1 MB
  phonenumbers             8.12.49  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch         2 MB
  pyasn1                     0.4.8  py_0            mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        53 KB
  pydot                      1.4.2  py37h89c1867_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      43 KB
  pygit2                     1.9.0  py37h540881e_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     217 KB
  pygtrie                    2.4.2  pyhd3deb0d_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        24 KB
  python-benedict           0.24.3  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        30 KB
  python-fsutil              0.6.1  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        14 KB
  python-gssapi              1.7.3  py37hb0bcb59_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     591 KB
  python-slugify             6.1.2  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        15 KB
  requests                  2.27.1  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        53 KB
  rich                      12.4.4  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch       164 KB
  ruamel.yaml              0.17.21  py37h540881e_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     171 KB
  ruamel.yaml.clib           0.2.6  py37h540881e_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     148 KB
  scmrepo                   0.0.19  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        34 KB
  shortuuid                  1.0.8  py37h89c1867_0  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      17 KB
  shtab                      1.5.4  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        17 KB
  smmap                      3.0.5  pyh44b312d_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        22 KB
  sshfs                   2022.3.1  py37h89c1867_1  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      25 KB
  tabulate                   0.8.9  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        26 KB
  text-unidecode               1.3  py_0            mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        68 KB
  toml                      0.10.2  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        18 KB
  typing-extensions          4.2.0  hd8ed1ab_1      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch         8 KB
  typing_extensions          4.2.0  pyha770c72_1    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        27 KB
  unidecode                  1.3.4  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch       155 KB
  voluptuous                0.13.1  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        29 KB
  xmltodict                 0.13.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        13 KB
  yarl                       1.7.2  py37h540881e_2  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     132 KB
  zc.lockfile                  2.0  pyhd8ed1ab_1    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        12 KB

  Change:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  zlib                      1.2.11  h7b6447c_3      installed
  zlib                      1.2.11  h166bdaf_1014   mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      88 KB

  Upgrade:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  ca-certificates       2021.10.26  h06a4308_2      installed
  ca-certificates      2022.5.18.1  ha878542_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     144 KB
  certifi                2021.10.8  py37h06a4308_0  installed
  certifi              2022.5.18.1  py37h89c1867_0  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     150 KB
  curl                      7.71.1  hbc83047_1      installed
  curl                      7.83.1  h7bff187_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64      89 KB
  fsspec                     0.8.3  py_0            installed
  fsspec                  2022.5.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        96 KB
  krb5                      1.18.2  h173b8e3_0      installed
  krb5                      1.19.3  h3790be6_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64       1 MB
  libcurl                   7.71.1  h20c2e04_1      installed
  libcurl                   7.83.1  h7bff187_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     342 KB
  libssh2                    1.9.0  h1ba5d50_1      installed
  libssh2                   1.10.0  ha56f1ee_2      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     233 KB
  openssl                   1.1.1l  h7f8727e_0      installed
  openssl                   1.1.1o  h166bdaf_0      mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64       2 MB
  pathspec                   0.7.0  py_0            installed
  pathspec                   0.9.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        31 KB
  psutil                     5.7.2  py37h7b6447c_0  installed
  psutil                     5.9.1  py37h540881e_0  mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64     344 KB
  tqdm                      4.55.0  pyhd3eb1b0_0    installed
  tqdm                      4.64.0  pyhd8ed1ab_0    mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch        81 KB

  Summary:

  Install: 69 packages
  Change: 1 packages
  Upgrade: 11 packages

  Total download: 15 MB

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
ERROR   transaction.cpp:84 File not valid: file size doesn't match expectation "/█████/█████/SHR/pkgs/zlib-1.2.11-h166bdaf_1014.tar.bz2"
zlib                     [====================] (00m:00s) Validating...
terminate called after throwing an instance of 'std::runtime_error'
  what():  File not valid: file size doesn't match expectation (/█████/█████/SHR/pkgs/zlib-1.2.11-h166bdaf_1014.tar.bz2)

```

Conda env:
```bash
$ conda info

     active environment : base
    active env location : /█████/█████/SHR/USER/█████/miniconda3
            shell level : 1
       user config file : /home/█████/.condarc
 populated config files : /home/█████/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.11.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /█████/█████/SHR/USER/█████/miniconda3  (writable)
      conda av data dir : /█████/█████/SHR/USER/█████/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /█████/█████/SHR/USER/█████/miniconda3/pkgs
                          /home/█████/.conda/pkgs
       envs directories : /█████/█████/█████/█████/.conda/envs
                          /█████/█████/SHR/USER/█████/miniconda3/envs
                          /home/█████/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.11 Linux/3.10.0-1127.el7.x86_64 centos/7.8.2003 glibc/2.17
                UID:GID : 34929:2782
             netrc file : None
           offline mode : False

```
