### ISSUE TITLE
Cannot load local channels that contain spaces

### ISSUE THREAD

**Issue by jaimergp** [mamba-org/mamba#1158]
If given a local channel (either absolute path of `file://` url) with spaces, Mamba fails to load the channel.

```
mamba install -c "/tmp/conda-channel/channel with spaces" python --dry-run
```

fails with:

```
Traceback (most recent call last):
  File "/opt/conda-src/debug_channels_mamba.py", line 11, in <module>
    index = load_channels(Pool(), channels_urls, [])
  File "/opt/conda/lib/python3.9/site-packages/mamba/utils.py", line 123, in load_channels
    index = get_index(
  File "/opt/conda/lib/python3.9/site-packages/mamba/utils.py", line 79, in get_index
    for channel in api.get_channels(all_channels):
RuntimeError: Could not set URL (code: 3 - url = file:///tmp/conda-channel/channel with spaces)
```

URL escaping the spaces works:

```
mamba install -c "/tmp/conda-channel/channel%20with%20spaces" python --dry-run
```

but that's a weird UX pattern for CLI users.

**Comment by wolfv** [comment]
@jaimergp we have this function available: https://github.com/mamba-org/mamba/blob/05bde9d6d445b0663b9fc126eee087ae61a42401/src/core/url.cpp#L116-L131

**Comment by jaimergp** [comment]
Nice! `conda` has some on its internals too. I need to come up with a cleaner solution than what I have at the moment because the escaped URLs are not unescaped for the name, so maybe handling this at fetch time is better than just passing the escaped URL from the beginning.
