### ISSUE TITLE
issue with read-only pkgs cache

### ISSUE THREAD

**Issue by mathause** [mamba-org/mamba#1292]
Mamba can fail when using a read-only pkgs cache (as can happen with a central installation). Should mamba disregard a read-only cache? Or should the read-only cache be removed from the `.condarc`? (In this case a better error message would be appropriate.) Or is it a bug?

The error message differs on the order of the `pkgs_dirs` in `.condarc`. If the ro cache is listed _after_ the rw cache, i.e. if

```
pkgs_dirs:
  - ~/rw/pkgs
  - ~/ro/pkgs
```

I get the following error:

```python-traceback
RuntimeError: File exists: '~/ro/pkgs/cache/14e80fbd.json', '~/rw/pkgs/cache/14e80fbd.json'
```

<details>

```

(base) mathause@poisson:~$ mamba install -q black
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/mathause/rw/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 922, in exception_converter
        raise e
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 916, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 874, in _wrapped_main
        result = do_call(args, p)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 739, in do_call
        exit_code = install(args, parser, "install")
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 495, in install
        index = load_channels(pool, channels, repos)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/utils.py", line 136, in load_channels
        index = get_index(
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/utils.py", line 117, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: File exists: '/home/mathause/ro/pkgs/cache/14e80fbd.json', '/home/mathause/rw/pkgs/cache/14e80fbd.json'

`$ /home/mathause/rw/bin/mamba install -q black`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/mathause/rw/bin/conda
             CONDA_PREFIX=/home/mathause/rw
           CONDA_PREFIX_1=/home/mathause/.conda
           CONDA_PREFIX_2=/home/mathause/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/mathause/rw/bin/python
               CONDA_ROOT=/home/mathause/rw
              CONDA_SHLVL=3
           CURL_CA_BUNDLE=<not set>
            DEFAULTS_PATH=/usr/share/gconf/plasma.default.path
           MANDATORY_PATH=/usr/share/gconf/plasma.mandatory.path
                     PATH=/home/mathause/conda/bin:/home/mathause/rw/bin:/home/mathause/conda/co
                          ndabin:/home/mathause/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/us
                          r/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1

     active environment : base
    active env location : /home/mathause/rw
            shell level : 3
       user config file : /home/mathause/.condarc
 populated config files : /home/mathause/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/mathause/rw  (writable)
      conda av data dir : /home/mathause/rw/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mathause/rw/pkgs
                          /home/mathause/ro/pkgs
       envs directories : /home/mathause/rw/envs
                          /home/mathause/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/5.13.0-21-generic linuxmint/20.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

```

</details>

---

If the rw cache is listed _after_ the ro cache, i.e. if

```
pkgs_dirs:
  - ~/ro/pkgs
  - ~/rw/pkgs
```

I get the following error

```python-traceback
RuntimeError: LockFile error. Aborting.
```
<details>

```

mamba install -q black
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/mamba.lock'
warning  LockFile creation for path '/home/mathause/ro/pkgs/cache' failed, continuing without it
error    Could not open lockfile '/home/mathause/ro/pkgs/cache/b556ea5a.solv.lock'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/mathause/rw/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 922, in exception_converter
        raise e
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 916, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 874, in _wrapped_main
        result = do_call(args, p)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 739, in do_call
        exit_code = install(args, parser, "install")
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/mamba.py", line 495, in install
        index = load_channels(pool, channels, repos)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/utils.py", line 185, in load_channels
        with lock_file(subdir.cache_path()):
      File "/home/mathause/rw/lib/python3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/home/mathause/rw/lib/python3.9/site-packages/mamba/utils.py", line 34, in lock_file
        lock = api.LockFile(path)  # noqa F841
    RuntimeError: LockFile error. Aborting.

`$ /home/mathause/rw/bin/mamba install -q black`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/mathause/rw/bin/conda
             CONDA_PREFIX=/home/mathause/rw
           CONDA_PREFIX_1=/home/mathause/.conda
           CONDA_PREFIX_2=/home/mathause/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/mathause/rw/bin/python
               CONDA_ROOT=/home/mathause/rw
              CONDA_SHLVL=3
           CURL_CA_BUNDLE=<not set>
            DEFAULTS_PATH=/usr/share/gconf/plasma.default.path
           MANDATORY_PATH=/usr/share/gconf/plasma.mandatory.path
                     PATH=/home/mathause/conda/bin:/home/mathause/rw/bin:/home/mathause/conda/co
                          ndabin:/home/mathause/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/us
                          r/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1

     active environment : base
    active env location : /home/mathause/rw
            shell level : 3
       user config file : /home/mathause/.condarc
 populated config files : /home/mathause/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/mathause/rw  (writable)
      conda av data dir : /home/mathause/rw/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mathause/ro/pkgs
                          /home/mathause/rw/pkgs
       envs directories : /home/mathause/rw/envs
                          /home/mathause/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/5.13.0-21-generic linuxmint/20.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

</details>

---

To reproduce you can do

```bash

# install miniconda & mamba
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# install to folder ~/rw
bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/rw

# reload shell
bash

conda config --add channels conda-forge
conda config --set channel_priority strict

conda install mamba

# install random package
mamba install isort

# create a ro cache & populate cache files 
mkdir -p ro/pkgs
cp -r rw/pkgs/cache/ ro/pkgs/
sudo chown -R root:root ro

# add pkgs_dirs to .condarc
cat << EOF >> .condarc
pkgs_dirs:
  - ~/ro/pkgs
  - ~/rw/pkgs
EOF

# try to install random package
mamba install black

```

Now revert the order in the `.condarc` and try again.

---

edit: this happens from v0.17 on.

**Comment by adriendelsalle** [comment]
Thanks for opening this issue, I'm having a look

**Comment by adriendelsalle** [comment]
There are several issues:
#### read-write cache has higher precedence than read-only one

`libmamba` tries to use the read-write cache, but probably in the error you met found an expired index file. In that case we iterate over all possible caches to check if valid/not expired index file is found (incl. read-only locations)
- Bug1: when an expired cache is found, we should not overwrite its path with a lower-precedence one if it's not a better match (e.g. if it's not a valid index file)
https://github.com/mamba-org/mamba/blob/207267432f936ca9c383e693302b0692b8286fd1/libmamba/src/core/subdirdata.cpp#L182-L186

Then if the index file is expired but hasn't changed (304 http status), and if that file is read-only (cf. the previous `Bug1`), we copy the expired file in the read-write cache and update its metadata (we *touch* it). We do that operation for both the `json` file and the `solv` one.
- Bug2: if the file already exists in the read-write cache, it throws an error. we should delete the pre-existing file before copying the other one
https://github.com/mamba-org/mamba/blob/207267432f936ca9c383e693302b0692b8286fd1/libmamba/src/core/subdirdata.cpp#L295
https://github.com/mamba-org/mamba/blob/207267432f936ca9c383e693302b0692b8286fd1/libmamba/src/core/subdirdata.cpp#L301

#### read-only cache has higher precedence than read-write one

We lock several directories or files to avoid race conditions between multiple processes. Most of those locks are used in `libmamba` C++ implementation but `mamba` also use them in several places.
- Bug3: the `mamba` implementation is not using the `LockFile`s correctly. It should use `LockFile::try_lock` on possibly read-only paths
https://github.com/mamba-org/mamba/blob/207267432f936ca9c383e693302b0692b8286fd1/mamba/mamba/utils.py#L185-L186

Last but not least we rely on `conda` for linking step of `mamba` and you will still get a permission error if the *magic file* `urls.txt` is missing in the `pkgs` directory:
`conda.exceptions.NotWritableError: The current user does not have write permissions to a required path.`

Adding this extra (empty) file allows `conda` to test if the cache is writable or not. It should consider it's not writable if the file is missing and fails to create it but it looks like it works differently.

For the other bugs, I'll open a PR

**Comment by mathause** [comment]
Thanks for looking at this so fast!
