### ISSUE TITLE
Infinite loop of pip warnings

### ISSUE THREAD

**Issue by astrojuanlu** [mamba-org/mamba#1293]
I was trying to recreate this environment:

```
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.9
- mock
- pillow
- sphinx
- sphinx_rtd_theme
- pip:
  - recommonmark
  - readthedocs-sphinx-ext
- mock
- pillow
- sphinx
- sphinx_rtd_theme
name: moacean-parcels-rtd
```

but got an infinite loop saying `Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.`.

The traceback on interrupt might shed some light:

```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
^CTraceback (most recent call last):
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 81, in execute
    spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
    if spec.can_handle():
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
    self._environment = env.from_file(self.filename)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda_env/env.py", line 165, in from_file
    return from_yaml(yamlstr, filename=filename)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
    data = validate_keys(data, kwargs)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda_env/env.py", line 65, in validate_keys
    new_data['dependencies'].insert(0, 'pip')
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/bin/mamba", line 11, in <module>
    sys.exit(main())
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/mamba/mamba.py", line 887, in main
    return mamba_env.main()
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/mamba/mamba_env.py", line 145, in main
    return conda_env_main()
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda_env/cli/main.py", line 91, in main
    return conda_exception_handler(do_call, args, parser)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda/exceptions.py", line 1122, in handle_exception
    self._print_conda_exception(CondaError("KeyboardInterrupt"), _format_exc())
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda/exceptions.py", line 1133, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda/exceptions.py", line 1047, in print_conda_exception
    print(_format_exc(exc_val, exc_tb), file=sys.stderr)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda/exceptions.py", line 1069, in _format_exc
    formatted_exception = format_exception(exc_type, exc_val, exc_tb)
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/traceback.py", line 347, in extract
    for f, lineno in frame_gen:
  File "/root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/traceback.py", line 312, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'str' object has no attribute 'tb_frame'
```

This is the comand I launched:

```
/usr/bin/time -v /root/.asdf/installs/python/mambaforge-4.10.1-5/bin/mamba env create --verbose --name latest --file environment-rtd-bad.yaml
```

more info:

```
# /root/.asdf/installs/python/mambaforge-4.10.1-5/bin/mamba info -a

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.14.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.asdf/installs/python/mambaforge-4.10.1-5/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /root/.asdf/installs/python/mambaforge-4.10.1-5  (writable)
      conda av data dir : /root/.asdf/installs/python/mambaforge-4.10.1-5/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /root/.asdf/installs/python/mambaforge-4.10.1-5/pkgs
                          /root/.conda/pkgs
       envs directories : /root/.asdf/installs/python/mambaforge-4.10.1-5/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.5 Linux/5.13.0-21-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False

# conda environments:
#
base                  *  /root/.asdf/installs/python/mambaforge-4.10.1-5
latest                   /root/.asdf/installs/python/mambaforge-4.10.1-5/envs/latest

sys.version: 3.9.5 | packaged by conda-forge | (defau...
sys.prefix: /root/.asdf/installs/python/mambaforge-4.10.1-5
sys.executable: /root/.asdf/installs/python/mambaforge-4.10.1-5/bin/python
conda location: /root/.asdf/installs/python/mambaforge-4.10.1-5/lib/python3.9/site-packages/conda
conda-build: None
conda-env: /root/.asdf/installs/python/mambaforge-4.10.1-5/bin/conda-env
user site dirs: 

CIO_TEST: <not set>
CONDA_ROOT: /root/.asdf/installs/python/mambaforge-4.10.1-5
CURL_CA_BUNDLE: <not set>
PATH: /home/docs/.asdf/shims:/home/docs/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

**Comment by adriendelsalle** [comment]
Thanks for filling this issue. I'll have a look tomorrow

**Comment by adriendelsalle** [comment]
@astrojuanlu it looks like this issue came from `conda`, see https://github.com/conda/conda/issues/10614 and its solution https://github.com/conda/conda/commit/5627cf79909bd934518bbcc6d21df7ac4ea96e62.

Could you please retry with a fresh install using the latest [`mambaforge` installer](https://github.com/conda-forge/miniforge/releases/tag/4.10.3-7)?

**Comment by wolfv** [comment]
yes, indeed, for the pip install via mamba we just use the same code as conda.
