### ISSUE TITLE
PID locked error

### ISSUE THREAD

**Issue by marcelned** [mamba-org/mamba#1295]
```console
❯ mamba --version
mamba 0.18.1
conda 4.11.0
```

```console
❯ mamba create -n test pip

Looking for: ['pip']

conda-forge/osx-64       Using cache
conda-forge/noarch       Using cache
Transaction

  Prefix: /Users/marcelcoetzee/mambaforge-pypy3/envs/test

  Updating specs:

   - pip


  Package              Version  Build               Channel                  Size
───────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────

  + bzip2                1.0.8  h0d85af4_4          conda-forge/osx-64     Cached
  + ca-certificates  2021.10.8  h033912b_0          conda-forge/osx-64     Cached
  + libffi               3.4.2  h0d85af4_5          conda-forge/osx-64     Cached
  + libzlib             1.2.11  h9173be1_1013       conda-forge/osx-64     Cached
  + ncurses                6.2  h2e338ed_4          conda-forge/osx-64     Cached
  + openssl              3.0.0  h0d85af4_2          conda-forge/osx-64     Cached
  + pip                 21.3.1  pyhd8ed1ab_0        conda-forge/noarch     Cached
  + python              3.10.0  h38b4d05_3_cpython  conda-forge/osx-64      13 MB
  + python_abi            3.10  2_cp310             conda-forge/osx-64       4 KB
  + readline               8.1  h05e3726_0          conda-forge/osx-64     Cached
  + setuptools          59.2.0  py310h2ec42d9_0     conda-forge/osx-64       1 MB
  + sqlite              3.36.0  h23a322b_2          conda-forge/osx-64     Cached
  + tk                  8.6.11  h5dbffcc_1          conda-forge/osx-64     Cached
  + tzdata               2021e  he74cb21_0          conda-forge/noarch     Cached
  + wheel               0.37.0  pyhd8ed1ab_1        conda-forge/noarch     Cached
  + xz                   5.2.5  haf1e3a3_1          conda-forge/osx-64     Cached
  + zlib                1.2.11  h9173be1_1013       conda-forge/osx-64     Cached

  Summary:

  Install: 17 packages

  Total download: 14 MB

───────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] Y
Finished python_abi                           (00m:00s)               4 KB     16 KB/s
Finished setuptools                           (00m:00s)               1 MB    957 KB/s
Finished python                               (00m:05s)              13 MB      2 MB/s
Downloading  [====================================================================================================] (00m:08s)    2.39 MB/s
Extracting   [====================================================================================================] (00m:08s)        3 / 3
error    Path already locked by the same PID

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/mamba/mamba.py", line 922, in exception_converter
        raise e
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/mamba/mamba.py", line 916, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/mamba/mamba.py", line 874, in _wrapped_main
        result = do_call(args, p)
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/mamba/mamba.py", line 743, in do_call
        exit_code = create(args, parser)
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/mamba/mamba.py", line 627, in create
        return install(args, parser, "create")
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/mamba/mamba.py", line 594, in install
        handle_txn(conda_transaction, prefix, args, newenv)
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/mamba/linking.py", line 36, in handle_txn
        with lock_file(PackageCacheData.first_writable().pkgs_dir):
      File "/Users/marcelcoetzee/mambaforge-pypy3/lib-python/3/contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "/Users/marcelcoetzee/mambaforge-pypy3/site-packages/mamba/utils.py", line 34, in lock_file
        lock = api.LockFile(path)  # noqa F841
    RuntimeError: LockFile error.

`$ /Users/marcelcoetzee/mambaforge-pypy3/bin/mamba create -n test pip`

  environment variables:
      AUTOJUMP_ERROR_PATH=/Users/marcelcoetzee/Library/autojump/errors.log
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/marcelcoetzee/mambaforge-pypy3/bin/conda
         CONDA_PYTHON_EXE=/Users/marcelcoetzee/mambaforge-pypy3/bin/python
               CONDA_ROOT=/Users/marcelcoetzee/mambaforge-pypy3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
          PKG_CONFIG_PATH=/usr/local/opt/sqlite/lib/pkgconfig
         PYTHONBREAKPOINT=pudb.set_trace
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/marcelcoetzee/.condarc
 populated config files : /Users/marcelcoetzee/mambaforge-pypy3/.condarc
                          /Users/marcelcoetzee/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.7.12.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/marcelcoetzee/mambaforge-pypy3  (writable)
      conda av data dir : /Users/marcelcoetzee/mambaforge-pypy3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/marcelcoetzee/mambaforge-pypy3/pkgs
                          /Users/marcelcoetzee/.conda/pkgs
       envs directories : /Users/marcelcoetzee/mambaforge-pypy3/envs
                          /Users/marcelcoetzee/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.26.0 PyPy/3.7.12 Darwin/21.1.0 OSX/10.16
                UID:GID : 502:20
             netrc file : /Users/marcelcoetzee/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by wolfv** [comment]
This is fixed and we will release today.
Sorry for the inconvenience.

**Comment by adriendelsalle** [comment]
See https://github.com/mamba-org/mamba/issues/1285
