### ISSUE TITLE
More Unicode

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1311]
- [ ] It would be good to check if the current way we use libarchive works with unicode paths.
- [ ] Table does not compute correct string width when using Unicode
- [ ] Make activation work with Unicode on Windows cmd.exe and/or Powershell

**Comment by wolfv** [comment]
Maybe the Windows short paths could help with the unicode activation issues: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getshortpathnamew

**Comment by wolfv** [comment]
vcpkg might have some useful UTF8 helpers: https://github.com/microsoft/vcpkg-tool/blob/8ffc40c63adc8b9a742a641351ea90e3c906605e/src/vcpkg/base/unicode.cpp

**Comment by jaimergp** [comment]
0.19 has alleviated most of the unicode problems, but I still see issues with local channels on Windows.

To reproduce:

1. Create a unicode path on Windows and drop some fake repodata:

```
(base) D:\Users\jrodriguez\devel\conda>dir "D:\Users\jrodriguez\a_local_channel 0b74 한áō固ђγ家êôñßç"
 Volume in drive D is UserProfile
 Volume Serial Number is XXXX-YYYY

 Directory of D:\Users\jrodriguez\a_local_channel 0b74 한áō固ђγ家êôñßç

12/02/2021  06:56 PM    <DIR>          .
12/02/2021  06:56 PM    <DIR>          ..
12/02/2021  06:56 PM    <DIR>          noarch
12/02/2021  06:56 PM    <DIR>          win-64
               0 File(s)              0 bytes
               4 Dir(s)  101,621,604,352 bytes free
```

2.  Try install anything from that channel.

```
(base) D:\Users\jrodriguez\devel\conda>mamba install ok ok --dry-run -q -c "D:\Users\jrodriguez\a_local_channel 0b74 한áō固ђγ家êôñßç"

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Users\jrodriguez\conda\lib\site-packages\conda\exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "D:\Users\jrodriguez\conda\lib\site-packages\mamba\mamba.py", line 917, in exception_converter
        raise e
      File "D:\Users\jrodriguez\conda\lib\site-packages\mamba\mamba.py", line 911, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "D:\Users\jrodriguez\conda\lib\site-packages\mamba\mamba.py", line 869, in _wrapped_main
        result = do_call(args, p)
      File "D:\Users\jrodriguez\conda\lib\site-packages\mamba\mamba.py", line 734, in do_call
        exit_code = install(args, parser, "install")
      File "D:\Users\jrodriguez\conda\lib\site-packages\mamba\mamba.py", line 486, in install
        index = load_channels(pool, channels, repos)
      File "D:\Users\jrodriguez\conda\lib\site-packages\mamba\utils.py", line 122, in load_channels
        index = get_index(
      File "D:\Users\jrodriguez\conda\lib\site-packages\mamba\utils.py", line 80, in get_index
        for channel in api.get_channels(all_channels):
    RuntimeError: Could not set URL (code: 3 - url = file://D:/Users/jrodriguez/a_local_channel 0b74 한áō固ђγ家êôñßç)

`$ D:\Users\jrodriguez\conda\Scripts\mamba install ok ok --dry-run -q -c D:\Users\jrodriguez\a_local_channel 0b74 한áō固ђγ家êôñßç`

```

Conversely, the same command without unicode characters works:

```
(base) D:\Users\jrodriguez\devel\conda>mamba install ok --dry-run  -c "D:\Users\jrodriguez\a_local_channel"

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.19.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['ok', 'ok']

conda-forge/win-64       Using cache
conda-forge/noarch       Using cache
a_local_channel/win-64   [====================] (00m:00s) Done
a_local_channel/noarch   [====================] (00m:00s) Done

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - nothing provides requested ok
```

**Comment by wolfv** [comment]
Did you urlencode the channel? We probably need to do that so that libcurl understands it.

**Comment by jaimergp** [comment]
Yes, I am trying that in the conda integration (even bypassing the Windows C: unit), but it [fails](https://github.com/conda/conda/runs/4400735775?check_suite_focus=true#step:5:458) in the same way.

```
RuntimeError: Download error (37) Couldn't read a file:// file [file://C:/tmp/test_install_tarball_from_loca0/tmpd63i_lfv/c158%2520%25C3%25AA%25C3%25A1%25C5%258D%25C3%25B4%25C3%259F%25E5%25AE%25B6%25ED%2595%259C%25C3%25B1%25C3%25A7%25D1%2592%25CE%25B3%25E5%259B%25BA/noarch/repodata.json]
Couldn't open file C:/tmp/test_install_tarball_from_loca0/tmpd63i_lfv/c158%2520%25C3%25AA%25C3%25A1%25C5%258D%25C3%25B4%25C3%259F%25E5%25AE%25B6%25ED%2595%259C%25C3%25B1%25C3%25A7%25D1%2592%25CE%25B3%25E5%259B%25BA/noarch/repodata.json
```

The problem seems to be that is encoded twice?

```
>>> from urllib.parse import unquote
>>> unquote("c158%2520%25C3%25AA%25C3%25A1%25C5%258D%25C3%25B4%25C3%259F%25E5%25AE%25B6%25ED%2595%259C%25C3%25B1%25C3%25A7%25D1%2592%25CE%25B3%25E5%259B%25BA")
'c158%20%C3%AA%C3%A1%C5%8D%C3%B4%C3%9F%E5%AE%B6%ED%95%9C%C3%B1%C3%A7%D1%92%CE%B3%E5%9B%BA'
>>> unquote(unquote("c158%2520%25C3%25AA%25C3%25A1%25C5%258D%25C3%25B4%25C3%259F%25E5%25AE%25B6%25ED%2595%259C%25C3%25B1%25C3%25A7%25D1%2592%25CE%25B3%25E5%259B%25BA"))
'c158 êáōôß家한ñçђγ固'
```

Is the channel being further processed in libmamba land?

**Comment by jaimergp** [comment]
Hm, is `libcurl` compiled with [Unicode support on Windows](https://github.com/curl/curl/tree/master/winbuild#build-in-the-console) on conda-forge? I don't see any relevant flags [there](https://github.com/conda-forge/curl-feedstock/blob/master/recipe/bld.bat#L10).

**Comment by jaimergp** [comment]
Some more data points:

```
> curl -O "file://D:/Users/jrodriguez/a_local_channel 0b74 한áō固ђγ家êôñßç/noarch/repodata.json"
curl: (3) URL using bad/illegal format or missing URL
> curl -O "file:///D:/Users/jrodriguez/a_local_channel%200b74%20%ED%95%9C%C3%A1%C5%8D%E5%9B%BA%D1%92%CE%B3%E5%AE%B6%C3%AA%C3%B4%C3%B1%C3%9F%C3%A7/noarch/repodata.json"
curl: (37) Couldn't open file D:/Users/jrodriguez/a_local_channel%200b74%20%ED%95%9C%C3%A1%C5%8D%E5%9B%BA%D1%92%CE%B3%E5%AE%B6%C3%AA%C3%B4%C3%B1%C3%9F%C3%A7/noarch/repodata.json
curl -O "file://D:\Users\jrodriguez\a_local_channel%200b74%20%ED%95%9C%C3%A1%C5%8D%E5%9B%BA%D1%92%CE%B3%E5%AE%B6%C3%AA%C3%B4%C3%B1%C3%9F%C3%A7\noarch\repodata.json"
curl: (37) Couldn't open file D:\Users\jrodriguez\a_local_channel%200b74%20%ED%95%9C%C3%A1%C5%8D%E5%9B%BA%D1%92%CE%B3%E5%AE%B6%C3%AA%C3%B4%C3%B1%C3%9F%C3%A7\noarch\repodata.json
```

Firefox can open that URL with no issue (both encoded and raw unicode):

![image](https://user-images.githubusercontent.com/2559438/144521094-a2f006d9-ad3b-4b03-b8d5-49c48e999a06.png)

So... is it a compilation issue? I opened https://github.com/conda-forge/curl-feedstock/pull/100
