### ISSUE TITLE
unable to pin PyPI packages

### ISSUE THREAD

**Issue by mfansler** [mamba-org/mamba#1339]
## Overview
Conda supports pinning PyPI packages, however, Mamba errors out under these same configuration settings.

# Example

**environment.yaml**
```yaml
name: foo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy=1.21.4
```

**Creation**
```bash
mamba env create -n foo -f environment.yaml
```

**Pinning Configuration**
```bash
conda activate foo

# pin
echo 'numpy=1.21.4=pypi*' > ${CONDA_PREFIX}/conda-meta/pinned

# enable interop and respect pypi channel priority
conda config --env --set pip_interop_enabled True
conda config --env --set channel_priority flexible
```

## Conda Result
To test, let's install `scipy`, which has a NumPy dependency:

```bash
$ conda activate foo
$ conda install -d scipy
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mfansler/miniconda3/envs/foo

  added / updated specs:
    - scipy

The following NEW packages will be INSTALLED:

  libblas            conda-forge/osx-64::libblas-3.9.0-12_osx64_openblas
  libcblas           conda-forge/osx-64::libcblas-3.9.0-12_osx64_openblas
  libcxx             conda-forge/osx-64::libcxx-12.0.1-habf9029_0
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-9_3_0_h6c81a4c_23
  libgfortran5       conda-forge/osx-64::libgfortran5-9.3.0-h6c81a4c_23
  liblapack          conda-forge/osx-64::liblapack-3.9.0-12_osx64_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.18-openmp_h3351f45_0
  llvm-openmp        conda-forge/osx-64::llvm-openmp-12.0.1-hda6cdc1_1
  scipy              conda-forge/osx-64::scipy-1.7.3-py39h056f1c0_0

DryRunExit: Dry run. Exiting.
```

## Mamba Result 

```bash
$ conda activate foo
$ mamba install -d scipy

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.19.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['scipy']

pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
bioconda/osx-64          [====================] (00m:00s) Done
bioconda/noarch          [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:02s) Done
conda-forge/osx-64       [====================] (00m:05s) Done
error    No package can be installed for pin: numpy 1.21.4 pypi*
```

## Expected Result
Mamba should also be able to respect packages pinned to PyPI installations.

**Comment by jonashaag** [comment]
Does this still not work?

**Comment by mfansler** [comment]
@jonashaag no, it still does not work.

## Updated Results (`mamba=0.25.0`)

**Conda Behavior**
```bash
$ conda activate foo
$ conda install -d scipy
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mfansler/miniconda3/envs/foo

  added / updated specs:
    - scipy

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-1.9.1                |   py39h9488793_0        22.9 MB
    ------------------------------------------------------------
                                           Total:        22.9 MB

The following NEW packages will be INSTALLED:

  libblas            conda-forge/osx-64::libblas-3.9.0-16_osx64_openblas
  libcblas           conda-forge/osx-64::libcblas-3.9.0-16_osx64_openblas
  libcxx             conda-forge/osx-64::libcxx-14.0.6-hccf4f1f_0
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-10_4_0_h97931a8_25
  libgfortran5       conda-forge/osx-64::libgfortran5-11.3.0-h082f757_25
  liblapack          conda-forge/osx-64::liblapack-3.9.0-16_osx64_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.21-openmp_h429af6e_3
  llvm-openmp        conda-forge/osx-64::llvm-openmp-14.0.4-ha654fa7_0
  python_abi         conda-forge/osx-64::python_abi-3.9-2_cp39
  scipy              conda-forge/osx-64::scipy-1.9.1-py39h9488793_0

DryRunExit: Dry run. Exiting.
```

**Mamba Behavior**
```bash
$ mamba install -d scipy

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.25.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['scipy']

conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-64                                             Using cache
bioconda/noarch                                             Using cache
pkgs/main/noarch                                              No change
pkgs/r/osx-64                                                 No change
[+] 0.2s
pkgs/main/osx-64 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s Downlpkgs/main/osx-64                                              No change
pkgs/r/noarch                                                 No change
No package can be installed for pin: numpy 1.21.4 pypi*

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/mfansler/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/Users/mfansler/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/Users/mfansler/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/mfansler/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 886, in _wrapped_main
        result = do_call(args, p)
      File "/Users/mfansler/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 750, in do_call
        exit_code = install(args, parser, "install")
      File "/Users/mfansler/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 545, in install
        solver.add_pin(final_spec)
    RuntimeError: No package can be installed for pin: numpy 1.21.4 pypi*
```
