### ISSUE TITLE
Use `repodata.json.bz2` instead of plain json

### ISSUE THREAD

**Issue by xhochy** [mamba-org/mamba#1353]
It seems that the codebase already have things in place to use `bz2` compressed repodata but I see no option to select it. What could be an easy (hacky is OK) way to activate the usage of it? This would help to better bypass a corporate proxy.

**Comment by wolfv** [comment]
It's actually relatively useless because curl natively supports gzip encoding. Does the corporate proxy not let gzip encoded responses through?

The gzip encoded repodata is ~19Mb for conda-forge/linux-64. (vs ~150Mb unzipped, I guess, haven't checked in a while)

PS: There is ongoing work in https://github.com/mamba-org/powerloader to support `zchunk` which will help cut down repodata.json file sizes.

**Comment by xhochy** [comment]
The `bz2` files seem slightly more reliable, not sure how much. I'm still trying to get a bit more information together to file a bug report that explains a bit better what I am facing.

**Comment by wolfv** [comment]
(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding)

**Comment by xhochy** [comment]
Closing this, as this is probably more an issue of corporate proxy + old docker runtime. Switching to `podman` at least helped a bit. Still, as this corporate proxy is much fun, I've opened a small follow-up in https://github.com/mamba-org/mamba/issues/1361

**Comment by afranchuk** [comment]
For what it's worth, Artifactory conda repositories don't seem to support `Accept-Encoding: gzip`. However I submitted a [bug report](https://www.jfrog.com/jira/browse/RTFACT-27290) so hopefully they will act on it. But for now, it's making the index download painfully slow (for a conda-forge mirror).

**Comment by wolfv** [comment]
Can you work around that by setting the REPODATA_FN variable?

**Comment by afranchuk** [comment]
I don't have time to play with it now, but I expect that simply changing the filename won't work because curl won't implicitly decompress the file. But you can try; most repositories seem to host a `repodata.json.bz2` file.

**Comment by aborsu** [comment]
Stuck behind artifactory:

I tried setting the REPODATA_FNS variable but it fails, I expect because it tries to read a plain json file but gets compressed bytes: 
```bash
Collecting package metadata (repodata.json.bz2): ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\cli\main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
                    ^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\cli\conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\notices\core.py", line 121, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\cli\main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\cli\install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\common\io.py", line 84, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\concurrent\futures\_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\concurrent\futures\_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\concurrent\futures\_base.py", line 401, in __get_result
        raise self._exception
      File "C:\Users\not-me\micromamba\Lib\concurrent\futures\thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\subdir_data.py", line 158, in subdir_query
        return tuple(
               ^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\subdir_data.py", line 174, in query
        self.load()
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\subdir_data.py", line 264, in load
        _internal_state = self._load()
                          ^^^^^^^^^^^^
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\core\subdir_data.py", line 411, in _load
        cache.save(raw_repodata_str or "{}")
      File "C:\Users\not-me\micromamba\Lib\site-packages\conda\gateways\repodata\__init__.py", line 583, in save
        temp.write(data)
      File "C:\Users\not-me\micromamba\Lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 12-13: character maps to <undefined>

````

**Comment by j-neefs** [comment]
> For what it's worth, Artifactory conda repositories don't seem to support `Accept-Encoding: gzip`. However I submitted a [bug report](https://www.jfrog.com/jira/browse/RTFACT-27290) so hopefully they will act on it. But for now, it's making the index download painfully slow (for a conda-forge mirror).

I voted for your bug report as we are suffering from the same slowness 👍 May I ask how you worked around ? We use `ENV MAMBA_NO_LOW_SPEED_LIMIT=1` and are patient ....for now 😅
