### ISSUE TITLE
mamba 0.21.0 broken on Windows

### ISSUE THREAD

**Issue by davidbrochart** [mamba-org/mamba#1459]
See e.g. https://github.com/davidbrochart/akernel/runs/5118828844?check_suite_focus=true
```
      Traceback (most recent call last):
        File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 1079, in __call__
          return func(*args, **kwargs)
        File "C:\Miniconda\lib\site-packages\mamba\mamba.py", line 934, in exception_converter
          raise e
        File "C:\Miniconda\lib\site-packages\mamba\mamba.py", line 928, in exception_converter
          exit_code = _wrapped_main(*args, **kwargs)
        File "C:\Miniconda\lib\site-packages\mamba\mamba.py", line 882, in _wrapped_main
          result = do_call(args, p)
        File "C:\Miniconda\lib\site-packages\mamba\mamba.py", line 748, in do_call
          exit_code = create(args, parser)
        File "C:\Miniconda\lib\site-packages\mamba\mamba.py", line 624, in create
          return install(args, parser, "create")
        File "C:\Miniconda\lib\site-packages\mamba\mamba.py", line 577, in install
          if not transaction.prompt():
      UnboundLocalError: local variable 'transaction' referenced before assignment
```

**Comment by dhirschfeld** [comment]
It looks like `transaction` is defined in the *`else`* clause so if `newenv and not specs` is True it won't get defined.

![image](https://user-images.githubusercontent.com/881019/153112967-78054d08-3020-41c5-8fa4-a2ba87444a6d.png)
https://github.com/mamba-org/mamba/blob/f76f428dc601ce4a39782d030563554e0ac74aeb/mamba/mamba/mamba.py#L558

**Comment by davidbrochart** [comment]
And prior to #1350 `transaction` was not used if `use_mamba_experimental==False`.
But since it works on Linux and MacOS, I don't have a clue.

**Comment by wolfv** [comment]
Thanks @davidbrochart -- argh! Sorry, that sucks. 
So it looks like creating an empty environment without any specs is currently broken. I am having a look right now!
