### ISSUE TITLE
error Could not set lock (Input/output error)

### ISSUE THREAD

**Issue by iuryt** [mamba-org/mamba#1515]
I installed mamba in a Linux server.

```
wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
bash "Mambaforge-$(uname)-$(uname -m).sh"
```

What I am trying to do:
`mamba create -n myenv python=3.8`

The output:

```
                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.19.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python=3.8']

conda-forge/linux-64     [         <=>        ] (00m:01s) 4 MB / ?? (2.64 MB/s)
conda-forge/noarch       [         <=>        ] (00m:01s) 7 MB / ?? (4.20 MB/s)
error    Could not set lock (Input/output error)
warning  Cannot lock '/home/its21001/mambaforge/pkgs/cache'
    Waiting for other mamba process to finish
error    Could not set lock (Input/output error)
error    LockFile can't be set at '/home/its21001/mambaforge/pkgs/cache'
    This could be fixed by changing the locks' timeout or cleaning your environment from previous runs

```

It also created this Error Report.

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 917, in exception_converter
        raise e
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 911, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 869, in _wrapped_main
        result = do_call(args, p)
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 738, in do_call
        exit_code = create(args, parser)
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 614, in create
        return install(args, parser, "create")
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 486, in install
        index = load_channels(pool, channels, repos)
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/mamba/utils.py", line 122, in load_channels
        index = get_index(
      File "/home/its21001/mambaforge/lib/python3.9/site-packages/mamba/utils.py", line 103, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: LockFile error. Aborting.

`$ /home/its21001/mambaforge/bin/mamba create -n bceddies python=3.8`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/its21001/mambaforge/bin/conda
             CONDA_PREFIX=/home/its21001/mambaforge
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/its21001/mambaforge/bin/python
               CONDA_ROOT=/home/its21001/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/lib64:/usr/local/lib
              LD_RUN_PATH=/usr/lib64
                  MANPATH=/usr/share/man:/apps2/Modules/3.2.6/share/man:/usr/man
               MODULEPATH=/apps2/Modules/versions:/apps2/Modules/$MODULE_VERSION/modulefiles:/ap
                          ps2/Modules/modulefiles:
                     PATH=/home/its21001/mambaforge/bin:/home/its21001/mambaforge/condabin:/apps
                          2/Modules/3.2.6/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/
                          sbin:/sbin:/opt/ibutils/bin:/gpfs/gpfs1/slurm/misc/stubl/stubl-
                          master/bin:/home/its21001/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/its21001/mambaforge
            shell level : 1
       user config file : /home/its21001/.condarc
 populated config files : /home/its21001/mambaforge/.condarc
                          /home/its21001/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=2.6.32=0
                          __glibc=2.12=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/its21001/mambaforge  (writable)
      conda av data dir : /home/its21001/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/its21001/mambaforge/pkgs
                          /home/its21001/.conda/pkgs
       envs directories : /home/its21001/mambaforge/envs
                          /home/its21001/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Linux/2.6.32-642.13.1.el6.x86_64 rhel/6.7 glibc/2.12
                UID:GID : 744359:1537
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

I tried to delete everything inside `/home/its21001/mambaforge/pkgs/cache` and also tried to delete and reinstall Mamba. Both didn't fix the problem.

**Comment by wolfv** [comment]
Are you using a weird filesystem or have strange permissions (shared disk or so?)

**Comment by iuryt** [comment]
@wolfv 
I have permissions to write in my own home, where I am installing Mamba.
Can you help me to understand what you mean by weird filesystem?
Is that anything I could do to investigate that?

**Comment by wolfv** [comment]
This could be a similar issue as https://github.com/mamba-org/mamba/pull/1448 and https://github.com/mamba-org/mamba/issues/1446

I would like to know if you are on some sort of shared drive for example?

**Comment by iuryt** [comment]
I hope I am not bothering you with elementary questions.

How can I check if this is a case of a shared drive? I think it is because I am using a shared cluster.

But why would a shared drive be a problem for using and installing Mamba? I thought that as long as I have write permissions I would be able to install it locally.

**Comment by wolfv** [comment]
Yes it shouldn't be a problem but it might be possible that you eg don't have permissions to create lock files on a shared drive. This probably depends on some configuration settings. I'll need to figure out how to find them out

**Comment by wolfv** [comment]
Maybe you can use the mount command to see some info? https://www.thegeekdiary.com/how-to-find-the-mounting-options-of-currently-mounted-filesystem/amp/

**Comment by wolfv** [comment]
https://www.thegeekdiary.com/how-to-find-the-mounting-options-of-currently-mounted-filesystem/amp/

**Comment by iuryt** [comment]
Hi,

I am so sorry for taking that long to reply here. I had a short deadline and had to find another machine to run my code, but now I am back to this machine.

```
$ mount | grep data
ib-cn451:/data on /shared/cn451 type nfs (rw,noatime,hard,intr,sloppy,vers=4,addr=<some ip>,clientaddr=<some ip>)
```

and `cat /proc/mounts` returns a bunch of mounts with many ips I could not hide, but I can do that is you think is needed.

**Comment by L-of-IOS** [comment]
On my shared server, this issue stills exists.
mamba --version
mamba 0.23.3
conda 4.12.0

All disks are ext4 file system

**Comment by magcurly** [comment]
I have the same problem on certain computing node. Using the same file system and the same directory, one node is fine running mamba and the other failed with the same error.
mamba version is 0.25.0.
conda version is 4.13.0.

**Comment by iuryt** [comment]
I could "fix" the problem using Mamba in the compute nodes instead of the login nodes.

**Comment by magcurly** [comment]
> I could "fix" the problem using Mamba in the compute nodes instead of the login nodes.

The problem is that mamba doesn't work on the node which is able to connect to the internet. The login node is able to use Mamba but it will be shut down internet service in a few days. I haven't found solutions for the problem.

**Comment by iuryt** [comment]
> > I could "fix" the problem using Mamba in the compute nodes instead of the login nodes.
> 
> The problem is that mamba doesn't work on the node which is able to connect to the internet. The login node is able to use Mamba but it will be shut down internet service in a few days. I haven't found solutions for the problem.

Ouch.. That's true, many HPCs restrict internet access to the computer nodes.

**Comment by jonashaag** [comment]
In the next release it will be possible to disable lockfiles

**Comment by 77babyy** [comment]
I have the exact same issue,please help us!

**Comment by fuzailmalang-rgb** [comment]
import (
