### ISSUE TITLE
mamba install error

### ISSUE THREAD

**Issue by sheep-liu** [mamba-org/mamba#1574]
When I install software with mamba I got an error. And the error was not solved when I re-install mamba. I do not know how to solve this problem.

```bash
$ mamba install -y bowtie2

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bowtie2']

anaconda/pkgs/free/linux [====================] (00m:00s) No change
anaconda/cloud/conda-for [====================] (00m:00s) No change
anaconda/cloud/pytorch/l [====================] (00m:00s) No change
anaconda/pkgs/free/noarc [====================] (00m:00s) No change
anaconda/cloud/msys2/noa [====================] (00m:00s) No change
anaconda/cloud/menpo/lin [====================] (00m:00s) No change
anaconda/cloud/bioconda/ [====================] (00m:00s) No change
anaconda/cloud/menpo/noa [====================] (00m:00s) No change
anaconda/cloud/msys2/lin [====================] (00m:00s) No change
anaconda/cloud/conda-for [====================] (00m:00s) No change
anaconda/cloud/pytorch/n [====================] (00m:00s) No change
anaconda/cloud/bioconda/ [====================] (00m:00s) No change
anaconda/pkgs/main/noarc [====================] (00m:00s) No change
anaconda/pkgs/main/linux [====================] (00m:00s) No change

Pinned packages:
  - python 3.8.*


WARNING Package tarball '/public/home/TEST/miniconda3/envs/epigenetics/pkgs/zlib-1.2.11-h36c2ea0_1013.tar.bz2' is invalid
WARNING Package tarball '/public/home/TEST/miniconda3/envs/epigenetics/pkgs/zstd-1.5.2-ha95c52a_0.tar.bz2' is invalid
WARNING Package tarball '/public/home/TEST/miniconda3/envs/epigenetics/pkgs/bowtie2-2.4.5-py38hfbc8389_2.tar.bz2' is invalid
Transaction

  Prefix: /public/home/TEST/miniconda3/envs/epigenetics

  Updating specs:

   - bowtie2
   - ca-certificates
   - certifi
   - openssl


  Package              Version  Build           Channel                                                                Size
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  + bowtie2              2.4.5  py38hfbc8389_2  mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64         14 MB
  + libzlib             1.2.11  h36c2ea0_1013   mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64      59 KB
  + tbb                 2020.3  hfd86e86_0      mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64             Cached

  Change:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  - certifi          2021.10.8  py38h578d9bd_1  installed
  + certifi          2021.10.8  py38h06a4308_2  mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64             Cached
  - zlib                1.2.11  0               installed
  + zlib                1.2.11  h36c2ea0_1013   mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64      86 KB

  Upgrade:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  - ca-certificates  2021.10.8  ha878542_0      installed
  + ca-certificates   2022.2.1  h06a4308_0      mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64             122 KB
  - zstd                 1.5.0  ha4553b6_1      installed
  + zstd                 1.5.2  ha95c52a_0      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     458 KB

  Summary:

  Install: 3 packages
  Change: 2 packages
  Upgrade: 2 packages

  Total download: 15 MB

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Downloading  [==>                                                                                                 ] (00m:00s)    2.35 MB/s
Extracting   [>                                                                                                   ] (--:--)
ERROR   File not valid: file size doesn't match expectation "/public/home/TEST/miniconda3/envs/epigenetics/pkgs/zstd-1.5.2-ha95c52a_0.tar.bz2"
        Expected: 469140
File size validation error.
Downloading  [==================================================================================================> ] (00m:00s)   72.47 MB/s
Extracting   [>                                                                                                   ] (--:--)
ERROR   File not valid: file size doesn't match expectation "/public/home/TEST/miniconda3/envs/epigenetics/pkgs/bowtie2-2.4.5-py38hfbc8389_2.tar.bz2"
        Expected: 15108023
File size validation error.
Downloading  [==================================================================================================> ] (00m:00s)   59.41 MB/s
Extracting   [>                                                                                                   ] (--:--)
ERROR   File not valid: file size doesn't match expectation "/public/home/TEST/miniconda3/envs/epigenetics/pkgs/libzlib-1.2.11-h36c2ea0_1013.tar.bz2"
        Expected: 59956
File size validation error.
Finished ca-certificates                      (00m:00s)             122 KB    129 KB/s
Downloading  [====================================================================================================] (00m:00s)   12.73 MB/s
Extracting   [====================>                                                                               ] (00m:00s)        1 / 5
ERROR   File not valid: file size doesn't match expectation "/public/home/TEST/miniconda3/envs/epigenetics/pkgs/zlib-1.2.11-h36c2ea0_1013.tar.bz2"
        Expected: 88215
File size validation error.
Downloading  [====================================================================================================] (00m:00s)   12.73 MB/s
Extracting   [====================>                                                                               ] (00m:00s)        1 / 5

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/public/home/TEST/miniconda3/envs/epigenetics/lib/python3.8/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/public/home/TEST/miniconda3/envs/epigenetics/lib/python3.8/site-packages/mamba/mamba.py", line 927, in exception_converter
        raise e
      File "/public/home/TEST/miniconda3/envs/epigenetics/lib/python3.8/site-packages/mamba/mamba.py", line 921, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/public/home/TEST/miniconda3/envs/epigenetics/lib/python3.8/site-packages/mamba/mamba.py", line 879, in _wrapped_main
        result = do_call(args, p)
      File "/public/home/TEST/miniconda3/envs/epigenetics/lib/python3.8/site-packages/mamba/mamba.py", line 757, in do_call
        exit_code = install(args, parser, "install")
      File "/public/home/TEST/miniconda3/envs/epigenetics/lib/python3.8/site-packages/mamba/mamba.py", line 613, in install
        downloaded = transaction.prompt(repos)
    RuntimeError: Found incorrect download: libzlib. Aborting

`$ /public/home/TEST/miniconda3/envs/epigenetics/bin/mamba install -y bowtie2`

  environment variables:
                 CIO_TEST=<not set>
   CONDA_BACKUP_JAVA_HOME=
CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=
        CONDA_DEFAULT_ENV=epigenetics
                CONDA_EXE=/public/home/TEST/miniconda3/bin/conda
             CONDA_PREFIX=/public/home/TEST/miniconda3/envs/epigenetics
           CONDA_PREFIX_1=/public/home/TEST/miniconda3
    CONDA_PROMPT_MODIFIER=(epigenetics)
         CONDA_PYTHON_EXE=/public/home/TEST/miniconda3/bin/python
               CONDA_ROOT=/public/home/TEST/miniconda3/envs/epigenetics
              CONDA_SHLVL=2
                    CPATH=/public/software//compiler/intel/intel-
                          compiler-2017.5.239/mkl/include:
           CURL_CA_BUNDLE=<not set>
                    FPATH=/public/software//compiler/intel/intel-
                          compiler-2017.5.239/mkl/include:
     JAVA_LD_LIBRARY_PATH=/public/home/TEST/miniconda3/envs/epigenetics/jre/lib/amd64/server
          LD_LIBRARY_PATH=/public/software//mpi/openmpi/intel/2.1.2/lib:/public/software//compil
                          er/intel/intel-compiler-2017.5.239/compiler/lib/intel64:/public/softwa
                          re//compiler/intel/intel-compiler-2017.5.239/mkl/lib/intel64:/public/s
                          oftware//compiler/intel/intel-compiler-2017.5.239/tbb/lib/intel64:
             LIBRARY_PATH=/public/software//compiler/intel/intel-compiler-2017.5.239/compiler/li
                          b/intel64:/public/software//compiler/intel/intel-compiler-2017.5.239/m
                          kl/lib/intel64:/public/software//compiler/intel/intel-
                          compiler-2017.5.239/tbb/lib/intel64
                  MANPATH=/public/software//mpi/openmpi/intel/2.1.2/share/man:/public/software//
                          compiler/intel/intel-compiler-2017.5.239/man/en_US:
      MIC_LD_LIBRARY_PATH=/public/software//compiler/intel/intel-compiler-2017.5.239/compiler/li
                          b/mic:/public/software//compiler/intel/intel-
                          compiler-2017.5.239/mkl/lib/mic:
                  NLSPATH=/public/software//compiler/intel/intel-compiler-2017.5.239compiler/lib
                          /intel64/locale/%l_%t/%N:/public/software//compiler/intel/intel-
                          compiler-2017.5.239/mkl/lib/intel64/locale/%l_%t/%N:
                     PATH=/public/home/TEST/miniconda3/envs/epigenetics/bin:/public/home/yang
                          liu/miniconda3/condabin:/public/home/TEST/program/firefox/firefox_d
                          river:/public/home/TEST/program/firefox/firefox:/public/home/yangli
                          u/program/minion:/public/home/TEST/wes_cancer/biosoft/annovar:/publ
                          ic/home/TEST/program/biosoft/bowtie2-2.4.2-linux-x86_64:/public/hom
                          e/TEST/.aspera/connect/bin:/public/home/TEST/wes_cancer/biosoft/
                          gatk-4.2.2.0:/public/home/TEST/program/novogene/linuxnd:/public/hom
                          e/TEST/program/homer/bin:/public/home/TEST/.local/bin:/public/ho
                          me/TEST/program/tree/bin:/usr/lib64/qt-3.3/bin:/public/home/TEST
                          /perl5/bin:/public/software/mpi/openmpi/intel/2.1.2/bin:/public/softwa
                          re/compiler/intel/intel-compiler-2017.5.239/bin/intel64:/usr/local/bin
                          :/usr/bin:/usr/local/sbin:/usr/sbin:/public/home/TEST/.local/bin:/p
                          ublic/home/TEST/bin
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /public/home/TEST/miniconda3/envs/epigenetics
            shell level : 2
       user config file : /public/home/TEST/.condarc
 populated config files : /public/home/TEST/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.12.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /public/home/TEST/miniconda3/envs/epigenetics  (writable)
      conda av data dir : /public/home/TEST/miniconda3/envs/epigenetics/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
          package cache : /public/home/TEST/miniconda3/envs/epigenetics/pkgs
                          /public/home/TEST/.conda/pkgs
       envs directories : /public/home/TEST/miniconda3/envs/epigenetics/envs
                          /public/home/TEST/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.12 Linux/3.10.0-693.el7.x86_64 centos/7.4.1708 glibc/2.17
                UID:GID : 1040:1007
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by mfansler** [comment]
That sounds like an issue with the metadata in the mirror, not a `mamba`-specific issue.

**Comment by sheep-liu** [comment]
Thanks for your reply, and the error was solved although I did not understand why this happens. Anyway, thanks a lot.

**Comment by caishengxiang** [comment]
> 感谢您的回复，虽然我不明白为什么会发生这种情况，但错误已解决。无论如何，非常感谢。

Hi, can I ask how to solve it?

**Comment by caishengxiang** [comment]
> Thanks for your reply, and the error was solved although I did not understand why this happens. Anyway, thanks a lot.

Hi, can I ask how to solve it?

**Comment by limbo1996** [comment]
> 

I also had this problem, then after I changed the conda channels to the default, the error disappeared

**Comment by sheep-liu** [comment]
> > 
> 
> I also had this problem, then after I changed the conda channels to the default, the error disappeared

Thanks for your reply, and I do the same thing and the error disappeared. Thanks a lot
