### ISSUE TITLE
Bug while installing a package from a password protected conda channel

### ISSUE THREAD

**Issue by mmabrouk** [mamba-org/mamba#1593]
I have tried to install a package from a password protected conda channel (the package is pyrosetta).
I first added the channel to my condarc in the format https://USERNAME:PASSWORD@conda.graylab.jhu.edu
When running conda install pyrosetta I got the following error:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/scratch/mahmoud/mambaforge/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/scratch/mahmoud/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 882, in exception_converter
        raise e
      File "/scratch/mahmoud/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/scratch/mahmoud/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "/scratch/mahmoud/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 716, in do_call
        exit_code = install(args, parser, "install")
      File "/scratch/mahmoud/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 586, in install
        conda_transaction = to_txn(
      File "/scratch/mahmoud/mambaforge/lib/python3.9/site-packages/mamba/utils.py", line 245, in to_txn
        for _, pkg in to_unlink:
    KeyError: 'https://xxxxxx:xxxxxx@conda.graylab.jhu.edu/linux-64'

`$ /scratch/mahmoud/mambaforge/bin/mamba install pyrosetta`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/scratch/mahmoud/mambaforge/bin/conda
             CONDA_PREFIX=/scratch/mahmoud/mambaforge
    CONDA_PROMPT_MODIFIER=(base)
   CONDA_PYTHONBREAKPOINT=
         CONDA_PYTHON_EXE=/scratch/mahmoud/mambaforge/bin/python
               CONDA_ROOT=/scratch/mahmoud/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=:/scratch/bio/modeller/lib/x86_64-intel8/
                  MANPATH=/opt/xcat/share/man:
               MODULEPATH=/opt/ohpc/pub/modulefiles
                     PATH=/scratch/apps/stubl-0.0.10/bin:/scratch/mahmoud/mambaforge/bin:/scratc
                          h/mahmoud/mambaforge/condabin:/scratch/sofa/v17.06_no_backtrace/build/
                          bin:/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools:/usr/local
                          /bin:/usr/bin:/usr/local/sbin:/usr/sbin:/scratch/bio/EMBOSS-6.6.0/embo
                          ss:/scratch/bio/modeller/bin:/home/users/m/mmabrouk/.local/bin:/home/u
                          sers/m/mmabrouk/bin
         PYTHONBREAKPOINT=ipdb.set_trace
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
__LMOD_REF_COUNT_MODULEPATH=/opt/ohpc/pub/modulefiles:1

     active environment : base
    active env location : /scratch/mahmoud/mambaforge
            shell level : 1
       user config file : /home/users/m/mmabrouk/.condarc
 populated config files : /scratch/mahmoud/mambaforge/.condarc
                          /home/users/m/mmabrouk/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.7.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /scratch/mahmoud/mambaforge  (writable)
      conda av data dir : /scratch/mahmoud/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://xxxxx:xxxxxxx@conda.graylab.jhu.edu/linux-64
                          https://xxxxxxxxx:xxxxxxxx@conda.graylab.jhu.edu/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /scratch/mahmoud/mambaforge/pkgs
                          /home/users/m/mmabrouk/.conda/pkgs
       envs directories : /scratch/mahmoud/mambaforge/envs
                          /home/users/m/mmabrouk/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.7 Linux/3.10.0-957.12.1.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 265099:100
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

--- 

To fix the problem I went to my site-packages/mamba/utils.py and modified the function to_txn from:
```
    lookup_dict = {}
    for _, c in index:
        lookup_dict[c.url(with_credentials=False)] = c

```
```
    lookup_dict = {}
    for _, c in index:
        lookup_dict[c.url(with_credentials=False)] = c
        lookup_dict[c.url(with_credentials=True)] = c

```
To be honest I am not sure what exactly the code does. But it seems to build a lookup table here with the urls without the credentials but do the lookup later (sdir = lookup_dict[split_anaconda_token(c)[0]]) with the credentials.

**Comment by jonashaag** [comment]
Can you try to come up with some instructions to reproduce the bug that doesn't require access to your private channel?
