### ISSUE TITLE
Mamba does not fail gracefully when channel doesn't exist or when it is mistyped

### ISSUE THREAD

**Issue by croth1** [mamba-org/mamba#1641]
# environment.yml
test.yml
```
name: crash_and_burn
dependencies:
  - condo-forge::mamba
```
Note the spelling error in channel name `condo-forge` vs `conda-forge`.

# mamba
`mamba env create -f  test.yml --dry-run` crashes with:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/christian/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 120, in execute
        solved_env = installer.dry_run(pkg_specs, args, env)
      File "/Users/christian/miniconda3/lib/python3.9/site-packages/mamba/mamba_env.py", line 178, in mamba_dry_run
        return mamba_install(
      File "/Users/christian/miniconda3/lib/python3.9/site-packages/mamba/mamba_env.py", line 53, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/Users/christian/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 122, in load_channels
        index = get_index(
      File "/Users/christian/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 103, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Multi-download failed.
```

# conda
conda seems to catch the error: `conda env create -f  test.yml --dry-run`
```
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: condo-forge
  channel url: https://conda.anaconda.org/condo-forge
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

**Comment by pertetotale** [comment]
maybe a typo thing:  change 
dependencies:
  - condo-forge::mamba
 to
dependencies:
  - conda-forge::mamba

**Comment by Titus-von-Koeller** [comment]
Hi everyone,

despite the prior comment being marked off-topic, it was the fix to overcome the exact same error, as outlined in this issue, for me.

I had mistyped `conda-forge` and instead used `conde-forga`: Fixing the typo also fixed the issue, despite the error message being seemingly unrelated.

**Comment by jjerphan** [comment]
mamba and micromamba 2.0 have informative error messages in this case.

https://github.com/mamba-org/mamba/pull/3634 hints about potential causes of the error.

**Comment by jjerphan** [comment]
Actually, we think the errors message as of 2.0, i.e.:

```
critical libmamba Multiple errors occurred:
    Transfer finalized, status: 404 [https://conda.anaconda.org/condo-forge/noarch/repodata.json] 2750 bytes
    Subdir conda-forge/noarch not loaded!
    Subdir condo-forge/noarch not loaded!
```

is quite explicit.

Hence I am closing this issue as completed, but please comment if you think the errors needs more hints.
