### ISSUE TITLE
mamba install RuntimeError: LockFile error. Aborting.

### ISSUE THREAD

**Issue by buer19970329** [mamba-org/mamba#1729]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/konglab/anaconda3/envs/mine39/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/konglab/anaconda3/envs/mine39/lib/python3.9/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/home/konglab/anaconda3/envs/mine39/lib/python3.9/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/konglab/anaconda3/envs/mine39/lib/python3.9/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(args, p)
      File "/home/konglab/anaconda3/envs/mine39/lib/python3.9/site-packages/mamba/mamba.py", line 750, in do_call
        exit_code = install(args, parser, "install")
      File "/home/konglab/anaconda3/envs/mine39/lib/python3.9/site-packages/mamba/mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
      File "/home/konglab/anaconda3/envs/mine39/lib/python3.9/site-packages/mamba/utils.py", line 129, in load_channels
        index = get_index(
      File "/home/konglab/anaconda3/envs/mine39/lib/python3.9/site-packages/mamba/utils.py", line 110, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: LockFile error. Aborting.

**Comment by jmague** [comment]
exact same issue here...  I didn't try conda, but sudoing worked well to.

**Comment by magcurly** [comment]
It's quite weird that during loading the repositories, the others won't move any further when one of the progress bars reached to the end. After a period of time, this error will show up. `conda install` works perfectly. I agree that it might be some setting problems because this error only appears in certain nodes.

**Comment by pyrevo** [comment]
Guess I had a similar issue:

`
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/sw/bioinfo-tools/sources/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/opt/sw/bioinfo-tools/sources/anaconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/sw/bioinfo-tools/sources/anaconda3/lib/python3.8/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/opt/sw/bioinfo-tools/sources/anaconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 156, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/opt/sw/bioinfo-tools/sources/anaconda3/lib/python3.8/site-packages/mamba/mamba_env.py", line 55, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/opt/sw/bioinfo-tools/sources/anaconda3/lib/python3.8/site-packages/mamba/utils.py", line 129, in load_channels
        index = get_index(
      File "/opt/sw/bioinfo-tools/sources/anaconda3/lib/python3.8/site-packages/mamba/utils.py", line 110, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: LockFile error. Aborting.
`

It got solved after running `conda clean --all` (from the admin account).
