### ISSUE TITLE
Undefined symbol: archive_write_add_filter_zstd

### ISSUE THREAD

**Issue by vallsv** [mamba-org/mamba#1775]
Hi,

Since few days i have problems to install properly mamba.

I though it was local issues, but in case:

```
> conda create -n foo python=3.7.* git mamba
> conda activate foo
> mamba
Traceback (most recent call last):
  File "/users/blissadm/conda/miniconda/envs/foo/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../libmamba.so.2: undefined symbol: archive_write_add_filter_zstd
```

Sounds like the libarchive from the system is used
```
> ldd /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../libmamba.so.2
	linux-vdso.so.1 (0x00007ffdd2916000)
	libsolv.so.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libsolv.so.1 (0x00007f5c340e0000)
	libsolvext.so.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libsolvext.so.1 (0x00007f5c340c7000)
	libarchive.so.13 => /usr/lib/x86_64-linux-gnu/libarchive.so.13 (0x00007f5c3398f000)
	libcurl.so.4 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libcurl.so.4 (0x00007f5c33fff000)
	libcrypto.so.1.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libcrypto.so.1.1 (0x00007f5c336bb000)
	libyaml-cpp.so.0.7 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libyaml-cpp.so.0.7 (0x00007f5c33634000)
	libreproc++.so.14 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libreproc++.so.14 (0x00007f5c33ff7000)
	libreproc.so.14 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libreproc.so.14 (0x00007f5c33fee000)
	libstdc++.so.6 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libstdc++.so.6 (0x00007f5c33480000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5c3317c000)
	libgcc_s.so.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libgcc_s.so.1 (0x00007f5c33fd3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5c32ddd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5c33f5c000)
	libz.so.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../././libz.so.1 (0x00007f5c33fb9000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f5c32ba6000)
	libacl.so.1 => /lib/x86_64-linux-gnu/libacl.so.1 (0x00007f5c3299d000)
	liblzo2.so.2 => /lib/x86_64-linux-gnu/liblzo2.so.2 (0x00007f5c3277b000)
	liblzma.so.5 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././liblzma.so.5 (0x00007f5c33f8e000)
	liblz4.so.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././liblz4.so.1 (0x00007f5c32740000)
	libbz2.so.1.0 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libbz2.so.1.0 (0x00007f5c3272c000)
	libxml2.so.2 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././libxml2.so.2 (0x00007f5c325c4000)
	libnghttp2.so.14 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../././libnghttp2.so.14 (0x00007f5c3259b000)
	libssh2.so.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../././libssh2.so.1 (0x00007f5c32557000)
	libssl.so.1.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../././libssl.so.1.1 (0x00007f5c324c6000)
	libgssapi_krb5.so.2 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../././libgssapi_krb5.so.2 (0x00007f5c32473000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5c3226b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5c3204e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5c31e4a000)
	libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 (0x00007f5c31c45000)
	libicuuc.so.58 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../././libicuuc.so.58 (0x00007f5c31a92000)
	libkrb5.so.3 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././././libkrb5.so.3 (0x00007f5c319bb000)
	libk5crypto.so.3 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././././libk5crypto.so.3 (0x00007f5c319a1000)
	libcom_err.so.3 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././././libcom_err.so.3 (0x00007f5c33f82000)
	libkrb5support.so.0 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././././libkrb5support.so.0 (0x00007f5c31992000)
	libkeyutils.so.1 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././././libkeyutils.so.1 (0x00007f5c3198b000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f5c31774000)
	libicudata.so.58 => /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../.././././libicudata.so.58 (0x00007f5c2fe72000)
```

libarchive is installed in the env
```
> conda list archive
# packages in environment at /users/blissadm/conda/miniconda/envs/foo:
#
# Name                    Version                   Build  Channel
libarchive                3.5.2                h5de8990_0  
```

Here is the installed mamba
```
> conda list mamba
# packages in environment at /users/blissadm/conda/miniconda/envs/foo:
#
# Name                    Version                   Build  Channel
libmamba                  0.24.0               hd8a31e3_1    conda-forge
libmambapy                0.24.0           py37h1ee4b26_1    conda-forge
mamba                     0.24.0           py37h6dacc13_1    conda-forge
```

Do you have any idea if all this things are normal?

**Comment by vallsv** [comment]
I have noticed libarchive was not installed from conda-forge

```
conda install libarchive==3.5.2 -c conda-forge
```
With that extra update, everything looks to work fine

Feel free to close the issue. I am not sure there a problem or not.

**Comment by wolfv** [comment]
Hey, yes, it's very likely that not using conda forge is the problem here. Sorry about that

**Comment by Netzach** [comment]
Could this be fixed so that using a mirrored version of conda-forge works? We are using a mirror on a secure system without internet access and mamba is very popular.

**Comment by wolfv** [comment]
@Netzach A mirrored version of conda-forge should work fine. I think the main issue is when you're mixing with "defaults" channel ...

**Comment by Netzach** [comment]
@wolfv Thanks for the answer. Does it work with conda 4.13 now as well? That would be great for my mirroring script.

**Comment by wolfv** [comment]
latest mamba and latest conda work fine together, yes.

**Comment by Netzach** [comment]
@wolfv Awesome! Thanks!

**Comment by vallsv** [comment]
I close the issue, as i feel everything is fine.

**Comment by aleksey-hariton** [comment]
Dont know how its possibly to close the issue when its not resolved...

Problem is that `libmamba.so.2` build with dependency on 

```
 ldd /users/blissadm/conda/miniconda/envs/foo/lib/python3.7/site-packages/libmambapy/../../../libmamba.so.2
...
	libarchive.so.13 => /usr/lib/x86_64-linux-gnu/libarchive.so.13 (0x00007f5c3398f000)
```

but `libarchive` shipped with conda/mamba contains only `libarchive.so.18` or `libarchive.so.19`


Dont know how to solve it correctly, but what I did:

```
find /you_conda_folder/ -name 'libarchive.so'
cd /to_the_lib_folders/
ln -s libarchive.so libarchive.so.13
```

**Comment by wolfv** [comment]
where did you get `libarchive` from? The `conda-forge` package should definitely work.

**Comment by abossenbroek** [comment]
Full output of `conda install mamba -yc conda-forge` is

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |       2_kmp_llvm           6 KB  conda-forge
    ca-certificates-2022.12.7  |       ha878542_0         143 KB  conda-forge
    certifi-2022.12.7          |     pyhd8ed1ab_0         147 KB  conda-forge
    conda-22.11.1              |  py310hff52083_1         913 KB  conda-forge
    fmt-9.1.0                  |       h924138e_0         185 KB  conda-forge
    libarchive-3.5.2           |       h5de8990_0         828 KB
    libgcc-ng-12.2.0           |      h65d4601_19         931 KB  conda-forge
    libiconv-1.17              |       h166bdaf_0         1.4 MB  conda-forge
    libmamba-1.1.0             |       h2c5f835_2         1.4 MB  conda-forge
    libmambapy-1.1.0           |  py310h5976e0f_2         308 KB  conda-forge
    libsolv-0.7.22             |       he621ea3_0         436 KB
    libstdcxx-ng-12.2.0        |      h46fd767_19         4.3 MB  conda-forge
    llvm-openmp-14.0.6         |       h9e868ea_0         4.4 MB
    mamba-1.1.0                |  py310hf87f941_2          47 KB  conda-forge
    openssl-1.1.1s             |       h0b41bf4_1         1.9 MB  conda-forge
    pcre2-10.37                |       h032f7d1_0         1.1 MB  conda-forge
    pybind11-abi-4             |       hd8ed1ab_3          10 KB  conda-forge
    python_abi-3.10            |          2_cp310           4 KB  conda-forge
    reproc-14.2.4              |       h0b41bf4_0          30 KB  conda-forge
    reproc-cpp-14.2.4          |       hcb278e6_0          21 KB  conda-forge
    yaml-cpp-0.7.0             |       h27087fc_2         215 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        18.5 MB

The following NEW packages will be INSTALLED:

  fmt                conda-forge/linux-64::fmt-9.1.0-h924138e_0
  libmamba           conda-forge/linux-64::libmamba-1.1.0-h2c5f835_2
  libmambapy         conda-forge/linux-64::libmambapy-1.1.0-py310h5976e0f_2
  libsolv            pkgs/main/linux-64::libsolv-0.7.22-he621ea3_0
  llvm-openmp        pkgs/main/linux-64::llvm-openmp-14.0.6-h9e868ea_0
  mamba              conda-forge/linux-64::mamba-1.1.0-py310hf87f941_2
  pcre2              conda-forge/linux-64::pcre2-10.37-h032f7d1_0
  pybind11-abi       conda-forge/noarch::pybind11-abi-4-hd8ed1ab_3
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310
  reproc             conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0
  reproc-cpp         conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  yaml-cpp           conda-forge/linux-64::yaml-cpp-0.7.0-h27087fc_2

The following packages will be REMOVED:

  libgomp-11.2.0-h1234567_1

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2022.10.11~ --> conda-forge::ca-certificates-2022.12.7-ha878542_0
  certifi            pkgs/main/linux-64::certifi-2022.9.24~ --> conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0
  libgcc-ng          pkgs/main::libgcc-ng-11.2.0-h1234567_1 --> conda-forge::libgcc-ng-12.2.0-h65d4601_19
  libiconv              pkgs/main::libiconv-1.16-h7f8727e_2 --> conda-forge::libiconv-1.17-h166bdaf_0
  libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-12.2.0-h46fd767_19
  openssl              pkgs/main::openssl-1.1.1s-h7f8727e_0 --> conda-forge::openssl-1.1.1s-h0b41bf4_1

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex          pkgs/main::_openmp_mutex-5.1-1_gnu --> conda-forge::_openmp_mutex-4.5-2_kmp_llvm
  conda              pkgs/main::conda-22.11.1-py310h06a430~ --> conda-forge::conda-22.11.1-py310hff52083_1

The following packages will be DOWNGRADED:

  libarchive                               3.6.1-hab531cd_0 --> 3.5.2-h5de8990_0
```

my error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/opt/conda/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/opt/conda/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
```

on,

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

in `/opt/conda/lib/` there is `libarchive.so.18` after running `cd /opt/conda && ln -s libarchive.so.18 libarchive.so.13` I can successfully run mamba.

**Comment by wolfv** [comment]
hmm, sorry that you have these issues. It's two issues:

- libarchive compiled with CMake has a different "soname" (so.18).
- for some reason you get `libarchive` from Anaconda channels and not conda-forge (which we cannot really support).

**Comment by abossenbroek** [comment]
thanks @wolfv I forced reinstall libarchive from `conda-forge` using `$ conda install libarchive --force-reinstall -yc conda-forge` and now things look good.

**Comment by zek1th** [comment]
> 

this really helped! thank u

**Comment by rikrdo89** [comment]
this is the only thing that worked for me . Thanks!
`$ conda install libarchive --force-reinstall -yc conda-forge`

**Comment by aewrwdw** [comment]
> thanks @wolfv I forced reinstall libarchive from `conda-forge` using `$ conda install libarchive --force-reinstall -yc conda-forge` and now things look good.

The comment counts a lot! Thank you so much!!
