### ISSUE TITLE
problem with conda._vendor.auxlib on "outdated" versions

### ISSUE THREAD

**Issue by ReimarBauer** [mamba-org/mamba#1832]
We need a way to block none working installations or warn the users before they try that.

```
conda create -n mytest mamba python==3.7
conda activate mytest

```

```
(mytest) ~$ mamba --version
Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mytest/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/reimar/miniconda3/envs/mytest/lib/python3.7/site-packages/mamba/mamba.py", line 53, in <module>
    from mamba.utils import get_index, to_package_record_from_subjson, _supplement_index_with_system
  File "/home/reimar/miniconda3/envs/mytest/lib/python3.7/site-packages/mamba/utils.py", line 7, in <module>
    from .FastSubdirData import FastSubdirData
  File "/home/reimar/miniconda3/envs/mytest/lib/python3.7/site-packages/mamba/FastSubdirData.py", line 23, in <module>
    from conda._vendor.auxlib.ish import dals
ModuleNotFoundError: No module named 'conda._vendor.auxlib'
```

```
conda list mamba
# packages in environment at /home/reimar/miniconda3/envs/mytest:
#
# Name                    Version                   Build  Channel
mamba                     0.1.2            py37h99015e2_0    conda-forge
```

**Comment by jonashaag** [comment]
IIUC this is hard to fix because this old version of Mamba has incorrect Conda compat pinnings (Conda made incompatible changes).
