### ISSUE TITLE
mamba env lists environments two times

### ISSUE THREAD

**Issue by StefRe** [mamba-org/mamba#1940]
I made a fresh install of mamba on Windows using the [mambaforge](https://github.com/conda-forge/miniforge/releases/download/4.14.0-0/Mambaforge-pypy3-Windows-x86_64.exe) installer.

Right after installation I do `conda env list` and it shows me one enviroement (`base`).
```
(base) PS C:\> conda env list
# conda environments:
#
base                     C:\programs\mambaforge

```

If I do the same with `mamba` (`mamba env list`) it shows this environment two times - with and without its name (also note the different capitalization of `C` and `P`:
```
(base) PS C:\> mamba env list
# conda environments:
#
                         C:\programs\mambaforge
base                     c:\Programs\mambaforge
```
I understand that this is one and the same environment (folder names are case-insensitive on Windows) but I find this still confusing (especially if you have multiply environments - at first I though I made some mistake therefore I started over with a fresh install but the issue remains).

(using `mamba/conda info --envs` results in exactly the same output)

Is this a bug or should `mamba` not be used instead of `conda` for listing environments?

**Comment by wolfv** [comment]
It's curious because under the hood, both should be using the same functions (mamba just calls into conda). It could be that we lowercase the current environment path somewhere but I wasn't aware of that.

**Comment by StefRe** [comment]
It becomes more confusing after I made another [`env`](https://github.com/matplotlib/matplotlib/blob/main/environment.yml) (note also the sometimes missing asterisk for the current env):

**from `base` list envs:**
```
(base) PS C:\> mamba env list
# conda environments:
#
                         C:\programs\mambaforge
base                     c:\Programs\mambaforge
mpl-dev                  c:\Programs\mambaforge\envs\mpl-dev

(base) PS C:\> conda env list
# conda environments:
#
base                     C:\programs\mambaforge
mpl-dev                  C:\programs\mambaforge\envs\mpl-dev
mpl-dev                  c:\Programs\mambaforge\envs\mpl-dev
```

**change to `mpl-dev` and list again:**
```
(base) PS C:\> conda activate -n mpl-dev
(mpl-dev) PS C:\> mamba env list
# conda environments:
#
base                     C:\Programs\mambaforge
mpl-dev                  C:\Programs\mambaforge\envs\mpl-dev
                         C:\programs\mambaforge
mpl-dev                  c:\Programs\mambaforge\envs\mpl-dev

(mpl-dev) PS C:\> conda env list
# conda environments:
#
base                     C:\programs\mambaforge
mpl-dev               *  C:\programs\mambaforge\envs\mpl-dev
mpl-dev                  c:\Programs\mambaforge\envs\mpl-dev
```

**change back to `base` and list again**  (should be the same as the first output, shouldn't it):
```
(mpl-dev) PS C:\> conda activate base
WARNING: overwriting environment variables set in the machine
overwriting variable MAMBA_NO_BANNER
(base) PS C:\> mamba env list
# conda environments:
#
base                     C:\Programs\mambaforge
mpl-dev                  C:\Programs\mambaforge\envs\mpl-dev
                      *  C:\programs\mambaforge
mpl-dev                  c:\Programs\mambaforge\envs\mpl-dev

(base) PS C:\> conda env list
# conda environments:
#
base                  *  C:\programs\mambaforge
mpl-dev                  C:\programs\mambaforge\envs\mpl-dev
mpl-dev                  c:\Programs\mambaforge\envs\mpl-dev
```

`mamba info` output:
```
     active environment : base
    active env location : C:\programs\mambaforge
            shell level : 3
       user config file : C:\Users\srehberg\.condarc
 populated config files : C:\Programs\mambaforge\.condarc
                          C:\Users\srehberg\.condarc
                          C:\programs\mambaforge\.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Programs\mambaforge  (writable)
      conda av data dir : C:\Programs\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Programs\mambaforge\pkgs
                          C:\Users\srehberg\.conda\pkgs
                          C:\Users\srehberg\AppData\Local\conda\conda\pkgs
       envs directories : C:\Programs\mambaforge\envs
                          C:\Users\srehberg\.conda\envs
                          C:\Users\srehberg\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.14.0 requests/2.28.1 PyPy/3.9.12 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False

```

output of `dir C:\Programs\mambaforge\envs\`:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        20.09.2022     15:23                mpl-dev
-a----        20.09.2022     14:34              0 .conda_envs_dir_test
```

output of `type C:\Users\srehberg\.conda\environments.txt`:
```
C:\programs\mambaforge
c:\Programs\mambaforge\envs\mpl-dev
```
I tried to understand what's going on by running `python -m pdb c:\programs\mambaforge\Lib\site-packages\mamba\mamba.py env list` but it raised an error:
```
Traceback (most recent call last):
  File "c:\programs\mambaforge\Lib\site-packages\mamba\mamba.py", line 50, in <module>
    import mamba
  File "c:\programs\mambaforge\Lib\site-packages\mamba\mamba.py", line 51, in <module>
    from mamba import repoquery as repoquery_api
ImportError: cannot import name 'repoquery' from partially initialized module 'mamba' (most likely due to a circular import) (c:\programs\mambaforge\Lib\site-packages\mamba\mamba.py)
```
I guess I'll have to install `mamba` from source to be able to do this, right?

**Comment by jjerphan** [comment]
We cannot reproduce this issue with 2.0, please update to 2.0.

Feel free to reopen an issue with a reproduce if you still have this issue with 2.0.

Note that 1.x is note being developed anymore, but to address security fixes.
