### ISSUE TITLE
mamba suddenly throws: argument -l/--locks: conflicting option string: -l

### ISSUE THREAD

**Issue by dariober** [mamba-org/mamba#2013]
My `mamba` installation is suddenly broken. Just executing `mamba` or `mamba -h`, throws:

```
mamba 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/dario/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/home/dario/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "/home/dario/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 930, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/dario/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 877, in _wrapped_main
        configure_clean_locks(p._subparsers._group_actions[0])
      File "/home/dario/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 779, in configure_clean_locks
        help="Remove lock files.",
      File "/home/dario/miniconda3/lib/python3.7/argparse.py", line 1373, in add_argument
        return self._add_action(action)
      File "/home/dario/miniconda3/lib/python3.7/argparse.py", line 1577, in _add_action
        action = super(_ArgumentGroup, self)._add_action(action)
      File "/home/dario/miniconda3/lib/python3.7/argparse.py", line 1387, in _add_action
        self._check_conflict(action)
      File "/home/dario/miniconda3/lib/python3.7/argparse.py", line 1526, in _check_conflict
        conflict_handler(action, confl_optionals)
      File "/home/dario/miniconda3/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
        raise ArgumentError(action, message % conflict_string)
    argparse.ArgumentError: argument -l/--locks: conflicting option string: -l

`$ /home/dario/miniconda3/condabin/mamba`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/dario/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/home/dario/miniconda3/bin/python
               CONDA_ROOT=/home/dario/miniconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/dario/miniconda3/condabin:/opt/gradle/gradle-5.2/bin:/home/dario
                          /.local/share/umake/bin:/home/dario/.local/bin:/home/dario/bin:/opt/gr
                          adle/gradle-5.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:
                          /sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-10-
                          oracle/bin:/usr/lib/jvm/java-10-oracle/db/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : None
            shell level : 0
       user config file : /home/dario/.condarc
 populated config files : 
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/dario/miniconda3  (writable)
      conda av data dir : /home/dario/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dario/miniconda3/pkgs
                          /home/dario/.conda/pkgs
       envs directories : /home/dario/miniconda3/envs
                          /home/dario/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.25.0 CPython/3.7.6 Linux/4.15.0-139-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

The only change I recently made was to upgrade conda to the latest 22.9.0. Any idea what's going on here? Also, I cannot  upgrade mamba with:

```
conda install mamba -n base -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
```

**Comment by wolfv** [comment]
Do you know what version of `mamba` you have installed?

**Comment by dariober** [comment]
@wolfv  thanks for getting in touch so quickly. I think I got 0.23.0:

```
cat /home/dario/miniconda3/lib/python3.7/site-packages/mamba/_version.py 
version_info = (0, 23, 0)
__version__ = ".".join(map(str, version_info))
```

**Comment by dariober** [comment]
@wolfv ok I'll figure out a way to upgrade it. So, is this an incompatibility between conda 22.9.0 and mamba 0.23? Everything worked fine before upgrading conda, although I cannot be sure that I haven't tweaked something else (I don't think so though...).

**Comment by dariober** [comment]
I ended up renaming the miniconda base directory (to `~/miniconda3.tmp`) and I reinstalled miniconda and mamba from scratch. Then I copied the old environments to the new installation base path (`~/miniconda3/envs/`). If those envs got broken in the process is not a big deal anyway. Now I have the latest conda and mamba and everything looks good.
