### ISSUE TITLE
mamba RuntimeError: Operation not permitted

### ISSUE THREAD

**Issue by anfab** [mamba-org/mamba#2027]
I’m trying to build a new docker image using jupyterhub/singleuser:3.0.0 as base image. This is the Dockerfile:

```
FROM jupyterhub/singleuser:3.0.0
RUN mamba install --quiet --yes \
    'tensorflow' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
```

However I’m facing the following errors:

```
Step 2/12 : RUN mamba install --quiet --yes     'tensorflow' &&     mamba clean --all -f -y &&     fix-permissions "${CONDA_DIR}" &&     fix-permissions "/home/${NB_USER}"
 ---> Running in a3bc1398de47
Operation not permitted

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 886, in _wrapped_main
        result = do_call(args, p)
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 750, in do_call
        exit_code = install(args, parser, "install")
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 258, in install
        init_api_context(use_mamba_experimental)
      File "/opt/conda/lib/python3.10/site-packages/mamba/utils.py", line 197, in init_api_context
        api_ctx = api.Context()
    RuntimeError: Operation not permitted
```
Any idea on how to fix this?

Thanks!

**Comment by jan-perl** [comment]
ran into similar problem.
I have an older Ubuntu computer with an older docker version.
Workaround for me: select older jupyterhub version, in my case: jupyter/r-notebook:ubuntu-18.04

**Comment by djuarezg** [comment]
Downgrading jupyterhub is not an option for me, is there any other workaround or permanent solution?

**Comment by anfab** [comment]
If I remember well, I managed to fix the issue by upgrading docker.

**Comment by djuarezg** [comment]
Then FML, because I have a local Ubuntu machine able to build it with a version `Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3` but I am unable to build it in a GitLab runner with neither Docker nor K8s executor, with any of the `docker` official images...
