### ISSUE TITLE
Uncaught error when channel times out - handle error properly and don't bubble conda stack trace

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#2107]
When there's a channel loading timeout, e.g. due to interrupted internet connection, mamba currently fails in an ungraceful way.

This is related to the similarly unhandled failure when a channel is mistyped in https://github.com/mamba-org/mamba/issues/2031

I don't see a reason why so much debug information and stack trace should be thrown at the mamba user when the error _is_ known after all and could be handled in such a way that it's immediately clear to the user what the issue is.

This is what I currently get when there's a time out:

```txt
$ mamba install poetry                                    

Looking for: ['poetry']

conda-forge/osx-arm64                               ??.?MB @  ??.?MB/s 0 failed  9.0s
Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/noarch/repodata.json]
SSL connection timeout

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 750, in do_call
        exit_code = install(args, parser, "install")
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/utils.py", line 129, in load_channels
        index = get_index(
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/utils.py", line 110, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/noarch/repodata.json]
    SSL connection timeout

`$ /opt/homebrew/Caskroom/miniforge/base/bin/mamba install poetry`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=general
                CONDA_EXE=/opt/homebrew/Caskroom/miniforge/base/bin/conda
             CONDA_PREFIX=/opt/homebrew/Caskroom/miniforge/base/envs/general
           CONDA_PREFIX_1=/opt/homebrew/Caskroom/miniforge/base/envs/py11
           CONDA_PREFIX_2=/opt/homebrew/Caskroom/miniforge/base/envs/py11-64
           CONDA_PREFIX_3=/opt/homebrew/Caskroom/miniforge/base/envs/general
           CONDA_PREFIX_4=/opt/homebrew/Caskroom/miniforge/base/envs/py11
    CONDA_PROMPT_MODIFIER=
   CONDA_PYTHONBREAKPOINT=
         CONDA_PYTHON_EXE=/opt/homebrew/Caskroom/miniforge/base/bin/python
               CONDA_ROOT=/opt/homebrew/Caskroom/miniforge/base
              CONDA_SHLVL=5
           CURL_CA_BUNDLE=<not set>
         GDAL_DRIVER_PATH=/opt/homebrew/Caskroom/miniforge/base/envs/general/lib/gdalplugins
                 INFOPATH=/opt/homebrew/share/info:
                  MANPATH=/Users/corneliusromer/.nvm/versions/node/v18.9.0/share/man:/opt/homebr
                          ew/share/man:::/Users/corneliusromer/.antidote/man
                     PATH=/opt/homebrew/Caskroom/miniforge/base/envs/general/bin:/opt/homebrew/C
                          askroom/miniforge/base/condabin:/Users/corneliusromer/.nvm/versions/no
                          de/v18.9.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/Sy
                          stem/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Appl
                          e/usr/bin:/Users/corneliusromer/.cargo/bin:/opt/homebrew/opt/fzf/bin
         PYTHONBREAKPOINT=ipdb.set_trace
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : general
    active env location : /opt/homebrew/Caskroom/miniforge/base/envs/general
            shell level : 5
       user config file : /Users/corneliusromer/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
                          /Users/corneliusromer/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __osx=13.0.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/corneliusromer/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/corneliusromer/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.10.6 Darwin/22.1.0 OSX/13.0.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

The following is my suggestion - much leaner and less noisy:

```txt
$ mamba install poetry                                    

Looking for: ['poetry']

conda-forge/osx-arm64                               ??.?MB @  ??.?MB/s 0 failed  9.0s
Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/noarch/repodata.json]
SSL connection timeout
```

cc @jonashaag

**Comment by jjerphan** [comment]
This has been improved in 2.0, with an explicit shorted messaged being raised.
