### ISSUE TITLE
broken dependency to libiconv.2.dylib on Mac M1

### ISSUE THREAD

**Issue by mrdrprofuroboros** [mamba-org/mamba#2119]
I am working on a MacBook Pro 2020 with M1 and Monterey (12.4)
Have a fresh install of miniforge anaconda and trying to install mamba with
`conda install mamba -n base -c conda-forge`

it installs successfully but crashes in runtime with
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: dlopen(/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Symbol not found: _libiconv
  Referenced from: /usr/local/Caskroom/miniforge/base/lib/libarchive.13.dylib
  Expected in: /usr/lib/libiconv.2.dylib
```

inspecting deps:
```
otool -L /usr/local/Caskroom/miniforge/base/lib/libarchive.13.dylib
/usr/local/Caskroom/miniforge/base/lib/libarchive.13.dylib:
	@rpath/libarchive.13.dylib (compatibility version 19.0.0, current version 19.2.0)
	@rpath/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	@rpath/liblzo2.2.dylib (compatibility version 2.0.0, current version 2.0.0)
	@rpath/liblzma.5.dylib (compatibility version 8.0.0, current version 8.5.0)
	@rpath/libzstd.1.dylib (compatibility version 1.0.0, current version 1.5.2)
	@rpath/liblz4.1.dylib (compatibility version 1.0.0, current version 1.9.3)
	@rpath/libbz2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.12)
	@rpath/libxml2.2.dylib (compatibility version 12.0.0, current version 12.14.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

I do have a correct libiconv installed from MacPorts in /opt/local/lib/
```
nm /opt/local/lib/libiconv.2.dylib | grep _libiconv
0000000000108020 D __libiconv_version
0000000000005346 T _libiconv
0000000000005368 T _libiconv_close
0000000000003e02 T _libiconv_open
0000000000005375 T _libiconv_open_into
000000000001a743 t _libiconv_relocate
000000000001a817 t _libiconv_relocate2
000000000001a684 T _libiconv_set_relocation_prefix
00000000000057b2 T _libiconvctl
00000000000058b4 T _libiconvlist
```

and no libiconv in /usr/lib
```
ls /usr/lib
charset.alias                libgmalloc.dylib             ruby
cron                         libhunspell-1.2.0.dylib      sasl2
dsc_extractor.bundle         libiodbc.2.dylib             sqlite3
dtrace                       libiodbcinst.2.dylib         ssh-keychain.dylib
dyld                         libobjc-trampolines.dylib    swift
groff                        libstdc++.6.dylib            system
libLeaksAtExit.dylib         log                          updaters
libMTLCapture.dylib          pam                          xpc
libMTLToolsDiagnostics.dylib pkgconfig                    zsh
libffi-trampolines.dylib     rpcsvc
```

any ideas how to fix it?

**Comment by mrdrprofuroboros** [comment]
seems to be fixed by prepending /opt/local/lib to DYLD_LIBRARY_PATH (I was appending it and it did not work)
`echo "export DYLD_LIBRARY_PATH=/opt/local/lib:$DYLD_LIBRARY_PATH" >> ~/.zshrc`

**Comment by wolfv** [comment]
Hmm, this is pretty weird. Usually the `libiconv` and all other libraries should come from conda-forge and work out of the box (without having to fiddle with the `DYLD_LIBRARY_PATH` and other variables).

**Comment by mrdrprofuroboros** [comment]
It works with an empty DYLD_LIBRARY_PATH (default)
But I was appending a couple of custom directories to it for my CMake projects
`export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/my/custom/dir`

it turned out that it was appending to an empty string resulting in just `:/my/custom/dir`
new dynamic libraries paths after Big Sur is a mystery ☹️

**Comment by wolfv** [comment]
For cmake you should be able to use CMAKE_INSTALL_PREFIX and CMAKE_PREFIX_PATH. Hacking around with the environment variable seems less ideal.
