### ISSUE TITLE
Unable to install PICRUSt2 on MackBook M1 with Monterey

### ISSUE THREAD

**Issue by borexino** [mamba-org/mamba#2120]
I ran this:

`micromamba create -n picrust2 -c bioconda -c conda-forge picrust2=2.5.1`

I had this:

```


                                           ___
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

warning  libmamba 'root_prefix' set with default value: /Users/xxx/micromamba
bioconda/osx-arm64                                            No change
bioconda/noarch                                      4.1MB @   1.9MB/s  2.3s
conda-forge/noarch                                  10.2MB @   3.0MB/s  3.7s
conda-forge/osx-arm64                                4.2MB @   1.1MB/s  3.8s
Encountered problems while solving:
  - nothing provides biom-format >=2.1.10 needed by picrust2-2.5.1-pyhdfd78af_0

The environment can't be solved, aborting the operation
error    libmamba Could not solve for environment specs
critical libmamba UnsatisfiableError_
```
OR:

`mamba create -n picrust2 -c bioconda -c conda-forge picrust2=2.5.1
`

Gives:

```
                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.0.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['picrust2=2.5.1']

pkgs/main/osx-arm64                                           No change
bioconda/osx-arm64                                            No change
bioconda/noarch                                               No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/r/osx-arm64                                              No change
conda-forge/osx-arm64                                4.2MB @   2.3MB/s  1.9s
conda-forge/noarch                                  10.2MB @   3.4MB/s  3.3s
Encountered problems while solving:
  - nothing provides biom-format >=2.1.10 needed by picrust2-2.5.1-pyhdfd78af_0
```

Here the issue:

```
conda init zsh

Password:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/cli/main_init.py", line 50, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/core/initialize.py", line 119, in initialize
        run_plan_elevated(plan2)
      File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/core/initialize.py", line 688, in run_plan_elevated
        result = subprocess_call(
      File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/gateways/subprocess.py", line 100, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
      File "/opt/homebrew/anaconda3/lib/python3.9/subprocess.py", line 1134, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/opt/homebrew/anaconda3/lib/python3.9/subprocess.py", line 1959, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'

`$ /opt/homebrew/anaconda3/bin/conda init zsh`

```

Can I solve somehow?

**Comment by wholtz** [comment]
Hi @borexino - you are in need of a osx-arm64 build of biom-format, but that does not exist on the [conda channels you are searching](https://anaconda.org/search?q=biom-format).

**Comment by jjerphan** [comment]
```
micromamba create -n picrust2 -c conda-forge -c bioconda picrust2=2.5.1
```

makes it installable.

For background reading, I recommend [this section of conda's documentation on managing channels](https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-channels.html), especially [the subsection on strict channel priority](https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-channels.html#strict-channel-priority).
