### ISSUE TITLE
Unable to install Spyder

### ISSUE THREAD

**Issue by Nathan-Thomas-Han** [mamba-org/mamba#2124]
Hi everyone,

I've been trying to install Spyder via Miniforge (following the instructions on the Spyder installation page). Unfortunately, when I try to do so, I get this error message:

```
(base) C:\Users\natha>mamba create -c mamba-forge -n spyder-env spyder numpy scipy pandas matplotlib sympy seaborn
Looking for: ['spyder', 'numpy', 'scipy', 'pandas', 'matplotlib', 'sympy', 'seaborn']

mamba-forge/win-64                                   3.1kB @   1.1kB/s 404 failed  2.9s
mamba-forge/noarch                                   3.1kB @ 860.0 B/s 404 failed  3.6s
Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/mamba-forge/noarch/repodata.json] 3086 bytes

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\natha\mambaforge\lib\site-packages\conda\exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "C:\Users\natha\mambaforge\lib\site-packages\mamba\mamba.py", line 935, in exception_converter
        raise e
      File "C:\Users\natha\mambaforge\lib\site-packages\mamba\mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Users\natha\mambaforge\lib\site-packages\mamba\mamba.py", line 886, in _wrapped_main
        result = do_call(parsed_args, p)
      File "C:\Users\natha\mambaforge\lib\site-packages\mamba\mamba.py", line 754, in do_call
        exit_code = create(args, parser)
      File "C:\Users\natha\mambaforge\lib\site-packages\mamba\mamba.py", line 630, in create
        return install(args, parser, "create")
      File "C:\Users\natha\mambaforge\lib\site-packages\mamba\mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
      File "C:\Users\natha\mambaforge\lib\site-packages\mamba\utils.py", line 129, in load_channels
        index = get_index(
      File "C:\Users\natha\mambaforge\lib\site-packages\mamba\utils.py", line 110, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/mamba-forge/noarch/repodata.json] 3086 bytes

`$ C:\Users\natha\mambaforge\Scripts\mamba create -c mamba-forge -n spyder-env spyder numpy scipy pandas matplotlib sympy seaborn`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\natha\mambaforge\condabin\..\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\natha\mambaforge
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\natha\mambaforge\python.exe
               CONDA_ROOT=C:\Users\natha\mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\natha
                     PATH=C:\Users\natha\mambaforge;C:\Users\natha\mambaforge\Library\mingw-
                          w64\bin;C:\Users\natha\mambaforge\Library\usr\bin;C:\Users\natha\mamba
                          forge\Library\bin;C:\Users\natha\mambaforge\Scripts;C:\Users\natha\mam
                          baforge\bin;C:\Users\natha\mambaforge\condabin;C:\Windows\system32;C:\
                          Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell
                          \v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\MATLAB\R2022b\bin;C
                          :\Users\natha\AppData\Local\Microsoft\WindowsApps;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\natha\mambaforge
            shell level : 1
       user config file : C:\Users\natha\.condarc
 populated config files : C:\Users\natha\mambaforge\.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\natha\mambaforge  (writable)
      conda av data dir : C:\Users\natha\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/mamba-forge/win-64
                          https://conda.anaconda.org/mamba-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\natha\mambaforge\pkgs
                          C:\Users\natha\.conda\pkgs
                          C:\Users\natha\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\natha\mambaforge\envs
                          C:\Users\natha\.conda\envs
                          C:\Users\natha\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.10.6 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

Can anyone help with this?

Kind regards,
Nathan

**Comment by jonashaag** [comment]
Channel name is conda-forge :) not mamba-forge

**Comment by Nathan-Thomas-Han** [comment]
Ah, you're right, what a silly mistake. That indeed did the trick. However, when I tried to open Spyder after activating the environment, I get this error. I've attached the error here but since it's a separate issue, should I open a separate thread? 

```
(base) C:\Users\natha>mamba activate spyder-env

(spyder-env) C:\Users\natha>spyder
fromIccProfile: failed minimal tag size sanity
Bad address (D:\bld\zeromq_1629967000004\work\src\epoll.cpp:100)
Traceback (most recent call last):
  File "C:\Users\natha\mambaforge\envs\spyder-env\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000002A47EBE8780> still has pending operation at deallocation, the process may crash
Bad address (D:\bld\zeromq_1629967000004\work\src\epoll.cpp:100)
```
Kind regards,
Nathan

**Comment by Nathan-Thomas-Han** [comment]
The issue was from my use of a VPN. It works fine after I've resetted winsock. Thanks Jonas!
