### ISSUE TITLE
Mamba couldn't resolve host name

### ISSUE THREAD

**Issue by GaganBhat** [mamba-org/mamba#2134]
Hi all,

Command executed was `mamba create -n robostackenv ros-noetic-desktop python=3.9 -c robostack -c robostack-experimental -c conda-forge --no-channel-priority --override-channels`

OS -- MacOS 12.6
CPU -- M1 Max

Error Report:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/gaganb/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/Users/gaganb/opt/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 882, in exception_converter
        raise e
      File "/Users/gaganb/opt/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/gaganb/opt/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "/Users/gaganb/opt/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 720, in do_call
        exit_code = create(args, parser)
      File "/Users/gaganb/opt/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 624, in create
        return install(args, parser, "create")
      File "/Users/gaganb/opt/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 572, in install
        downloaded = transaction.prompt(
    RuntimeError: Download error (6) Couldn't resolve host name [https://conda.anaconda.org/conda-forge/osx-64/aom-3.5.0-hf0c8a7f_0.tar.bz2]

`$ /Users/gaganb/opt/anaconda3/bin/mamba create -n robostackenv ros-noetic-desktop python=3.9 -c robostack -c robostack-experimental -c conda-forge --no-channel-priority --override-channels`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/gaganb/opt/anaconda3/bin/conda
             CONDA_PREFIX=/Users/gaganb/opt/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/gaganb/opt/anaconda3/bin/python
               CONDA_ROOT=/Users/gaganb/opt/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
                  MANPATH=/Users/gaganb/.nvm/versions/node/v14.20.0/share/man:/opt/homebrew/shar
                          e/man::
                     PATH=/Users/gaganb/.sdkman/candidates/java/current/bin:/Users/gaganb/opt/an
                          aconda3/bin:/Users/gaganb/opt/anaconda3/condabin:/Users/gaganb/.nvm/ve
                          rsions/node/v14.20.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/loc
                          al/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local
                          /munki
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/gaganb/opt/anaconda3
            shell level : 1
       user config file : /Users/gaganb/.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/gaganb/opt/anaconda3  (writable)
      conda av data dir : /Users/gaganb/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/robostack/osx-64
                          https://conda.anaconda.org/robostack/noarch
                          https://conda.anaconda.org/robostack-experimental/osx-64
                          https://conda.anaconda.org/robostack-experimental/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/gaganb/opt/anaconda3/pkgs
                          /Users/gaganb/.conda/pkgs
       envs directories : /Users/gaganb/opt/anaconda3/envs
                          /Users/gaganb/.conda/envs
               platform : osx-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Darwin/21.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

I am able to access and download https://conda.anaconda.org/conda-forge/osx-64/aom-3.5.0-hf0c8a7f_0.tar.bz2 through google chrome as well as curl. It isn't a networking issue.

Any ideas what it could be?

**Comment by GaganBhat** [comment]
Here is the full log with `-v` verbose logging enabled.

[mamba_verbose_error_logs.txt](https://github.com/mamba-org/mamba/files/10071538/mamba_verbose_error_logs.txt)

**Comment by wolfv** [comment]
Hi @GaganBhat Hmm, that's puzzling. Usually, if `curl` works, `mamba` should work as well. 

I can see that you are starting from a `anaconda3` environment? It's strongly recommended not to mix `defaults` and `conda-forge`. It's much easier to start with `mambaforge` (https://github.com/conda-forge/miniforge

**Comment by GaganBhat** [comment]
I see similar issues before #980 and #1089. 

Let me try mambaforge, but unsure if that will fix the issue.

**Comment by GaganBhat** [comment]
Starting with mambaforge through the installer you linked worked. No longer hit the host name resolution error.

Closing the issue. Thanks!
