### ISSUE TITLE
micromamba proposes to remove a conflicting package instead of giving unsolvable error

### ISSUE THREAD

**Issue by jorisvandenbossche** [mamba-org/mamba#2166]
While testing out micromamba (in comparison to mamba), I noticed that micromamba would propose to remove an already installed package if that was needed to install another package, instead of giving the error message about the environment not being solvable.

The case I tried (related to https://github.com/mamba-org/mamba/issues/2078#issuecomment-1350579586), was to first install qgis (`micromamba create -n test-qgis qgis`), and then try to install `libgdal-arrow-parquet`:

```
$ micromamba install libgdal-arrow-parquet
...
Pinned packages:
  - python 3.11.*


Transaction

  Prefix: /home/joris/micromamba/envs/test-qgis

  Updating specs:

   - libgdal-arrow-parquet


  Package                     Version  Build               Channel                    Size
────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────

 ...

  Remove:
────────────────────────────────────────────────────────────────────────────────────────────

  - psycopg2                    2.9.3  py311hd4cff14_1     conda-forge              Cached
  - qgis                       3.28.1  py311h7bb8ebf_2     conda-forge              Cached

  Change:
────────────────────────────────────────────────────────────────────────────────────────────

...

  Upgrade:
────────────────────────────────────────────────────────────────────────────────────────────

 ...

```

So has to install some new package and change build / upgrade some existing packages (that all looks OK), but it also simply removed `qgis`, while I explicitly installed this just before.

Sequence of commands that I used:
```
micromamba create -n test-qgis
micromamba activate test-qgis
micromamba install qgis
micromamba install libgdal-arrow-parquet
```

It's also a bit strange that it shows "Pinned packages: - python 3.11.*", while the only package installed explicitly before was `qgis`

When doing `mamba install libgdal-arrow-parquet` instead (using mamba instead of micromamba), it will say it cannot solve the environment.

Is this different behaviour intentional?

**Comment by ifrh** [comment]
Any updates on this?

In a CD/CI-Environment I just found, that micromamba has removed Python and Pip from micromambas activated environment... 

Could it be possible to create a "removal" safeguard around `python` and `pip`?
At least both should not be removed without a recreation in same `micromamba` call... 

```
Parsing Packages' Records                                                                 ✔ Done (0.8 sec)
critical libmamba failed to run python command :
      error: No such file or directory
      command ran:  -q -m pip inspect --local
      env options:("PYTHONIOENCODING", "utf-8") ("NO_COLOR", "1") ("PIP_NO_COLOR", "1")
    -> output:

    -> error output:
```

By the way is that somehow related with the "inspect"-bug?  
- https://github.com/mamba-org/mamba/issues/4075

If you create a micromamba venv for very old Python versions:
- Python 2.7: Python has no `-q` so `micromamba update` prints `Unknown option: -q`   
- Python 3.4: for whatever reason a Pip version was installed by Micromamba which needs at least Python 3.5. Only if you specify the needed Pip version while creating the environment,  a suitable pip persion for python 3.4 gets installed. I got some Pip in version 9.0, with that `micromamba update` prints `ERROR: unknown command "inspect"`  
- Python 3.5, Pip 20.3.4: `micromamba update` prints `ERROR: unknown command "inspect"`
- Python 3.6, Pip 21.3.1: `micromamba update` prints `ERROR: unknown command "inspect"`
- Python 3.7, Pip 22.3.1: `micromamba update` prints `WARNING: pip inspect is currently an experimental command. The output format may change in a future release without prior warning.`

Just as an idea ... perhaps the analysing of installed packages are somehow broken,
at least the command for listing the environment content is (currently) useless - independent of Python or Pip versions .

The following is the output for an dockerised micromamba environment using Python 3.13 and Pip 26.1.1:

```
(d52py313) user@7d776fbb87ed:~$ micromamba list env
List of packages in environment: "/home/user/micromamba/envs/d52py313"

(d52py313) user@7d776fbb87ed:~$
```

--
Edit: add link to other possible related bug report.

**Comment by ifrh** [comment]
micromamba version : 2.6.2

```
(d52py313) user@cd4c86aaf95f:~$ python -c "import cffi"
```
```
(d52py313) user@cd4c86aaf95f:~$ python -c "import ldap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import ldap
  File "/home/user/micromamba/envs/d52py313/lib/python3.13/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: /usr/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
```
```
(d52py313) user@cd4c86aaf95f:~$ pip freeze | grep ldap
python-ldap==3.4.7
(d52py313) user@cd4c86aaf95f:~$
```
```
(d52py313) user@f340759bba63:~$ micromamba install -y libffi"<=3.4" --allow-downgrade
⚠ Shard Index for nodefaults/linux-64 not available, falling back to flat repodata
Using Flat Repodata for nodefaults/linux-64                                               ✔ Done (0.0 sec)
⚠ Shard Index for nodefaults/noarch not available, falling back to flat repodata
Using Flat Repodata for nodefaults/noarch                                                 ✔ Done (0.0 sec)
Using Cached Shard Index for conda-forge/linux-64                                                   ✔ Done
Using Cached Shard Index for conda-forge/noarch                                                     ✔ Done
Fetching and Parsing Packages' Shards                                                     ✔ Done (0.1 sec)
Using Cached Shard Index for conda-forge/linux-64                                                   ✔ Done
Using Cached Shard Index for conda-forge/noarch                                                     ✔ Done
Fetching and Parsing Packages' Shards                                                     ✔ Done (0.1 sec)
Parsing Packages' Records                                                                 ✔ Done (0.3 sec)

Pinned packages:

  - python=3.13

Resolving Environment                                                                     ✔ Done (0.3 sec)

Transaction

  Prefix: /home/user/micromamba/envs/d52py313

  Updating specs:

   - libffi<=3.4


  Package         Version  Build               Channel           Size
───────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────

  + libstdcxx-ng   15.2.0  hdf11a46_19         conda-forge       28kB

  Remove:
───────────────────────────────────────────────────────────────────────

  - pip            26.1.2  pyh145f28c_0        conda-forge     Cached
  - python        3.13.11  hcf712cf_100_cp313  anaconda        Cached

  Change:
───────────────────────────────────────────────────────────────────────

  - libgcc         15.2.0  h69a1729_8          anaconda        Cached
  + libgcc         15.2.0  he0feb66_19         conda-forge        1MB
  - libgcc-ng      15.2.0  h166f726_8          anaconda        Cached
  + libgcc-ng      15.2.0  h69a702a_19         conda-forge       28kB
  - libstdcxx      15.2.0  h39759b7_8          anaconda        Cached
  + libstdcxx      15.2.0  h934c35e_19         conda-forge        6MB

  Downgrade:
───────────────────────────────────────────────────────────────────────

  - libffi          3.5.2  h3435931_0          conda-forge     Cached
  + libffi            3.3  h58526e2_2          conda-forge       53kB

  Summary:

  Install: 1 packages
  Remove: 2 packages
  Change: 3 packages
  Downgrade: 1 packages

  Total download: 7MB

───────────────────────────────────────────────────────────────────────



Transaction starting
libstdcxx-ng                                        27.8kB @ 120.3kB/s  0.1s
libgcc-ng                                           27.7kB @  ??.?MB/s  0.1s
libffi                                              52.6kB @  ??.?MB/s  0.1s
libgcc                                               1.0MB @   2.9MB/s  0.3s
libstdcxx                                            5.9MB @   6.4MB/s  0.8s
Unlinking libgcc-15.2.0-h69a1729_8
Unlinking python-3.13.11-hcf712cf_100_cp313
Unlinking libstdcxx-15.2.0-h39759b7_8
Unlinking libgcc-ng-15.2.0-h166f726_8
Unlinking libffi-3.5.2-h3435931_0
Linking libgcc-15.2.0-he0feb66_19
Linking libstdcxx-15.2.0-h934c35e_19
Linking libgcc-ng-15.2.0-h69a702a_19
Linking libstdcxx-ng-15.2.0-hdf11a46_19
Linking libffi-3.3-h58526e2_2

Transaction finished

(d52py313) user@f340759bba63:~$
```
Why Python and Pip gets removed ? ... mhm ....
