### ISSUE TITLE
Error when creating multiple environments at the same time with the same package cache

### ISSUE THREAD

**Issue by williamAlhant** [mamba-org/mamba#2279]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

To reproduce the issue, first the package cache/directory must be empty.
Then, when 2 environment creation commands are invoked in parallel, some errors occur.
Something like the following script can be used to reproduce the issue
```
from subprocess import Popen

def run_mamba_create(i) -> Popen:
    stdout_log_file = open(f'./logs/ps_{i}.stdout.log', 'w')
    stderr_log_file = open(f'./logs/ps_{i}.stderr.log', 'w')
    return Popen(
        ['mamba', 'create', '-y', '-q', '--prefix', f'envs/foo_{i}', '-c', 'conda-forge', 'gcc=11.3'],
        stdout=stdout_log_file,
        stderr=stderr_log_file,
    )

mamba_ps_1 = run_mamba_create(1)
mamba_ps_2 = run_mamba_create(2)

mamba_ps_1.wait()
mamba_ps_2.wait()

```

One process has the following stderr
```
Could not read JSON repodata file (/home/cookie/code/mamba_experiments/pkgs/cache/497deca9.json) repository does not start with an object

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/cookie/code/mamba_experiments/conda_base/lib/python3.11/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/cookie/code/mamba_experiments/conda_base/lib/python3.11/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "/home/cookie/code/mamba_experiments/conda_base/lib/python3.11/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/cookie/code/mamba_experiments/conda_base/lib/python3.11/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(parsed_args, p)
                 ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/cookie/code/mamba_experiments/conda_base/lib/python3.11/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = create(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^
      File "/home/cookie/code/mamba_experiments/conda_base/lib/python3.11/site-packages/mamba/mamba.py", line 630, in create
        return install(args, parser, "create")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/cookie/code/mamba_experiments/conda_base/lib/python3.11/site-packages/mamba/mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/cookie/code/mamba_experiments/conda_base/lib/python3.11/site-packages/mamba/utils.py", line 178, in load_channels
        repo = subdir.create_repo(pool)
               ^^^^^^^^^^^^^^^^^^^^^^^^
    RuntimeError: Could not read JSON repodata file (/home/cookie/code/mamba_experiments/pkgs/cache/497deca9.json) repository does not start with an object
```

### mamba info / micromamba info

```shell
active environment : base
    active env location : /home/cookie/code/mamba_experiments/conda_base
            shell level : 1
       user config file : /home/cookie/.condarc
 populated config files : 
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.11.0.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.36=0
                          __linux=6.1.8=0
                          __unix=0=0
       base environment : /home/cookie/code/mamba_experiments/conda_base  (writable)
      conda av data dir : /home/cookie/code/mamba_experiments/conda_base/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/cookie/code/mamba_experiments/pkgs
       envs directories : /home/cookie/code/mamba_experiments/envs
                          /home/cookie/code/mamba_experiments/conda_base/envs
                          /home/cookie/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.11.0 Linux/6.1.8-200.fc37.x86_64 fedora/37 glibc/2.36
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by jonashaag** [comment]
Would you mind trying this with Micromamba?

**Comment by williamAlhant** [comment]
I get the same error with micromamba, except there is no Python backtrace this time.
