### ISSUE TITLE
mamba install breaks when tilde (~) is present in requirements.txt file

### ISSUE THREAD

**Issue by ChillarAnand** [mamba-org/mamba#2322]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

tilde (~)

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Reproducible with Conda

### Describe your issue

Not able to install packages in requirements.txt file when tilde(~) operator is present.

```
$ cat requirements.txt
python-confluent-kafka~=1.9.0

 ⚡ root  /app  ✘  conda install --file requirements.txt

InvalidVersionSpec: Invalid version '~1.9.0': invalid operator

 ⚡ root  /app  ✘  mamba install --file requirements.txt

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.3.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Invalid version '~1.9.0': invalid operator

InvalidVersionSpec: Invalid version '~1.9.0': invalid operator
```

### mamba info / micromamba info

```shell
active environment : None
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=aarch64
                          __glibc=2.31=0
                          __linux=5.10.104=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-aarch64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Linux/5.10.104-linuxkit ubuntu/20.04.5 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Logs

```shell
⚡ root  /app  mamba install -v --file requirements.txt

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.3.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Invalid version '~1.9.0': invalid operator
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/conda/models/version.py", line 40, in __call__
    return cls._cache_[arg]
KeyError: '~1.9.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1118, in __call__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 936, in exception_converter
    raise e
  File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 929, in exception_converter
    exit_code = _wrapped_main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 887, in _wrapped_main
    result = do_call(parsed_args, p)
  File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 750, in do_call
    exit_code = install(args, parser, "install")
  File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 372, in install
    specs.extend(MatchSpec(s) for s in file_specs)
  File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 372, in <genexpr>
    specs.extend(MatchSpec(s) for s in file_specs)
  File "/opt/conda/lib/python3.10/site-packages/conda/models/match_spec.py", line 57, in __call__
    return super().__call__(**parsed)
  File "/opt/conda/lib/python3.10/site-packages/conda/models/match_spec.py", line 178, in __init__
    self._match_components = self._build_components(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda/models/match_spec.py", line 404, in _build_components
    return frozendict(_make_component(key, value) for key, value in kwargs.items())
  File "/opt/conda/lib/python3.10/site-packages/conda/_vendor/frozendict/__init__.py", line 21, in __init__
    self._dict = self.dict_cls(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda/models/match_spec.py", line 404, in <genexpr>
    return frozendict(_make_component(key, value) for key, value in kwargs.items())
  File "/opt/conda/lib/python3.10/site-packages/conda/models/match_spec.py", line 418, in _make_component
    matcher = _implementors[field_name](value)
  File "/opt/conda/lib/python3.10/site-packages/conda/models/version.py", line 42, in __call__
    val = cls._cache_[arg] = super().__call__(arg)
  File "/opt/conda/lib/python3.10/site-packages/conda/models/version.py", line 504, in __init__
    vspec_str, matcher, is_exact = self.get_matcher(vspec)
  File "/opt/conda/lib/python3.10/site-packages/conda/models/version.py", line 533, in get_matcher
    raise InvalidVersionSpec(vspec_str, "invalid operator")
conda.exceptions.InvalidVersionSpec: Invalid version '~1.9.0': invalid operator
```

### environment.yml

```yaml
Only requirements.txt file is used.
```

### ~/.condarc

```yaml
Not present.
```

**Comment by jonashaag** [comment]
Thanks for reporting this! If this is reproducible with Conda, please file a bug there instead.
