### ISSUE TITLE
Installing vtk library breaks mamba

### ISSUE THREAD

**Issue by mountaindust** [mamba-org/mamba#2338]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

See #1728

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not reproducible with Conda

### Describe your issue

# Summary of issue
Mamba stops working after installing the vtk package. This is reproducible from a clean install of Mambaforge.

## Steps to reproduce
1. Install Mambaforge.
2. (optional) update mamba.
3. Install the vtk package with `mamba install vtk`

## Result
Any attempt to run mamba will crash, resulting in the following traceback:
```
Traceback (most recent call last):
  File "C:\Users\<username>\mambaforge\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Users\<username>\mambaforge\lib\site-packages\mamba\mamba.py", line 49, in <module>
    import libmambapy as api
  File "C:\Users\<username>\mambaforge\lib\site-packages\libmambapy\__init__.py", line 7, in <module>
    raise e
  File "C:\Users\<username>\mambaforge\lib\site-packages\libmambapy\__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
```

## Additional info:
- OS: Windows10 (win64)
- Mambaforge 22.11.1-4 (64-bit)
- Seems related to #1728 
- If you try this with Miniforge 22.11.1-4 (64-bit), conda has no trouble with vtk. But installing mamba and then installing vtk will get you the same error.

**Comment by mountaindust** [comment]
Somehow, I managed just now to avoid the problem using a fresh install of Miniforge 22.11.1-4 and installing the following yml:
```
# Packages to install in Miniforge
#
# Name
bokeh
cython
google-api-python-client
google-auth-httplib2
google-auth-oauthlib
h5py
jupyter
mamba
markdown
matplotlib
netcdf4
networkx
numba
numpy-stl
numpydoc
pep8
plotly
pyflakes
pylint
pytables
pytest
pyvista
scikit-learn
scipy
seaborn
snakeviz
sympy
vtk
```
So... perhaps relevant version numbers can be compared between an install with only vtk and this install in order to help narrow down the problem.
