### ISSUE TITLE
Mambaforge installation error 

### ISSUE THREAD

**Issue by QuietQuarters** [mamba-org/mamba#2389]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

Installation error

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Didn't try

### Describe your issue

Tried to install mambaforge on Mac intel but returned with an error msg. Anyone please help with solutions. Thank you.

### Logs

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/administrator/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
      File "/Users/administrator/mambaforge/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/administrator/mambaforge/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/administrator/mambaforge/lib/python3.10/site-packages/conda/cli/main_init.py", line 38, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/Users/administrator/mambaforge/lib/python3.10/site-packages/conda/core/initialize.py", line 118, in initialize
        run_plan_elevated(plan2)
      File "/Users/administrator/mambaforge/lib/python3.10/site-packages/conda/core/initialize.py", line 714, in run_plan_elevated
        result = subprocess_call(
      File "/Users/administrator/mambaforge/lib/python3.10/site-packages/conda/gateways/subprocess.py", line 98, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
      File "/Users/administrator/mambaforge/lib/python3.10/subprocess.py", line 1154, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/Users/administrator/mambaforge/lib/python3.10/subprocess.py", line 1985, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'

`$ /Users/administrator/mambaforge/lib/python3.10/site-packages/conda/__main__.py init`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/anaconda3/bin/conda
             CONDA_PREFIX=/opt/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/anaconda3/bin/python
               CONDA_ROOT=/Users/administrator/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/opt/anaconda3/bin:/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bi
                          n:/usr/sbin:/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : /opt/anaconda3
    active env location : /opt/anaconda3
            shell level : 1
       user config file : /Users/administrator/.condarc
 populated config files : /Users/administrator/mambaforge/.condarc
                          /Users/administrator/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.13.6=0
                          __unix=0=0
       base environment : /Users/administrator/mambaforge  (writable)
      conda av data dir : /Users/administrator/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/administrator/mambaforge/pkgs
                          /Users/administrator/.conda/pkgs
       envs directories : /Users/administrator/mambaforge/envs
                          /Users/administrator/.conda/envs
               platform : osx-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by jonashaag** [comment]
I think it’s best if you report this in the Mambaforge repo.
