### ISSUE TITLE
Error installing snakemake via mamba

### ISSUE THREAD

**Issue by jonwhit** [mamba-org/mamba#2406]
Following fresh install of conda and mamba, mamba fails to install any package. Here is the following example and error report trying to install snakemake (same error with jupyter or any other package I've tried). 

```
mamba install -c conda-forge snakemake

Looking for: ['snakemake']

basic_string::replace: __pos (which is 18446744073709551615) > this->size() (which is 6)

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/jwhitney/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/jwhitney/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/jwhitney/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/jwhitney/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/jwhitney/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/home/jwhitney/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 499, in install
        index = load_channels(pool, channels, repos)
      File "/home/jwhitney/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 129, in load_channels
        index = get_index(
      File "/home/jwhitney/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 97, in get_index
        for channel in api.get_channels(all_channels):
    IndexError: basic_string::replace: __pos (which is 18446744073709551615) > this->size() (which is 6)

`$ /home/jwhitney/mambaforge/bin/mamba install -c conda-forge snakemake`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/jwhitney/mambaforge/bin/conda
         CONDA_PYTHON_EXE=/home/jwhitney/mambaforge/bin/python
               CONDA_ROOT=/home/jwhitney/mambaforge
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/lib64:/usr/lib:/home/jwhitney/bamtools/lib64:/home/jwhitney/lib:/
                          home/jwhitney/clustal/lib:/home/jwhitney/pcre/lib:/home/jwhitney/pcre2
                          /lib:/home/jwhitney/htslib/lib:
               LD_PRELOAD=<not set>
                  MANPATH=::/usr/man:/usr/share/man:/usr/local/share/man:/usr/local/man
               MODULEPATH=/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/
                          usr/share/modulefiles
                     PATH=/home/jwhitney/programs/dadasnake:/home/jwhitney/micromamba/bin:/home/
                          jwhitney/mambaforge/condabin:/home/jwhitney/bamtools/bin:/home/jwhitne
                          y/bamutil/bin:/home/jwhitney/bedtools/bin:/home/jwhitney/bowtie:/home/
                          jwhitney/bowtie2:/home/jwhitney/bwa:/home/jwhitney/bwa-
                          mem2:/home/jwhitney/cd-hit/bin:/home/jwhitney/clustal/bin:/home/jwhitn
                          ey/nextflow:/home/jwhitney/go/bin:/home/jwhitney/FastQC:/home/jwhitney
                          /pcre/bin:/home/jwhitney/pcre2/bin:/home/jwhitney/fastq-tools/bin:/hom
                          e/jwhitney/htslib/bin:/home/jwhitney/mothur:/home/jwhitney/mothur/blas
                          t/bin:/home/jwhitney/PGDSpider:/home/jwhitney/samtools/bin:/home/jwhit
                          ney/vcftools/bin:/home/jwhitney/.local/bin:/home/jwhitney/bin:/usr/sha
                          re/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/
                          X11R6/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /home/jwhitney/.condarc
 populated config files : /home/jwhitney/mambaforge/.condarc
                          /home/jwhitney/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /home/jwhitney/mambaforge  (writable)
      conda av data dir : /home/jwhitney/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/noarch/linux-64
          package cache : /home/jwhitney/mambaforge/pkgs
                          /home/jwhitney/.conda/pkgs
       envs directories : /home/jwhitney/mambaforge/envs
                          /home/jwhitney/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.9 Linux/4.18.0-425.13.1.el8_7.x86_64 rhel/8.7 glibc/2.28
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by jonashaag** [comment]
Your `noarch` channel is invalid, does removing it fix the issue?

Also please next time don't ignore the issue template.

**Comment by jonwhit** [comment]
Thank you so much for your response and advice. That did work, removing the noarch channel fixed the issue. Thank you again for your help. 

Apologies for missing the issue template, I'll make sure to adhere next time.

**Comment by jonashaag** [comment]
Actually we should fix the crash

**Comment by jjerphan** [comment]
We cannot reproduce this issue with 2.0, please update to 2.0.

`snakemake` is not available on `conda-forge` but it can be installed from `bioconda` using.

```
micromamba install -c bioconda snakemake
```

Feel free to reopen an issue with a reproduce if you still have this issue with 2.0.

Note that 1.x is note being developed anymore, but to address security fixes.
