### ISSUE TITLE
`mamba init` --- 'Namespace' object has no attribute 'no_user'

### ISSUE THREAD

**Issue by c2b2pss** [mamba-org/mamba#2457]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

'Namespace' object has no attribute 'no_user'

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

- Installed mambaforge outside of conda base
- Running mamba within conda base
- Trying to initalize mamba
- `mamba init`
- python=3.10.8, & 3.9.7 both give same error

### mamba info / micromamba info

```shell
environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/user/miniconda3/bin/conda
             CONDA_PREFIX=/home/user/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/user/miniconda3/bin/python
               CONDA_ROOT=/home/user/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
            DEFAULTS_PATH=/usr/share/gconf/pop.default.path
               LD_PRELOAD=<not set>
           MANDATORY_PATH=/usr/share/gconf/pop.mandatory.path
                     PATH=/home/user/miniconda3/bin:/home/user/miniconda3/
                          condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
                          /usr/games:/usr/local/games:/snap/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/user/miniconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.34=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/user/miniconda3  (writable)
      conda av data dir : /home/user/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : conda.anaconda.org/conda-forge/linux-64
                          conda.anaconda.org/conda-forge/noarch
                          conda.anaconda.org/bioconda/linux-64
                          conda.anaconda.org/bioconda/noarch
                          repo.anaconda.com/pkgs/main/linux-64
                          repo.anaconda.com/pkgs/main/noarch
                          repo.anaconda.com/pkgs/free/linux-64
                          repo.anaconda.com/pkgs/free/noarch
                          repo.anaconda.com/pkgs/r/linux-64
                          repo.anaconda.com/pkgs/r/noarch
                          conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.9.7 Linux/5.19.0-051900-generic pop/21.10 glibc/2.34
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Logs

```shell
`$ /home/user/miniconda3/bin/mamba init`
'Namespace' object has no attribute 'no_user'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 758, in do_call
        exit_code = shell_init(args)
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba_shell_init.py", line 87, in shell_init
        if args.no_user:
    AttributeError: 'Namespace' object has no attribute 'no_user'
```

**Comment by jonashaag** [comment]
You are not using the latest version of Mamba

**Comment by c2b2pss** [comment]
Agreed. But running "mamba update -n base mamba" here is the output.  It runs as v1.4 but sees only v1.2 in conda-forge ??  And running `mamba init` shows v 1.2

```
 mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['mamba']

warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
pkgs/main/linux-64                                   5.5MB @   2.6MB/s  2.1s
r/linux-64                                                    No change
bioconda/noarch                                    @   1.5MB/s  2.8s
pkgs/free/noarch                                              No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
bioconda/linux-64                                  @   1.5MB/s  3.0s
pkgs/free/linux-64                                            No change
r/noarch                                                      No change
pkgs/main/noarch                                   821.4kB @ 250.7kB/s  0.5s
conda-forge/noarch                                  11.9MB @   3.1MB/s  3.9s
conda-forge/linux-64                               @   3.6MB/s  8.7s

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: /home/premsubramaniam/mambaforge

  Updating specs:

   - mamba
   - ca-certificates
   - certifi
   - openssl


  Package       Version  Build            Channel                    Size
───────────────────────────────────────────────────────────────────────────
  Upgrade:
───────────────────────────────────────────────────────────────────────────

  - libmamba      1.1.0  h83d9b23_3       conda-forge                    
  + libmamba      1.2.0  habaa8ee_0       conda-forge/linux-64     Cached
  - libmambapy    1.1.0  py310h4d5d8b6_3  conda-forge                    
  + libmambapy    1.2.0  py310h4d5d8b6_0  conda-forge/linux-64     Cached
  - mamba         1.1.0  py310hf87f941_3  conda-forge                    
  + mamba         1.2.0  py310hf87f941_0  conda-forge/linux-64     Cached

  Summary:

  Upgrade: 3 packages

  Total download: 0 B

───────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] Y

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```


```
        mamba (1.2.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

'Namespace' object has no attribute 'no_user'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/premsubramaniam/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/premsubramaniam/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "/home/premsubramaniam/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/premsubramaniam/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/premsubramaniam/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
        exit_code = shell_init(args)
      File "/home/premsubramaniam/mambaforge/lib/python3.10/site-packages/mamba/mamba_shell_init.py", line 87, in shell_init
        if args.no_user:
    AttributeError: 'Namespace' object has no attribute 'no_user'
```

**Comment by jonashaag** [comment]
Hm do you have multiple installations? Also better to remove the default channels (see Troubleshooting docs) but that’s unrelated

**Comment by c2b2pss** [comment]
Well...I got this solved by updating conda and then mamba.  It was a rabbit hole, but permissions on 'miniconda3' folder was a problem.

Mamba is now v1.4.2.  But `mamba init` is trying to write to `~/.bashrc`.  Opened separate issue.

**Comment by jonashaag** [comment]
Yes it can be a mess :( next time you might want to try Micromamba :)
