### ISSUE TITLE
Mmaba v1.4.2 --- `~/.bashrc` permission denied

### ISSUE THREAD

**Issue by c2b2pss** [mamba-org/mamba#2461]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

bashrc

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

From within conda base, `mamba init` gives permission error with trying to write ~/.bashrc.

Should ~/.bashrc be written to? I searched the issues for `~/.bashrc`, but am confused with what is supposed to happen?

```
mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

no change     /home/user/miniconda3/condabin/conda
no change     /home/user/miniconda3/bin/conda
no change     /home/user/miniconda3/bin/conda-env
no change     /home/user/miniconda3/bin/activate
no change     /home/user/miniconda3/bin/deactivate
no change     /home/user/miniconda3/etc/profile.d/conda.sh
no change     /home/user/miniconda3/etc/fish/conf.d/conda.fish
no change     /home/user/miniconda3/shell/condabin/Conda.psm1
no change     /home/user/miniconda3/shell/condabin/conda-hook.ps1
no change     /home/user/miniconda3/lib/python3.10/site-packages/xontrib/conda.xsh
no change     /home/user/miniconda3/etc/profile.d/conda.csh
no change     /home/user/.bashrc
No action taken.
[Errno 13] Permission denied: '/home/user/.bashrc'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/user/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/user/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/user/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/user/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 762, in do_call
        exit_code = shell_init(args)
      File "/home/user/miniconda3/lib/python3.10/site-packages/mamba/mamba_shell_init.py", line 126, in shell_init
        add_mamba_to_rcfile(target_path, conda_prefix)
      File "/home/user/miniconda3/lib/python3.10/site-packages/mamba/mamba_shell_init.py", line 55, in add_mamba_to_rcfile
        with open(file, "w") as fo:
    PermissionError: [Errno 13] Permission denied: '/home/user/.bashrc' `
```

### mamba info / micromamba info

```shell
`$ /home/user/miniconda3/bin/mamba init`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/user/miniconda3/bin/conda
             CONDA_PREFIX=/home/user/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/user/miniconda3/bin/python
               CONDA_ROOT=/home/user/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
            DEFAULTS_PATH=/usr/share/gconf/pop.default.path
          LD_LIBRARY_PATH=:/home/user/miniconda3/lib
               LD_PRELOAD=<not set>
           MANDATORY_PATH=/usr/share/gconf/pop.mandatory.path
                     PATH=/home/user/miniconda3/bin:/home/user/.local/bin:
                          /home/user/miniconda3/condabin:/usr/local/sbin:/usr/local/b
                          in:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
                          :/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/user/miniconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.34=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/user/miniconda3  (writable)
      conda av data dir : /home/user/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.10 Linux/5.19.0-051900-generic pop/21.10 glibc/2.34
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by c2b2pss** [comment]
So when I run `mamba init`, I get this error. What does it mean? mamba was initalized properly or mot??

**Comment by jonashaag** [comment]
Are you sure? What's so special about Pop OS that it doesn't allow to run Mamba as user?

**Comment by c2b2pss** [comment]
@jonashaag  You can close this issue.  Thank you so much for your efforts - I was able to get past this.

I downloaded the file using a browser, so it's not as root.
