### ISSUE TITLE
Can't use pytorch properly on jetson nano

### ISSUE THREAD

**Issue by AtaraxyAdong** [mamba-org/mamba#2462]
Hello, I installed mamba on Jetson nano, and installed pytorch after creating a virtual environment, but when I run `import torch`, an error will be reported :
`Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import torch
  File "/home/adong/mambaforge/envs/openmmlab/lib/python3.8/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/home/adong/mambaforge/envs/openmmlab/lib/python3.8/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/adong/mambaforge/envs/openmmlab/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpi_cxx.so.40: cannot open shared object file: No such file or directory`
how should I solve this problem?

**Comment by jonashaag** [comment]
Please open a new ticket and use the issue template.
