### ISSUE TITLE
HELP!! Cannot start mamba:  ImportError: /home/user/mambaforge/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTIN8validate8RoleBaseE

### ISSUE THREAD

**Issue by c2b2pss** [mamba-org/mamba#2473]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

cython, ImportError

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Totally clueless about this error.

I updated mamba and conda.  After getting into conda base, now just typing "mamba" gives me the following error:

```
(base) user@pop-os:~$ mamba
Traceback (most recent call last):
  File "/home/user/mambaforge/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/user/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/home/user/mambaforge/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/user/mambaforge/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: /home/user/mambaforge/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTIN8validate8RoleBaseE
```

### mamba info / micromamba info

```shell
Mamba info: I cannot run mamba at all.  I get the above error.  The python version is 3.10.10.

Conda Info::

user@pop-os:~$ conda info

     active environment : None
            shell level : 0
       user config file : /home/user/.condarc
 populated config files : /home/user/mambaforge/.condarc
                          /home/user/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.34=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/user/mambaforge  (writable)
      conda av data dir : /home/user/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
          package cache : /home/user/mambaforge/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/mambaforge/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.10 Linux/5.19.0-051900-generic pop/21.10 glibc/2.34
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by c2b2pss** [comment]
Fixed using `conda update mamba` within base.
Then run `mamba update mamba`

However, getting multiple warnings of 
`libmamba Could not parse mod/etag header`

**Comment by c2b2pss** [comment]
Oh well! `mamba init` fails.

So I tried to reinstall mambaforge.  Now the original listed error is back, and `conda update mamba` does not fix it.

I'M GOING IN CIRCLES!!!! AAArgh!

**Comment by c2b2pss** [comment]
mamba init error:

`        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

memoryview: a bytes-like object is required, not 'str'
[sudo] password for user: 
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/user/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/user/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/user/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/user/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 762, in do_call
        exit_code = shell_init(args)
      File "/home/user/mambaforge/lib/python3.10/site-packages/mamba/mamba_shell_init.py", line 98, in shell_init
        exit_code = initialize(
      File "/home/user/mambaforge/lib/python3.10/site-packages/conda/core/initialize.py", line 113, in initialize
        run_plan_elevated(plan2)
      File "/home/user/mambaforge/lib/python3.10/site-packages/conda/core/initialize.py", line 709, in run_plan_elevated
        result = subprocess_call(
      File "/home/user/mambaforge/lib/python3.10/site-packages/conda/gateways/subprocess.py", line 98, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
      File "/home/user/mambaforge/lib/python3.10/subprocess.py", line 1154, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/home/user/mambaforge/lib/python3.10/subprocess.py", line 1985, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'
`

**Comment by c2b2pss** [comment]
Phew !!!  FIXED. Please close

`~/bashrc` was set up as root. Hence writing to it failed.  Fixing permissions to remove root then allowed all conda and mamba updates etc.

At some point on has to add conda to path.
