### ISSUE TITLE
DLL load failed while importing _ctypes

### ISSUE THREAD

**Issue by MMCMA** [mamba-org/mamba#2492]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

NA

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

I am trying to re-create an env that used to work. 

However, when installing it I keep on getting DLL import error:
```
Installing pip dependencies: - Ran pip subprocess with arguments:
['C:\\ProgramData\\mambaforge\\envs\\py310\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'D:\\condaenv.tpztv70r.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
Traceback (most recent call last):
  File "C:\ProgramData\mambaforge\envs\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\mambaforge\envs\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 43, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 23, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\ProgramData\mambaforge\envs\py310\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
    import ctypes
  File "C:\ProgramData\mambaforge\envs\py310\lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
```

For now I solved it by copying/overwriting the DLLs from mambaforge\DLLs

### mamba info / micromamba info

```shell
active environment : py310
    active env location : C:\ProgramData\mambaforge\envs\py310
            shell level : 2
       user config file : C:\Users\user1\.condarc
 populated config files : C:\ProgramData\mambaforge\.condarc
                          C:\Users\user1\.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.7=0
                          __win=0=0
       base environment : C:\ProgramData\mambaforge  (writable)
      conda av data dir : C:\ProgramData\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\mambaforge\pkgs
                          C:\Users\user1\.conda\pkgs
                          C:\Users\user1\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\mambaforge\envs
                          C:\Users\user1\.conda\envs
                          C:\Users\user1\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Windows/10 Windows/10.0.19045
          administrator : True
             netrc file : None
           offline mode : False
```

### environment.yml

```yaml
name: py310
channels:
  - conda-forge
dependencies:
  - python=3.10
  - arch-py
  - beautifulsoup4
  - bs4
  - catboost
  - cvxopt
  - cvxpy
  - fastcluster
  - hyperopt
  - h2o-py
  - langdetect
  - lightgbm
  - linearmodels
  - matplotlib
  - memory_profiler
  - nbformat
  - numpy
  - nltk
  - openpyxl
  - osqp
  - pandas=1.5.3
  - pip
  - pandas-datareader
  - pandera
  - pandoc
  - pathos
  - psutil
  - pyarrow
  - pycountry
  - pyportfolioopt
  - pyscipopt
  - pytest
  - python-benedict
  - pytorch
  - psycopg2-binary
  - ray-tune
  - requests
  - schema
  - scikit-learn
  - scipy
  - seaborn
  - snowflake-connector-python
  - snowflake-sqlalchemy
  - sqlalchemy
  - statsmodels
  - textdistance
  - xgboost
  - yfinance
  - pip:
    - exchange_calendars
```

### ~/.condarc

```yaml
ssl_verify: true
channels:
  - conda-forge
  - defaults
channel_priority: disabled
```

**Comment by jjerphan** [comment]
Hello,

This is because `exchange-calendars` as installed via `pip` rebuild the dependencies and fails, see this line:

```
['C:\\ProgramData\\mambaforge\\envs\\py310\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'D:\\condaenv.tpztv70r.requirements.txt', '--exists-action=b']
```

The solution is to modify your environment specification to install `exchange-calendars` from `conda-forge`, i.e. to perform this change:

```diff
53,54c53
<   - pip:
<     - exchange_calendars
---
>   - exchange_calendars
```

More generally, we recommend:
 - to install conda packages from `conda-forge` 
 - not to mix `defaults` and `conda-forge`
 - to install wheels from PyPI when their conda package counterpart aren't available (on `conda-forge`)
