### ISSUE TITLE
Mamba 1.4.3 - mamba create fails 

### ISSUE THREAD

**Issue by npanpaliya** [mamba-org/mamba#2593]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

Yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I've built mamba 1.4.3 and 1.4.4 using our conda recipe https://github.com/open-ce/mamba-feedstock and encountered following error while running `mamba create -n test_py2 python=3.9 --dry-run`  -
```
+ mamba create -n test_py2 python=3.9 --dry-run
warning  libmamba Extracted package cache '/opt/conda/pkgs/_libgcc_mutex-0.1-main' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/ld_impl_linux-64-2.38-h1181459_1' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/libstdcxx-ng-11.2.0-h1234567_1' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/ca-certificates-2023.05.30-h06a4308_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/libgomp-11.2.0-h1234567_1' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/_openmp_mutex-5.1-1_gnu' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/libgcc-ng-11.2.0-h1234567_1' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/xz-5.4.2-h5eee18b_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/libffi-3.4.4-h6a678d5_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/zlib-1.2.13-h5eee18b_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/openssl-1.1.1t-h7f8727e_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/ncurses-6.4-h6a678d5_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/tk-8.6.12-h1ccaba5_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/readline-8.2-h5eee18b_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/sqlite-3.41.2-h5eee18b_0' has invalid url
warning  libmamba Extracted package cache '/opt/conda/pkgs/tzdata-2023c-h04d1e81_0' has invalid url
missing key https://repo.anaconda.com/pkgs/main in channels: {'https://repo.anaconda.com/pkgs/main/linux-64': {'platform': 'linux-64', 'url': 'https://repo.anaconda.com/pkgs/main/linux-64', 'channel': pkgs/main[linux-64,noarch]}, 'https://repo.anaconda.com/pkgs/main/noarch': {'platform': 'noarch', 'url': 'https://repo.anaconda.com/pkgs/main/noarch', 'channel': pkgs/main[linux-64,noarch]}, 'https://repo.anaconda.com/pkgs/r/linux-64': {'platform': 'linux-64', 'url': 'https://repo.anaconda.com/pkgs/r/linux-64', 'channel': pkgs/r[linux-64,noarch]}, 'https://repo.anaconda.com/pkgs/r/noarch': {'platform': 'noarch', 'url': 'https://repo.anaconda.com/pkgs/r/noarch', 'channel': pkgs/r[linux-64,noarch]}}

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/mamba/mamba.py", line 968, in exception_converter
        raise e
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/mamba/mamba.py", line 961, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/mamba/mamba.py", line 919, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/mamba/mamba.py", line 784, in do_call
        exit_code = create(args, parser)
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/mamba/mamba.py", line 632, in create
        return install(args, parser, "create")
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/mamba/mamba.py", line 590, in install
        conda_transaction = to_txn(
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/mamba/utils.py", line 449, in to_txn
        final_precs = compute_final_precs(
      File "/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/mamba/utils.py", line 395, in compute_final_precs
        raise ValueError("missing key {} in channels: {}".format(key, lookup_dict))
    ValueError: missing key https://repo.anaconda.com/pkgs/main in channels: {'https://repo.anaconda.com/pkgs/main/linux-64': {'platform': 'linux-64', 'url': 'https://repo.anaconda.com/pkgs/main/linux-64', 'channel': pkgs/main[linux-64,noarch]}, 'https://repo.anaconda.com/pkgs/main/noarch': {'platform': 'noarch', 'url': 'https://repo.anaconda.com/pkgs/main/noarch', 'channel': pkgs/main[linux-64,noarch]}, 'https://repo.anaconda.com/pkgs/r/linux-64': {'platform': 'linux-64', 'url': 'https://repo.anaconda.com/pkgs/r/linux-64', 'channel': pkgs/r[linux-64,noarch]}, 'https://repo.anaconda.com/pkgs/r/noarch': {'platform': 'noarch', 'url': 'https://repo.anaconda.com/pkgs/r/noarch', 'channel': pkgs/r[linux-64,noarch]}}

`$ /opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/mamba create -n test_py2 python=3.9  --dry-run`
  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
              CONDA_BUILD=1
        CONDA_BUILD_STATE=TEST
        CONDA_DEFAULT_ENV=/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placeh
                CONDA_EXE=/opt/conda/bin/conda
               CONDA_HOME=/opt/conda
                CONDA_LUA=5
                CONDA_NPY=116
               CONDA_PERL=5.26
             CONDA_PREFIX=/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placeh
           CONDA_PREFIX_1=/opt/conda
    CONDA_PROMPT_MODIFIER=(/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_pl
                          acehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
                          acehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
                          acehold_placeh)
                 CONDA_PY=310
         CONDA_PYTHON_EXE=/opt/conda/bin/python
                  CONDA_R=3.5
               CONDA_ROOT=/opt/conda
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
               LD_PRELOAD=<not set>
              LD_RUN_PATH=/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placeh/lib
                     PATH=/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placeh:/opt/conda/conda-bld/mamba-split_1686740174158/_test_env
                          _placehold_placehold_placehold_placehold_placehold_placehold_placehold
                          _placehold_placehold_placehold_placehold_placehold_placehold_placehold
                          _placehold_placehold_placeh/bin:/opt/conda/conda-bld/mamba-split_16867
                          40174158/_test_env_placehold_placehold_placehold_placehold_placehold_p
                          lacehold_placehold_placehold_placehold_placehold_placehold_placehold_p
                          lacehold_placehold_placehold_placehold_placeh/bin:/opt/conda/condabin:
                          /home/builder/.local/bin:/home/builder/bin:/opt/conda/bin:/usr/local/s
                          bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          PKG_CONFIG_PATH=/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placeh/lib/pkgconfig
                   PYTHON=/opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placeh/bin/python
         PYTHONNOUSERSITE=1
               PYTHONPATH=:/home/builder/open_ce
       REQUESTS_CA_BUNDLE=
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
            shell level : 2
       user config file : /home/builder/.condarc
 populated config files : /opt/conda/.condarc
                          /home/builder/.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.28=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh  (writable)
      conda av data dir : /opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
       envs directories : /opt/conda/envs
                          /opt/conda/conda-bld/mamba-split_1686740174158/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/envs
                          /home/builder/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.0 requests/2.29.0 CPython/3.10.11 Linux/3.10.0-1160.62.1.el7.x86_64 rhel/8.6 glibc/2.28
                UID:GID : 1084:1500
             netrc file : None
           offline mode : False

```

I noticed this error goes away if I remove entries of `envs_dir` and `pkgs_dirs` from condarc file. 
Also, this issue was not seen in mamba 1.4.2 and I found this commit https://github.com/mamba-org/mamba/commit/5fa2ce3f3dff8b46f771248dbb5f3e0d592b9e44 is causing this issue. But not sure exactly which change.

Any help is appreciated. 
Thanks in advance.

### ~/.condarc

```yaml
envs_dirs:
  - /opt/conda/envs
pkgs_dirs:
  - /opt/conda/pkgs
auto_update_conda: true
notify_outdated_conda: false
```

**Comment by jonashaag** [comment]
@AntoinePrv xref #2409
