### ISSUE TITLE
Mamba crashes trying to install anything

### ISSUE THREAD

**Issue by fperez** [mamba-org/mamba#2597]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

missing key in channels 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

As mentioned in #2543, I'm trying to sort out why a given environment won't install JuptyerLab 4. At some point I removed several packages and mamba then agreed to try and install it, but now it immediately crashes when attempting the installation. Furthermore, it's crashing when trying to install _any_ new package not already present.

This was a fresh, from mamba-forge installation on a clean system, where all I did:

1. Install mamba-forge
2. Build a fairly complex environment with many packages
3. Try to install JupyterLab 4, and upon failing, remove a few things until mamba would proceed.

Now, the environment is completely broken, and the only error reported is this (the same error causes a crash no matter what I try to install):

```
Looking for: ['jupyterlab']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: /Users/fperez/local/conda

  Updating specs:

   - jupyterlab
   - ca-certificates
   - certifi
   - openssl


  Package                Version  Build         Channel           Size
────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────

  + jupyter-lsp            2.2.0  pyhd8ed1ab_0  conda-forge     Cached
  + jupyter_server         2.6.0  pyhd8ed1ab_0  conda-forge     Cached
  + jupyterlab             4.0.2  pyhd8ed1ab_0  conda-forge     Cached
  + jupyterlab_pygments    0.2.2  pyhd8ed1ab_0  conda-forge     Cached
  + jupyterlab_server     2.23.0  pyhd8ed1ab_0  conda-forge     Cached
  + nbconvert-core         7.5.0  pyhd8ed1ab_0  conda-forge     Cached
  + notebook-shim          0.2.3  pyhd8ed1ab_0  conda-forge     Cached

  Summary:

  Install: 7 packages

  Total download: 0 B

────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] y
missing key https://conda.anaconda.org/conda-forge in channels: {'https://conda.anaconda.org/conda-forge/osx-arm64': {'platform': 'osx-arm64', 'url': 'https://conda.anaconda.org/conda-forge/osx-arm64', 'channel': conda-forge[osx-arm64,noarch]}, 'https://conda.anaconda.org/conda-forge/noarch': {'platform': 'noarch', 'url': 'https://conda.anaconda.org/conda-forge/noarch', 'channel': conda-forge[osx-arm64,noarch]}}

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/fperez/local/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/fperez/local/conda/lib/python3.10/site-packages/mamba/mamba.py", line 968, in exception_converter
        raise e
      File "/Users/fperez/local/conda/lib/python3.10/site-packages/mamba/mamba.py", line 961, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/fperez/local/conda/lib/python3.10/site-packages/mamba/mamba.py", line 919, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/Users/fperez/local/conda/lib/python3.10/site-packages/mamba/mamba.py", line 780, in do_call
        exit_code = install(args, parser, "install")
      File "/Users/fperez/local/conda/lib/python3.10/site-packages/mamba/mamba.py", line 590, in install
        conda_transaction = to_txn(
      File "/Users/fperez/local/conda/lib/python3.10/site-packages/mamba/utils.py", line 449, in to_txn
        final_precs = compute_final_precs(
      File "/Users/fperez/local/conda/lib/python3.10/site-packages/mamba/utils.py", line 395, in compute_final_precs
        raise ValueError("missing key {} in channels: {}".format(key, lookup_dict))
    ValueError: missing key https://conda.anaconda.org/conda-forge in channels: {'https://conda.anaconda.org/conda-forge/osx-arm64': {'platform': 'osx-arm64', 'url': 'https://conda.anaconda.org/conda-forge/osx-arm64', 'channel': conda-forge[osx-arm64,noarch]}, 'https://conda.anaconda.org/conda-forge/noarch': {'platform': 'noarch', 'url': 'https://conda.anaconda.org/conda-forge/noarch', 'channel': conda-forge[osx-arm64,noarch]}}

`$ /Users/fperez/local/conda/bin/mamba install jupyterlab`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/fperez/local/conda/bin/conda
             CONDA_PREFIX=/Users/fperez/local/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/fperez/local/conda/bin/python
               CONDA_ROOT=/Users/fperez/local/conda
              CONDA_SHLVL=1
                    CPATH=:/Users/fperez/tmp/junk/include:/Users/fperez/usr/include:/Users/fpere
                          z/usr/local/include:/Users/fperez/.local/include:
           CURL_CA_BUNDLE=<not set>
         GDAL_DRIVER_PATH=/Users/fperez/local/conda/lib/gdalplugins
             JUPYTER_PATH=/Users/fperez/.local/share/jupyter
          LD_LIBRARY_PATH=:
               LD_PRELOAD=<not set>
             LIBRARY_PATH=:
                  MANPATH=/Users/fperez/tmp/junk/share/man:/Users/fperez/usr/share/man:/Users/fp
                          erez/usr/local/share/man:/Users/fperez/.local/share/man:
                     PATH=/Users/fperez/local/conda/bin:/Users/fperez/local/conda/condabin:.:/Us
                          ers/fperez/tmp/junk/bin:/Users/fperez/usr/bin:/Users/fperez/usr/local/
                          bin:/Users/fperez/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr
                          /local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bi
                          n:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/var/run/com.apple
                          .security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.a
                          pple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.app
                          le.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/App
                          lications/iTerm.app/Contents/Resources/utilities
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/fperez/local/conda
            shell level : 1
       user config file : /Users/fperez/.condarc
 populated config files : /Users/fperez/local/conda/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.4=0
                          __unix=0=0
       base environment : /Users/fperez/local/conda  (writable)
      conda av data dir : /Users/fperez/local/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/fperez/local/conda/pkgs
                          /Users/fperez/.conda/pkgs
       envs directories : /Users/fperez/local/conda/envs
                          /Users/fperez/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.11 Darwin/22.5.0 OSX/13.4
                UID:GID : 33212:20665
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

I'm now simply going to nuke the entire installation and start from scratch, as it's impossible to use it further for anything. But I figured I'd report the error so hopefully a future version can catch that exception.

**Comment by fperez** [comment]
The `/Users/fperez/local/conda` is my mambaforge installation, so renaming that means deactivating the installation. I deleted it entirely so I could actually work, since at this point Mamba was completely unusable. Hopefully you can add some handling for that error path so at least mamba doesn't become wedged if the problem arises - logging an error to the console and continuing would be more useful to the user than not being able to install anything ever again.

**Comment by AntoinePrv** [comment]
Could you try deleting these folders: `/Users/fperez/local/conda/pkgs/cache` `/Users/fperez/.conda/pkgs/cache` ?

**Comment by AntoinePrv** [comment]
It also looks like it could be related to `mamba-forge` packaging.

**Comment by fperez** [comment]
Thanks for the suggestion @AntoinePrv - unfortunately in order to be able to work, I nuked my installation entirely, so I can't replicate it anymore. I'll report here if it happens again and will try your idea.
