### ISSUE TITLE
force-reinstall error in v1.4.5

### ISSUE THREAD

**Issue by gboeing** [mamba-org/mamba#2634]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

force-reinstall

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

I am using mamba 1.4.5. The following line runs successfully:
```
mamba install --update-all -c conda-forge --strict-channel-priority --no-banner --file requirements.txt
```
However, adding `--force-reinstall` to it like this fails:
```
mamba install --update-all --force-reinstall -c conda-forge --strict-channel-priority --no-banner --file requirements.txt
```

I saw PR #2601 but there wasn't much info about it, or a related issue it closed, so I'm not sure if this is related to it or not. But it appears that the work done in #2601 was released in 1.4.5.

I have tried this on my local machine (M1 Mac) and in a jupyter/base-notebook Docker container. Same result. I'll paste the Docker attempt output below, but it's equivalent.

### mamba info / micromamba info

```shell
$ mamba info

          mamba version : 1.4.5
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=aarch64
                          __glibc=2.35=0
                          __linux=5.15.49=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-aarch64
             user-agent : conda/23.5.0 requests/2.31.0 CPython/3.11.4 Linux/5.15.49-linuxkit-pr ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```

### Logs

```shell
$ mamba install --update-all --force-reinstall -c conda-forge --strict-channel-priority --no-banner --verbose --file requirements.txt

Looking for: ['osmnx', 'python=3.11', 'beautifulsoup4', 'bokeh', 'bottleneck', 'cartopy', 'contextily', 'cython', 'folium', 'jupyterlab', 'mapclassify', 'numexpr', 'pillow', 'psycopg2', 'pysal', 'python-igraph', 'seaborn', 'statsmodels', 'furo', 'pip', 'sphinx', 'conda-smithy', 'hatch', 'twine', 'black', 'nbdime', 'nbqa', 'pre-commit', 'pytest', 'pytest-cov', 'ruff']

info     libmamba Loading single package record: "/opt/conda/conda-meta/ncurses-6.4-h2e1726e_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libbrotlidec-1.0.9-h4e544f5_9.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/cffi-1.15.1-py311h2e7898d_3.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libev-4.33-h516909a_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/cryptography-41.0.1-py311hd42d77a_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/typing-extensions-4.6.3-hd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/xz-5.2.6-h9cdd2b7_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyter_core-5.3.1-py311hec3470c_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/yaml-cpp-0.7.0-h4de3ea5_2.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libuuid-2.38.1-hb4cce97_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/readline-8.2-h8fc344f_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/brotli-bin-1.0.9-h4e544f5_9.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/setuptools-68.0.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/conda-package-handling-2.0.2-pyh38be061_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pycparser-2.21-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/ca-certificates-2023.5.7-hcefe29a_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pluggy-1.2.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jsonpatch-1.32-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/lzo-2.10-h516909a_1000.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/keyutils-1.6.1-h4e544f5_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libmamba-1.4.5-h0c45e31_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/typing_extensions-4.6.3-pyha770c72_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/zstandard-0.19.0-py311hb827a26_2.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/toolz-0.12.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libiconv-1.17-h9cdd2b7_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/tqdm-4.65.0-pyhd8ed1ab_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/reproc-cpp-14.2.4-hd600fc2_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/packaging-23.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/conda-23.5.0-py311hec3470c_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libsolv-0.7.24-hd84c7bf_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libbrotlienc-1.0.9-h4e544f5_9.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libnsl-2.0.0-hf897c2e_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/colorama-0.4.6-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/lz4-c-1.9.4-hd600fc2_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/traitlets-5.9.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libbrotlicommon-1.0.9-h4e544f5_9.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/_openmp_mutex-4.5-2_gnu.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/conda-package-streaming-0.8.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pyopenssl-23.2.0-pyhd8ed1ab_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/krb5-1.20.1-h113d92e_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/bzip2-1.0.8-hf897c2e_4.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libffi-3.4.2-h3557bc0_5.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libexpat-2.5.0-hd600fc2_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/brotli-1.0.9-h4e544f5_9.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/fmt-9.1.0-hdd96247_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libmambapy-1.4.5-py311he85eb8a_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pysocks-1.7.1-pyha2e5f31_6.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/wheel-0.40.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libssh2-1.11.0-h492db2e_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libsqlite-3.42.0-h194ca79_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/python_abi-3.11-3_cp311.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/urllib3-2.0.3-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/mamba-1.4.5-py311hb6c5aa6_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libgcc-ng-13.1.0-h2b4548d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libzlib-1.2.13-h31becfc_5.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/tzdata-2023c-h71feb2d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/charset-normalizer-3.1.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/requests-2.31.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/ruamel.yaml.clib-0.2.7-py311h1d6c08a_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/boltons-23.0.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libarchive-3.6.2-h566b526_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/python-3.11.4-h43d1f9e_0_cpython.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libxml2-2.11.4-h164fba4_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/icu-72.1-hcf00150_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/openssl-3.1.1-h31becfc_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/idna-3.4-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pybind11-abi-4-hd8ed1ab_3.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/platformdirs-3.8.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libnghttp2-1.52.0-h250e5c5_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/c-ares-1.19.1-h31becfc_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/certifi-2023.5.7-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/zstd-1.5.2-h44f6412_6.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/ruamel.yaml-0.17.32-py311hcd402e7_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libgomp-13.1.0-h2b4548d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pip-23.1.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/tk-8.6.12-hd8af866_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libedit-3.1.20191231-he28a2e2_2.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/ld_impl_linux-aarch64-2.40-h2d8c526_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libstdcxx-ng-13.1.0-h452befe_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jsonpointer-2.0-py_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/reproc-14.2.4-hb4cce97_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libcurl-8.1.2-hc34909b_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pycosat-0.6.4-py311hdfa8b44_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/mako-1.2.4-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/yaml-0.2.5-hf897c2e_2.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/tornado-6.3.2-py311hc8f2f60_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/zlib-1.2.13-h31becfc_5.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/blinker-1.6.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pexpect-4.8.0-pyh1a96a4e_2.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyterlab-4.0.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/six-1.16.0-pyh6c4a22f_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/oauthlib-3.2.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pandocfilters-1.5.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/notebook-shim-0.2.3-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyter_client-8.3.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/tomli-2.0.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyter-lsp-2.2.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyter_telemetry-0.1.0-pyhd8ed1ab_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/tinycss2-1.2.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyterlab_server-2.23.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pure_eval-0.2.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyterlab_pygments-0.2.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/sniffio-1.3.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/mistune-3.0.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libsodium-1.0.18-hb9de7d4_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/parso-0.8.3-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/libuv-1.44.2-h4e544f5_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/asttokens-2.2.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pyzmq-25.1.0-py311hc83961d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jedi-0.18.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/prompt-toolkit-3.0.38-pyha770c72_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/webencodings-0.5.1-py_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/async-lru-2.0.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/babel-2.12.1-pyhd8ed1ab_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/rfc3986-validator-0.1.1-pyh9f0ad1d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/async_generator-1.10-py_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/backports.functools_lru_cache-1.6.5-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/overrides-7.3.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/defusedxml-0.7.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/sqlalchemy-2.0.17-py311hc8f2f60_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/terminado-0.17.1-pyh41d4057_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/argon2-cffi-21.3.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyterhub-base-4.0.1-pyh2a2186d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/wcwidth-0.2.6-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/send2trash-1.8.2-pyh41d4057_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/executing-1.2.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/argon2-cffi-bindings-21.2.0-py311hdfa8b44_3.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/nest-asyncio-1.5.6-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/nbclient-0.8.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/anyio-3.7.0-pyhd8ed1ab_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/nodejs-18.15.0-hcab9400_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyter_server-2.7.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/python-fastjsonschema-2.17.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/ipython-8.14.0-pyh41d4057_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pycurl-7.45.1-py311h4769251_3.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jsonschema-4.17.3-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pkgutil-resolve-name-1.3.10-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/beautifulsoup4-4.12.2-pyha770c72_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/prompt_toolkit-3.0.38-hd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/markupsafe-2.1.3-py311hc8f2f60_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/decorator-5.1.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pygments-2.15.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/nbclassic-1.0.0-pyhb4ecaf3_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyter_events-0.6.3-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/importlib_metadata-6.7.0-hd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/json5-0.9.5-pyh9f0ad1d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/certipy-0.1.3-py_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/backcall-0.2.0-pyh9f0ad1d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/comm-0.1.3-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/entrypoints-0.4-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pandoc-3.1.3-h8af1aa0_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/nbconvert-core-7.6.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/exceptiongroup-1.1.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/flit-core-3.9.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/configurable-http-proxy-4.5.4-hc2da131_2.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/prometheus_client-0.17.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/greenlet-2.0.2-py311h8715677_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/ptyprocess-0.7.0-pyhd3deb0d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/soupsieve-2.3.2.post1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/debugpy-1.6.7-py311hbb176d9_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/attrs-23.1.0-pyh71513ae_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/importlib_resources-5.12.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/rfc3339-validator-0.1.4-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/psutil-5.9.5-py311h1d6c08a_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pyjwt-2.7.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/notebook-6.5.4-pyha770c72_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyterhub-4.0.1-pyh2a2186d_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/stack_data-0.6.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/backports-1.0-pyhd8ed1ab_3.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/typing_utils-0.1.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/importlib-metadata-6.7.0-pyha770c72_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/python-json-logger-2.0.7-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/python-dateutil-2.8.2-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jinja2-3.1.2-pyhd8ed1ab_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/jupyter_server_terminals-0.4.4-pyhd8ed1ab_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pyrsistent-0.19.3-py311h9f62e77_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/ipykernel-6.23.3-pyh71e2992_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pyyaml-6.0-py311hdfa8b44_5.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/alembic-1.11.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/nbconvert-pandoc-7.6.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pamela-1.0.0-py_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pytz-2023.3-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/pickleshare-0.7.5-py_1003.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/zipp-3.15.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/websocket-client-1.6.1-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/nbconvert-7.6.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/zeromq-4.3.4-h01db608_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/bleach-6.0.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/ipython_genutils-0.2.0-py_1.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/nbformat-5.9.0-pyhd8ed1ab_0.json"
info     libmamba Loading single package record: "/opt/conda/conda-meta/matplotlib-inline-0.1.6-pyhd8ed1ab_0.json"
info     libmamba Reading cache files '/tmp/tmpq8orpvz_.*' for repo index 'installed'
info     libmamba Reading repodata.json file "/tmp/tmpq8orpvz_" for repo installed
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/linux-aarch64/repodata.json'
conda-forge/linux-aarch64                                   Using cache
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/noarch/repodata.json'
conda-forge/noarch                                          Using cache
info     libmamba All targets to download are cached
Channel: conda-forge[linux-aarch64,noarch], platform: linux-aarch64, prio: 1 : 0
Cache path:  /opt/conda/pkgs/cache/d9d93fba.solv
info     libmamba Reading cache files '/opt/conda/pkgs/cache/d9d93fba.solv.*' for repo index 'conda-forge/linux-aarch64'
info     libmamba Attempting to read libsolv solv file "/opt/conda/pkgs/cache/d9d93fba.solv" for repo conda-forge/linux-aarch64
info     libmamba Expecting solv metadata : {"etag":"W/\"26cadab97835c31f7b3a3301e1d8e1e9\"","mod":"Wed, 28 Jun 2023 14:51:55 GMT","pip_added":true,"tool_version":"1.3_0.7.24","url":"https://conda.anaconda.org/conda-forge/linux-aarch64"}
info     libmamba Loaded solv metadata : {"etag":"W/\"26cadab97835c31f7b3a3301e1d8e1e9\"","mod":"Wed, 28 Jun 2023 14:51:55 GMT","pip_added":true,"tool_version":"1.3_0.7.24","url":"https://conda.anaconda.org/conda-forge/linux-aarch64"}
info     libmamba Metadata from solv are valid, loading successful
Channel: conda-forge[linux-aarch64,noarch], platform: noarch, prio: 1 : 0
Cache path:  /opt/conda/pkgs/cache/09cdf8bf.solv
info     libmamba Reading cache files '/opt/conda/pkgs/cache/09cdf8bf.solv.*' for repo index 'conda-forge/noarch'
info     libmamba Attempting to read libsolv solv file "/opt/conda/pkgs/cache/09cdf8bf.solv" for repo conda-forge/noarch
info     libmamba Expecting solv metadata : {"etag":"W/\"be5876d0ba6021d6f484006cc7eba492\"","mod":"Wed, 28 Jun 2023 15:02:56 GMT","pip_added":true,"tool_version":"1.3_0.7.24","url":"https://conda.anaconda.org/conda-forge/noarch"}
info     libmamba Loaded solv metadata : {"etag":"W/\"be5876d0ba6021d6f484006cc7eba492\"","mod":"Wed, 28 Jun 2023 15:02:56 GMT","pip_added":true,"tool_version":"1.3_0.7.24","url":"https://conda.anaconda.org/conda-forge/noarch"}
info     libmamba Metadata from solv are valid, loading successful
info     libmamba Parsing MatchSpec osmnx
info     libmamba Parsing MatchSpec osmnx
Could not find any installed package matching ""

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 933, in exception_converter
        raise e
      File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 926, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 884, in _wrapped_main
        result = do_call(parsed_args, p)
                 ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 755, in do_call
        exit_code = install(args, parser, "install")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 490, in install
        solver.add_jobs(mamba_solve_specs, solver_task)
    RuntimeError: Could not find any installed package matching ""

`$ /opt/conda/bin/mamba install --update-all --force-reinstall -c conda-forge --strict-channel-priority --no-banner --verbose --file requirements.txt`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_DIR=/opt/conda
                CONDA_EXE=/opt/conda/bin/conda
             CONDA_PREFIX=/opt/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/conda/bin/python
               CONDA_ROOT=/opt/conda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr
                          /local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=aarch64
                          __glibc=2.35=0
                          __linux=5.15.49=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-aarch64
             user-agent : conda/23.5.0 requests/2.31.0 CPython/3.11.4 Linux/5.15.49-linuxkit-pr ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:100
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

### environment.yml

```yaml
n/a
```

### ~/.condarc

```yaml
$ cat ~/.condarc
cat: /home/jovyan/.condarc: No such file or directory
```

**Comment by gboeing** [comment]
Also: the full command including `--force-reinstall` worked regularly to build this environment across platforms for many months and as recently as a couple weeks ago. Today is the first time it had this error.

**Comment by AntoinePrv** [comment]
It seems at the moment `--force-reinstall` does not work in combination with packages that are not installed.
