### ISSUE TITLE
Micromamba Docker cannot install environment - permission denied when trying to write environment file

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [mamba-org/mamba#2720]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

permission denied

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Outside of Docker, mamba can build the environment successfully. Conda with Docker might be fine - my docker build over the weekend failed because my computer lost internet, but it did successfully solve the environment before that.

### Describe your issue

Notes:
1. Although the docker image pulled is micromamba, calling `micromamba info` failed to find the command `micromamba` but `mamba info` works and the output is shown below.
2. `mamba install -v ...` has too long of an output in VS code and the top part is cut off so I included as much as I can. I skipped some of the repetitive or irrelevant parts.
3. The MPI dependencies caused solve issues in the previous working version of the Dockerfile. So in the previous version, I installed MPI separately then updated the rest of the environment with mamba. In the current version, I am seeing if they can be installed together, hence the difference.

I am trying to build an environment as a docker image. As of 1 month ago, the following Dockerfile produced no issues and can complete the build successfully, both local and on GitHub actions. Locally, I am using an Apple M1 Ultra Mac.

```
ARG CONDA_VERSION=23.3.1-0
FROM --platform=linux/amd64 continuumio/miniconda3:${CONDA_VERSION} as build

ARG CONDA_ENV=rietveld

ENV MAUD_PATH=/Maud
ENV CINEMA_PATH=/cinema
ENV PATH="${PATH}:/opt/conda/envs/${CONDA_ENV}/bin"

# Fetch MILK
COPY . /MILK

# Pre-requisites
ENV DEBIAN_FRONTEND noninteractive
RUN apt update \
    && apt -y install \
        vim \
    && rm -rf /var/lib/apt/lists/*

# Install MILK
RUN cd MILK \
    && conda install mamba -n base -c conda-forge \
    && mamba create -n ${CONDA_ENV} -c conda-forge openmpi mpi4py \
    && mamba env update -n ${CONDA_ENV} -f environments/environment_linux_docker.yml \
    && echo "conda activate $CONDA_ENV" >> ~/.bashrc
```

I discovered as of 2 weeks ago that the build script no longer works. The error is:

```
[2029]# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
[2030](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2031)

[2031](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2032)
    Traceback (most recent call last):
[2032](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2033)
      File "/opt/conda/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
[2033](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2034)
        return func(*args, **kwargs)
[2034](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2035)
      File "/opt/conda/lib/python3.10/site-packages/conda_env/cli/main.py", line 56, in do_call
[2035](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2036)
        exit_code = getattr(module, func_name)(arguments, parser)
[2036](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2037)
      File "/opt/conda/lib/python3.10/site-packages/conda/notices/core.py", line 124, in wrapper
[2037](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2038)
        return func(*args, **kwargs)
[2038](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2039)
      File "/opt/conda/lib/python3.10/site-packages/conda_env/cli/main_update.py", line 143, in execute
[2039](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2040)
        result[installer_type] = installer.install(prefix, specs, args, env)
[2040](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2041)
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba_env.py", line 169, in mamba_install
[2041](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2042)
        conda_transaction = to_txn(
[2042](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2043)
      File "/opt/conda/lib/python3.10/site-packages/mamba/utils.py", line 464, in to_txn
[2043](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2044)
        final_precs = compute_final_precs(
[2044](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2045)
      File "/opt/conda/lib/python3.10/site-packages/mamba/utils.py", line 410, in compute_final_precs
[2045](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2046)
        raise ValueError("missing key {} in channels: {}".format(key, lookup_dict))
[2046](https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594#step:3:2047)
    ValueError: missing key https://conda.anaconda.org/conda-forge/noarch/wheel-0.41.0-pyhd8ed1ab_0.conda in channels: {'https://repo.anaconda.com/pkgs/main/linux-64': {'platform': 'linux-64', 'url': 'https://repo.anaconda.com/pkgs/main/linux-64', 'channel': pkgs/main[linux-64,noarch], 'needs_finalising': False}, 'https://repo.anaconda.com/pkgs/main/noarch': {'platform': 'noarch', 'url': 'https://repo.anaconda.com/pkgs/main/noarch', 'channel': pkgs/main[linux-64,noarch], 'needs_finalising': False}, 'https://repo.anaconda.com/pkgs/r/linux-64': {'platform': 'linux-64', 'url': 'https://repo.anaconda.com/pkgs/r/linux-64', 'channel': pkgs/r[linux-64,noarch], 'needs_finalising': False}, 'https://repo.anaconda.com/pkgs/r/noarch': {'platform': 'noarch', 'url': 'https://repo.anaconda.com/pkgs/r/noarch', 'channel': pkgs/r[linux-64,noarch], 'needs_finalising': False}, 'https://conda.anaconda.org/conda-forge/linux-64': {'platform': 'linux-64', 'url': 'https://conda.anaconda.org/conda-forge/linux-64', 'channel': conda-forge[linux-64,noarch], 'needs_finalising': False}, 'https://conda.anaconda.org/conda-forge/noarch': {'platform': 'noarch', 'url': 'https://conda.anaconda.org/conda-forge/noarch', 'channel': conda-forge[linux-64,noarch], 'needs_finalising': False}}
```

I have been trying new approaches. In a previous issue thread that I created and now closed, @jonashaag helped pointed me to the documentation page and I found the mamba/micromamba docker image for building. Now my dockerfile is shown below. But I encounter permission writing issues that I tried to address with the added user and change permission, but it didn't fix the permission problem. 

```
FROM mambaorg/micromamba:1.4.9

ARG CONDA_ENV=base
ENV MAUD_PATH=/Maud
ENV CINEMA_PATH=/cinema

USER root
RUN adduser --disabled-password --gecos '' newuser \
    && adduser newuser sudo \
    && echo '%sudo ALL=(ALL:ALL) ALL' >> /etc/sudoers

RUN mkdir -p /home/MILK
# Fetch MILK
COPY . /home/MILK/.
RUN chown newuser /home/MILK
USER newuser
WORKDIR /home/MILK

RUN micromamba install -v -y -n base -f environments/environment_linux_docker.yml
```

### mamba info / micromamba info

```shell
mamba version : 1.4.9
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 23.7.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=aarch64
                          __glibc=2.31=0
                          __linux=5.15.49=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-aarch64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-aarch64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-aarch64
             user-agent : conda/23.7.1 requests/2.28.1 CPython/3.10.12 Linux/5.15.49-linuxkit-pr debian/11 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Logs

```shell
#0 22.44 info     libmamba Download finished, validating '/opt/conda/pkgs/jinja2-3.1.2-pyhd8ed1ab_1.tar.bz2'
#0 22.52 info     libmamba Transfer done for 'prompt_toolkit'
#0 22.52 info     libmamba Transfer finalized, status: 200 [https://conda.anaconda.org/conda-forge/noarch/prompt_toolkit-3.0.39-hd8ed1ab_0.conda] 6731 bytes
#0 22.52 info     libmamba Download finished, validating '/opt/conda/pkgs/prompt_toolkit-3.0.39-hd8ed1ab_0.conda'
#0 22.57 info     libmamba Transfer done for 'widgetsnbextension'
#0 22.57 info     libmamba Transfer finalized, status: 200 [https://conda.anaconda.org/conda-forge/noarch/widgetsnbextension-4.0.8-pyhd8ed1ab_0.conda] 1071462 bytes
#0 22.57 info     libmamba Download finished, validating '/opt/conda/pkgs/widgetsnbextension-4.0.8-pyhd8ed1ab_0.conda'
#0 22.61 info     libmamba Transfer done for 'svt-av1'
#0 22.61 info     libmamba Transfer finalized, status: 200 [https://conda.anaconda.org/conda-forge/linux-aarch64/svt-av1-1.6.0-h2f0025b_0.conda] 1547008 bytes
#0 22.61 info     libmamba Download finished, validating '/opt/conda/pkgs/svt-av1-1.6.0-h2f0025b_0.conda'
...
#0 23.56 Linking mpi-1.0-openmpi
#0 23.56 Linking python_abi-3.9-3_cp39
...
#0 25.31 Linking libtiff-4.5.1-h360e80f_0
#0 25.32 Linking openmpi-4.1.5-hd86f6cd_101
#0 25.65 WARNING: No ICDs were found. Either,
#0 25.65 - Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or 
#0 25.65 - Make your system-wide implementation visible by installing ocl-icd-system conda package. 
#0 25.65  
#0 25.65 For Linux 64, Open MPI is built with CUDA awareness but this support is disabled by default.
#0 25.65 To enable it, please set the environment variable OMPI_MCA_opal_cuda_support=true before
#0 25.65 launching your MPI processes. Equivalently, you can set the MCA parameter in the command line:
#0 25.65 mpiexec --mca opal_cuda_support 1 ...
#0 25.65  
#0 25.65 In addition, the UCX support is also built but disabled by default.
#0 25.65 To enable it, first install UCX (conda install -c conda-forge ucx). Then, set the environment
#0 25.65 variables OMPI_MCA_pml="ucx" OMPI_MCA_osc="ucx" before launching your MPI processes.
#0 25.65 Equivalently, you can set the MCA parameters in the command line:
#0 25.65 mpiexec --mca pml ucx --mca osc ucx ...
#0 25.65 Note that you might also need to set UCX_MEMTYPE_CACHE=n for CUDA awareness via UCX.
#0 25.65 Please consult UCX's documentation for detail.
#0 25.65  
#0 25.65 
#0 25.65 Linking nss-3.89-hf608148_0
#0 25.66 Linking freetype-2.12.1-hbbbf32d_1
...
#0 30.28 Linking silx-1.1.2-hd8ed1ab_2
#0 30.28 Linking pyfai-2023.5.0-hd8ed1ab_1
#0 30.28 info     libmamba Waiting for pyc compilation to finish
#0 30.31 info     libmamba Opening history file: "/opt/conda/conda-meta/history"
#0 30.31 
#0 30.31 Transaction finished
#0 30.31 
#0 30.31 To activate this environment, use:
#0 30.31 
#0 30.31     micromamba activate base
#0 30.31 
#0 30.31 Or to execute a single command in this environment, use:
#0 30.31 
#0 30.31     micromamba run -n base mycommand
#0 30.31 
#0 30.31 error    libmamba Error opening for writing "/home/MILK/environments/mambafN71JJAYLkH": Permission denied
#0 30.31 error    libmamba Error opening for writing "/home/MILK/environments/mambafN71JJAYLkH": Permission denied
#0 30.31 
#0 30.31 Installing pip packages: -e ../, git+https://github.com/lanl/spotlight.git@v0.10.2, mystic==0.4.1, pyina>=0.2.8, pathos>=0.3.1
#0 30.31 info     libmamba Calling: /opt/conda/bin/python -m pip install -r /home/MILK/environments/mambafN71JJAYLkH --no-input
#0 30.59 WARNING: No ICDs were found. Either,
#0 30.59 - Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or 
#0 30.59 - Make your system-wide implementation visible by installing ocl-icd-system conda package. 
#0 30.83 ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/MILK/environments/mambafN71JJAYLkH'
#0 31.32 critical libmamba pip failed to install packages
------
Dockerfile:33
--------------------
  31 |     WORKDIR /home/MILK
  32 |     
  33 | >>> RUN micromamba install -v -y -n base -f environments/environment_linux_docker.yml
  34 |     
  35 |     # # Install MAUD
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -v -y -n base -f environments/environment_linux_docker.yml" did not complete successfully: exit code: 1
```

### environment.yml

```yaml
name: base

channels:
  - conda-forge
  
dependencies:
  #Base MILK
  - tqdm
  - pip=22.1.2
  - prettytable
  - python=3.9
  - pandas
  - pydantic
  - seaborn
  - pyfai
  - matplotlib
  - pyopencl
  - opencv
  - pyqtgraph
  - autopep8
  - git
  - pytest
  
  # Spotlight
  - klepto=0.2.2
  - numpy=1.23.0
  - openmpi
  - mpi4py
  - jupyter=1.0.0
  - nbsphinx=0.8.9
  - sphinx=5.0.2
  - sphinxcontrib-programoutput=0.16
  - scipy=1.8.1
  - scikit-learn=1.1.2

  # pip packages
  - pip:
    #MILK github installation
    - -e ../
    #Spotlight
    - git+https://github.com/lanl/spotlight.git@v0.10.2
    - mystic==0.4.1
    - pyina>=0.2.8
    - pathos>=0.3.1
```

### ~/.condarc

```yaml
(base) root@c2659fd100c1:/output# cat ~/.condarc
cat: /root/.condarc: No such file or directory
```

**Comment by wholtz** [comment]
There was another report of this in the [micromamba-docker issues](https://github.com/mamba-org/micromamba-docker/issues/356). I would like to see the location of the temporary requirements file follow how `mktemp` selects it's output directory.

**Comment by ZhangxiJesseFeng** [comment]
@wholtz thanks for getting back to me. How can I provide you those information?

**Comment by wholtz** [comment]
@ZhangxiJesseFeng  Do you really need to add a user to your image? I'd recommend avoiding it if you can. If you must, I suggest you read [our documentation on changing the user](https://micromamba-docker.readthedocs.io/en/latest/advanced_usage.html#changing-the-user-id-or-name).

I'm guessing you just need to make your `chown` recursive:

```
RUN chown -R newuser /home/MILK
```

and then the temporary file that `micromamba` is trying to create will be allowed.

**Comment by wholtz** [comment]
I'm probably missing something about your requirements or approach. 

I'd suggest trying something like:

```
FROM mambaorg/micromamba:1.4.9

ENV MAUD_PATH=/Maud
ENV CINEMA_PATH=/cinema
ENV HOME=/home/$MAMBA_USER

COPY --chown=$MAMBA_USER:$MAMBA_USER . $HOME/
WORKDIR $HOME

RUN micromamba install -v -y -n base -f "${HOME}/environments/environment_linux_docker.yml"
```

If that doesn't work for you, can you please explain how it fails to meet your requirements?

**Comment by ZhangxiJesseFeng** [comment]
@wholtz Ok this worked. Please allow me to recap my progress so far to make sure I understand what happened:

1. Initially, I installed mamba through conda and used a conda docker base to build everything. This no longer works.
2. Then I used mamba docker to build everything, but missed the part on assigning ownership to mamba_user.
3. With your suggested script, everything works.

So the key is mamba is no longer supported via conda install in docker? I am closing this issue now, but would appreciate if you could confirm the above.

Thanks!

Jesse
