### ISSUE TITLE
Issue when removing package

### ISSUE THREAD

**Issue by astrofrog** [mamba-org/mamba#2767]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

Tried searching for issues related to remove

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

I am running into an error when trying to remove a package with mamba. To reproduce, 

```bash
mamba create -n test
mamba activate test
mamba install glueviz
mamba remove glue-core
```

(this is with mambaforge so using conda-forge)

The error I get is included below. It's interesting that in addition to the error it appears to be trying to remove all packages from the environment, not just glue-core and packages that depend on it, but maybe this is expected?

I'm not able to try with ``conda`` as it's too slow to ever solve the environment in the first place.

### mamba info / micromamba info

```shell
$ mamba info

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : test
    active env location : /home/tom/mambaforge/envs/test
            shell level : 2
       user config file : /home/tom/.condarc
 populated config files : /home/tom/mambaforge/.condarc
                          /home/tom/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/tom/mambaforge  (writable)
      conda av data dir : /home/tom/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/tom/mambaforge/pkgs
                          /home/tom/.conda/pkgs
       envs directories : /home/tom/mambaforge/envs
                          /home/tom/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.31.0 CPython/3.10.12 Linux/6.2.0-26-generic ubuntu/22.04.3 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Logs

```shell
$ mamba remove glue-core

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Removing specs: ['glue-core']
Transaction

  Prefix: /home/tom/mambaforge/envs/test

  Removing specs:

   - glue-core


  Package                               Version  Build                    Channel         Size
────────────────────────────────────────────────────────────────────────────────────────────────
  Remove:
────────────────────────────────────────────────────────────────────────────────────────────────

  - __glibc                                2.35  0                        installed           
  - __linux                               6.2.0  0                        installed           
  - __unix                                    0  0                        installed           
  - _libgcc_mutex                           0.1  conda_forge              conda-forge         
  - _openmp_mutex                           4.5  2_gnu                    conda-forge         
  - alsa-lib                              1.2.9  hd590300_0               conda-forge         
  - aom                                   3.5.0  h27087fc_0               conda-forge         
  - astropy                               5.3.2  py311h1f0f07a_0          conda-forge         
  - asttokens                             2.2.1  pyhd8ed1ab_0             conda-forge         
  - attr                                  2.5.1  h166bdaf_1               conda-forge         
  - aws-c-auth                            0.7.3  h28f7589_1               conda-forge         
  - aws-c-cal                             0.6.1  hc309b26_1               conda-forge         
  - aws-c-common                          0.9.0  hd590300_0               conda-forge         
  - aws-c-compression                    0.2.17  h4d4d85c_2               conda-forge         
  - aws-c-event-stream                    0.3.1  h2e3709c_4               conda-forge         
  - aws-c-http                           0.7.11  h00aa349_4               conda-forge         
  - aws-c-io                            0.13.32  h4a1a131_0               conda-forge         
  - aws-c-mqtt                            0.9.3  hb447be9_1               conda-forge         
  - aws-c-s3                             0.3.14  hf3aad02_1               conda-forge         
  - aws-c-sdkutils                       0.1.12  h4d4d85c_1               conda-forge         
  - aws-checksums                        0.1.17  h4d4d85c_1               conda-forge         
  - aws-crt-cpp                          0.21.0  hb942446_5               conda-forge         
  - aws-sdk-cpp                         1.10.57  h85b1a90_19              conda-forge         
  - backcall                              0.2.0  pyh9f0ad1d_0             conda-forge         
  - backports                               1.0  pyhd8ed1ab_3             conda-forge         
  - backports.functools_lru_cache         1.6.5  pyhd8ed1ab_0             conda-forge         
  - blosc                                1.21.4  h0f2a231_0               conda-forge         
  - bokeh                                 3.2.2  pyhd8ed1ab_0             conda-forge         
  - bottleneck                            1.3.7  py311hcb2cf0a_0          conda-forge         
  - brotli                                1.0.9  h166bdaf_9               conda-forge         
  - brotli-bin                            1.0.9  h166bdaf_9               conda-forge         
  - brotli-python                         1.0.9  py311ha362b79_9          conda-forge         
  - brunsli                                 0.1  h9c3ff4c_0               conda-forge         
  - bzip2                                 1.0.8  h7f98852_4               conda-forge         
  - c-ares                               1.19.1  hd590300_0               conda-forge         
  - c-blosc2                             2.10.2  hb4ffafa_0               conda-forge         
  - ca-certificates                   2023.7.22  hbcca054_0               conda-forge         
  - cached-property                       1.5.2  hd8ed1ab_1               conda-forge         
  - cached_property                       1.5.2  pyha770c72_1             conda-forge         
  - cairo                                1.16.0  hbbf8b49_1016            conda-forge         
  - casa_formats_io                       0.2.1  py311h1f0f07a_1          conda-forge         
  - certifi                           2023.7.22  pyhd8ed1ab_0             conda-forge         
  - charls                                2.4.2  h59595ed_0               conda-forge         
  - charset-normalizer                    3.2.0  pyhd8ed1ab_0             conda-forge         
  - click                                 8.1.7  unix_pyh707e725_0        conda-forge         
  - cloudpickle                           2.2.1  pyhd8ed1ab_0             conda-forge         
  - comm                                  0.1.4  pyhd8ed1ab_0             conda-forge         
  - contourpy                             1.1.0  py311h9547e67_0          conda-forge         
  - cycler                               0.11.0  pyhd8ed1ab_0             conda-forge         
  - cytoolz                              0.12.2  py311h459d7ec_0          conda-forge         
  - dask                               2023.8.1  pyhd8ed1ab_0             conda-forge         
  - dask-core                          2023.8.1  pyhd8ed1ab_0             conda-forge         
  - dav1d                                 1.2.1  hd590300_0               conda-forge         
  - dbus                                 1.13.6  h5008d03_3               conda-forge         
  - debugpy                               1.6.8  py311hb755f60_0          conda-forge         
  - decorator                             5.1.1  pyhd8ed1ab_0             conda-forge         
  - dill                                  0.3.7  pyhd8ed1ab_0             conda-forge         
  - distributed                        2023.8.1  pyhd8ed1ab_0             conda-forge         
  - echo                                  0.8.0  pyhd8ed1ab_0             conda-forge         
  - et_xmlfile                            1.1.0  pyhd8ed1ab_0             conda-forge         
  - executing                             1.2.0  pyhd8ed1ab_0             conda-forge         
  - expat                                 2.5.0  hcb278e6_1               conda-forge         
  - fast-histogram                         0.11  py311h1f0f07a_1          conda-forge         
  - font-ttf-dejavu-sans-mono              2.37  hab24e00_0               conda-forge         
  - font-ttf-inconsolata                  3.000  h77eed37_0               conda-forge         
  - font-ttf-source-code-pro              2.038  h77eed37_0               conda-forge         
  - font-ttf-ubuntu                        0.83  hab24e00_0               conda-forge         
  - fontconfig                           2.14.2  h14ed4e7_0               conda-forge         
  - fonts-conda-ecosystem                     1  0                        conda-forge         
  - fonts-conda-forge                         1  0                        conda-forge         
  - fonttools                            4.42.1  py311h459d7ec_0          conda-forge         
  - freetype                             2.12.1  hca18f0e_1               conda-forge         
  - freetype-py                           2.4.0  pyhd8ed1ab_0             conda-forge         
  - fsspec                             2023.6.0  pyh1a96a4e_0             conda-forge         
  - gettext                              0.21.1  h27087fc_0               conda-forge         
  - gflags                                2.2.2  he1b5a44_1004            conda-forge         
  - giflib                                5.2.1  h0b41bf4_3               conda-forge         
  - glib                                 2.76.4  hfc55251_0               conda-forge         
  - glib-tools                           2.76.4  hfc55251_0               conda-forge         
  - glog                                  0.6.0  h6f12383_0               conda-forge         
  - glue-core                            1.12.0  py311h38be061_1          conda-forge         
  - glue-vispy-viewers                    1.0.7  pyhd8ed1ab_0             conda-forge         
  - glueviz                               1.2.0  py311h38be061_1          conda-forge         
  - graphite2                            1.3.13  h58526e2_1001            conda-forge         
  - gst-plugins-base                     1.22.5  hf7dbed1_0               conda-forge         
  - gstreamer                            1.22.5  h98fc4e7_0               conda-forge         
  - h5py                                  3.9.0  nompi_py311he78b9b8_101  conda-forge         
  - harfbuzz                              7.3.0  hdb3a94d_0               conda-forge         
  - hdf5                                 1.14.1  nompi_h4f84152_100       conda-forge         
  - hsluv                                 5.0.2  pyh44b312d_0             conda-forge         
  - icu                                    72.1  hcb278e6_0               conda-forge         
  - idna                                    3.4  pyhd8ed1ab_0             conda-forge         
  - imagecodecs                       2023.8.12  py311h67b54e4_0          conda-forge         
  - imageio                              2.31.1  pyh24c5eb1_0             conda-forge         
  - importlib-metadata                    6.8.0  pyha770c72_0             conda-forge         
  - importlib_metadata                    6.8.0  hd8ed1ab_0               conda-forge         
  - ipykernel                            6.25.1  pyh71e2992_0             conda-forge         
  - ipython                              8.14.0  pyh41d4057_0             conda-forge         
  - ipython_genutils                      0.2.0  py_1                     conda-forge         
  - jedi                                 0.19.0  pyhd8ed1ab_0             conda-forge         
  - jinja2                                3.1.2  pyhd8ed1ab_1             conda-forge         
  - joblib                                1.3.2  pyhd8ed1ab_0             conda-forge         
  - jupyter_client                        8.3.0  pyhd8ed1ab_0             conda-forge         
  - jupyter_core                          5.3.1  py311h38be061_0          conda-forge         
  - jxrlib                                  1.1  h7f98852_2               conda-forge         
  - keyutils                              1.6.1  h166bdaf_0               conda-forge         
  - kiwisolver                            1.4.4  py311h4dd048b_1          conda-forge         
  - krb5                                 1.21.2  h659d440_0               conda-forge         
  - lame                                  3.100  h166bdaf_1003            conda-forge         
  - lazy_loader                             0.3  pyhd8ed1ab_0             conda-forge         
  - lcms2                                  2.15  haa2dc70_1               conda-forge         
  - ld_impl_linux-64                       2.40  h41732ed_0               conda-forge         
  - lerc                                  4.0.0  h27087fc_0               conda-forge         
  - libabseil                        20230125.3  cxx17_h59595ed_0         conda-forge         
  - libaec                                1.0.6  hcb278e6_1               conda-forge         
  - libarrow                             12.0.1  h10ac928_8_cpu           conda-forge         
  - libavif                              0.11.1  h8182462_2               conda-forge         
  - libblas                               3.9.0  17_linux64_openblas      conda-forge         
  - libbrotlicommon                       1.0.9  h166bdaf_9               conda-forge         
  - libbrotlidec                          1.0.9  h166bdaf_9               conda-forge         
  - libbrotlienc                          1.0.9  h166bdaf_9               conda-forge         
  - libcap                                 2.69  h0f662aa_0               conda-forge         
  - libcblas                              3.9.0  17_linux64_openblas      conda-forge         
  - libclang                             15.0.7  default_h7634d5b_3       conda-forge         
  - libclang13                           15.0.7  default_h9986a30_3       conda-forge         
  - libcrc32c                             1.1.2  h9c3ff4c_0               conda-forge         
  - libcups                               2.3.3  h4637d8d_4               conda-forge         
  - libcurl                               8.2.1  hca28451_0               conda-forge         
  - libdeflate                             1.18  h0b41bf4_0               conda-forge         
  - libedit                        3.1.20191231  he28a2e2_2               conda-forge         
  - libev                                  4.33  h516909a_1               conda-forge         
  - libevent                             2.1.12  hf998b51_1               conda-forge         
  - libexpat                              2.5.0  hcb278e6_1               conda-forge         
  - libffi                                3.4.2  h7f98852_5               conda-forge         
  - libflac                               1.4.3  h59595ed_0               conda-forge         
  - libgcc-ng                            13.1.0  he5830b7_0               conda-forge         
  - libgcrypt                            1.10.1  h166bdaf_0               conda-forge         
  - libgfortran-ng                       13.1.0  h69a702a_0               conda-forge         
  - libgfortran5                         13.1.0  h15d22d2_0               conda-forge         
  - libglib                              2.76.4  hebfc3b9_0               conda-forge         
  - libgomp                              13.1.0  he5830b7_0               conda-forge         
  - libgoogle-cloud                      2.12.0  h840a212_1               conda-forge         
  - libgpg-error                           1.47  h71f35ed_0               conda-forge         
  - libgrpc                              1.56.2  h3905398_1               conda-forge         
  - libiconv                               1.17  h166bdaf_0               conda-forge         
  - libjpeg-turbo                       2.1.5.1  h0b41bf4_0               conda-forge         
  - liblapack                             3.9.0  17_linux64_openblas      conda-forge         
  - libllvm15                            15.0.7  h5cf9203_3               conda-forge         
  - libnghttp2                           1.52.0  h61bc06f_0               conda-forge         
  - libnsl                                2.0.0  h7f98852_0               conda-forge         
  - libnuma                              2.0.16  h0b41bf4_1               conda-forge         
  - libogg                                1.3.4  h7f98852_1               conda-forge         
  - libopenblas                          0.3.23  pthreads_h80387f5_0      conda-forge         
  - libopus                               1.3.1  h7f98852_1               conda-forge         
  - libpng                               1.6.39  h753d276_0               conda-forge         
  - libpq                                  15.4  hfc447b1_0               conda-forge         
  - libprotobuf                          4.23.3  hd1fb520_0               conda-forge         
  - libsndfile                            1.2.2  hbc2eb40_0               conda-forge         
  - libsodium                            1.0.18  h36c2ea0_1               conda-forge         
  - libsqlite                            3.42.0  h2797004_0               conda-forge         
  - libssh2                              1.11.0  h0841786_0               conda-forge         
  - libstdcxx-ng                         13.1.0  hfd8a6a1_0               conda-forge         
  - libsystemd0                             254  h3516f8a_0               conda-forge         
  - libthrift                            0.18.1  h8fd135c_2               conda-forge         
  - libtiff                               4.5.1  h8b53f26_0               conda-forge         
  - libutf8proc                           2.8.0  h166bdaf_0               conda-forge         
  - libuuid                              2.38.1  h0b41bf4_0               conda-forge         
  - libvorbis                             1.3.7  h9c3ff4c_0               conda-forge         
  - libwebp-base                          1.3.1  hd590300_0               conda-forge         
  - libxcb                                 1.15  h0b41bf4_0               conda-forge         
  - libxkbcommon                          1.5.0  h5d7e998_3               conda-forge         
  - libxml2                              2.11.5  h0d562d8_0               conda-forge         
  - libzlib                              1.2.13  hd590300_5               conda-forge         
  - libzopfli                             1.0.3  h9c3ff4c_0               conda-forge         
  - locket                                1.0.0  pyhd8ed1ab_0             conda-forge         
  - lz4                                   4.3.2  py311h9f220a4_0          conda-forge         
  - lz4-c                                 1.9.4  hcb278e6_0               conda-forge         
  - markupsafe                            2.1.3  py311h459d7ec_0          conda-forge         
  - matplotlib-base                       3.7.2  py311h54ef318_0          conda-forge         
  - matplotlib-inline                     0.1.6  pyhd8ed1ab_0             conda-forge         
  - mpg123                               1.31.3  hcb278e6_0               conda-forge         
  - mpl-scatter-density                     0.7  pyhd8ed1ab_0             conda-forge         
  - msgpack-python                        1.0.5  py311ha3edf6b_0          conda-forge         
  - munkres                               1.1.4  pyh9f0ad1d_0             conda-forge         
  - mysql-common                         8.0.33  hf1915f5_2               conda-forge         
  - mysql-libs                           8.0.33  hca2cd23_2               conda-forge         
  - ncurses                                 6.4  hcb278e6_0               conda-forge         
  - nest-asyncio                          1.5.6  pyhd8ed1ab_0             conda-forge         
  - networkx                                3.1  pyhd8ed1ab_0             conda-forge         
  - nspr                                   4.35  h27087fc_0               conda-forge         
  - nss                                    3.89  he45b914_0               conda-forge         
  - numpy                                1.25.2  py311h64a7726_0          conda-forge         
  - openjpeg                              2.5.0  hfec8fc6_2               conda-forge         
  - openpyxl                              3.1.2  py311h459d7ec_0          conda-forge         
  - openssl                               3.1.2  hd590300_0               conda-forge         
  - orc                                   1.9.0  h385abfd_1               conda-forge         
  - packaging                              23.1  pyhd8ed1ab_0             conda-forge         
  - pandas                                2.0.3  py311h320fe9a_1          conda-forge         
  - parso                                 0.8.3  pyhd8ed1ab_0             conda-forge         
  - partd                                 1.4.0  pyhd8ed1ab_0             conda-forge         
  - pcre2                                 10.40  hc3806b6_0               conda-forge         
  - pexpect                               4.8.0  pyh1a96a4e_2             conda-forge         
  - pickleshare                           0.7.5  py_1003                  conda-forge         
  - pillow                               10.0.0  py311h0b84326_0          conda-forge         
  - pip                                  23.2.1  pyhd8ed1ab_0             conda-forge         
  - pixman                               0.40.0  h36c2ea0_0               conda-forge         
  - platformdirs                         3.10.0  pyhd8ed1ab_0             conda-forge         
  - ply                                    3.11  py_1                     conda-forge         
  - pooch                                 1.7.0  pyha770c72_3             conda-forge         
  - prompt-toolkit                       3.0.39  pyha770c72_0             conda-forge         
  - prompt_toolkit                       3.0.39  hd8ed1ab_0               conda-forge         
  - psutil                                5.9.5  py311h2582759_0          conda-forge         
  - pthread-stubs                           0.4  h36c2ea0_1001            conda-forge         
  - ptyprocess                            0.7.0  pyhd3deb0d_0             conda-forge         
  - pulseaudio-client                      16.1  hb77b528_4               conda-forge         
  - pure_eval                             0.2.2  pyhd8ed1ab_0             conda-forge         
  - pvextractor                             0.3  pyhd8ed1ab_0             conda-forge         
  - pyarrow                              12.0.1  py311h39c9aba_8_cpu      conda-forge         
  - pyerfa                              2.0.0.3  py311h1f0f07a_0          conda-forge         
  - pygments                             2.16.1  pyhd8ed1ab_0             conda-forge         
  - pyopengl                              3.1.6  pyhd8ed1ab_1             conda-forge         
  - pyparsing                             3.0.9  pyhd8ed1ab_0             conda-forge         
  - pyqt                                 5.15.9  py311hf0fb5b6_4          conda-forge         
  - pyqt5-sip                           12.12.2  py311hb755f60_4          conda-forge         
  - pysocks                               1.7.1  pyha2e5f31_6             conda-forge         
  - python                               3.11.4  hab00c5b_0_cpython       conda-forge         
  - python-dateutil                       2.8.2  pyhd8ed1ab_0             conda-forge         
  - python-tzdata                        2023.3  pyhd8ed1ab_0             conda-forge         
  - python_abi                             3.11  3_cp311                  conda-forge         
  - pytz                                 2023.3  pyhd8ed1ab_0             conda-forge         
  - pywavelets                            1.4.1  py311hcb2cf0a_0          conda-forge         
  - pyyaml                                  6.0  py311hd4cff14_5          conda-forge         
  - pyzmq                                25.1.1  py311h75c88c4_0          conda-forge         
  - qt-main                              5.15.8  h7fe3ca9_15              conda-forge         
  - qtconsole                             5.4.3  pyhd8ed1ab_0             conda-forge         
  - qtconsole-base                        5.4.3  pyha770c72_0             conda-forge         
  - qtpy                                  2.3.1  pyhd8ed1ab_0             conda-forge         
  - radio-beam                            0.3.4  pyhd8ed1ab_0             conda-forge         
  - rdma-core                              28.9  h59595ed_1               conda-forge         
  - re2                              2023.03.02  h8c504da_0               conda-forge         
  - readline                                8.2  h8228510_1               conda-forge         
  - requests                             2.31.0  pyhd8ed1ab_0             conda-forge         
  - s2n                                  1.3.48  h06160fa_0               conda-forge         
  - scikit-image                         0.21.0  py311hb755f60_0          conda-forge         
  - scipy                                1.11.2  py311h64a7726_0          conda-forge         
  - setuptools                           68.1.2  pyhd8ed1ab_0             conda-forge         
  - sip                                  6.7.11  py311hb755f60_0          conda-forge         
  - six                                  1.16.0  pyh6c4a22f_0             conda-forge         
  - snappy                               1.1.10  h9fff704_0               conda-forge         
  - sortedcontainers                      2.4.0  pyhd8ed1ab_0             conda-forge         
  - spectral-cube                         0.6.2  pyhd8ed1ab_0             conda-forge         
  - stack_data                            0.6.2  pyhd8ed1ab_0             conda-forge         
  - tblib                                 1.7.0  pyhd8ed1ab_0             conda-forge         
  - tifffile                          2023.8.12  pyhd8ed1ab_1             conda-forge         
  - tk                                   8.6.12  h27826a3_0               conda-forge         
  - toml                                 0.10.2  pyhd8ed1ab_0             conda-forge         
  - tomli                                 2.0.1  pyhd8ed1ab_0             conda-forge         
  - toolz                                0.12.0  pyhd8ed1ab_0             conda-forge         
  - tornado                               6.3.3  py311h459d7ec_0          conda-forge         
  - traitlets                             5.9.0  pyhd8ed1ab_0             conda-forge         
  - typing-extensions                     4.7.1  hd8ed1ab_0               conda-forge         
  - typing_extensions                     4.7.1  pyha770c72_0             conda-forge         
  - tzdata                                2023c  h71feb2d_0               conda-forge         
  - ucx                                  1.14.1  h4a2ce2d_3               conda-forge         
  - urllib3                               2.0.4  pyhd8ed1ab_0             conda-forge         
  - vispy                                0.13.0  py311h40e7361_0          conda-forge         
  - wcwidth                               0.2.6  pyhd8ed1ab_0             conda-forge         
  - wheel                                0.41.1  pyhd8ed1ab_0             conda-forge         
  - xcb-util                              0.4.0  hd590300_1               conda-forge         
  - xcb-util-image                        0.4.0  h8ee46fc_1               conda-forge         
  - xcb-util-keysyms                      0.4.0  h8ee46fc_1               conda-forge         
  - xcb-util-renderutil                   0.3.9  hd590300_1               conda-forge         
  - xcb-util-wm                           0.4.1  h8ee46fc_1               conda-forge         
  - xkeyboard-config                       2.39  hd590300_0               conda-forge         
  - xlrd                                  2.0.1  pyhd8ed1ab_3             conda-forge         
  - xorg-kbproto                          1.0.7  h7f98852_1002            conda-forge         
  - xorg-libice                           1.1.1  hd590300_0               conda-forge         
  - xorg-libsm                            1.2.4  h7391055_0               conda-forge         
  - xorg-libx11                           1.8.6  h8ee46fc_0               conda-forge         
  - xorg-libxau                          1.0.11  hd590300_0               conda-forge         
  - xorg-libxdmcp                         1.1.3  h7f98852_0               conda-forge         
  - xorg-libxext                          1.3.4  h0b41bf4_2               conda-forge         
  - xorg-libxrender                      0.9.11  hd590300_0               conda-forge         
  - xorg-renderproto                     0.11.1  h7f98852_1002            conda-forge         
  - xorg-xextproto                        7.3.0  h0b41bf4_1003            conda-forge         
  - xorg-xf86vidmodeproto                 2.3.1  h7f98852_1002            conda-forge         
  - xorg-xproto                          7.0.31  h7f98852_1007            conda-forge         
  - xyzservices                        2023.7.0  pyhd8ed1ab_0             conda-forge         
  - xz                                    5.2.6  h166bdaf_0               conda-forge         
  - yaml                                  0.2.5  h7f98852_2               conda-forge         
  - zeromq                                4.3.4  h9c3ff4c_1               conda-forge         
  - zfp                                   1.0.0  h27087fc_3               conda-forge         
  - zict                                  3.0.0  pyhd8ed1ab_0             conda-forge         
  - zipp                                 3.16.2  pyhd8ed1ab_0             conda-forge         
  - zlib                                 1.2.13  hd590300_5               conda-forge         
  - zlib-ng                               2.0.7  h0b41bf4_0               conda-forge         
  - zstd                                  1.5.2  hfc55251_7               conda-forge         

  Summary:

  Remove: 297 packages

  Total download: 0 B

────────────────────────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] 
PackageRecord(_hash=-723053267294325033, name='__linux', version='6.2.0', build='0', build_number=0, channel=Channel("@"), subdir='linux-64', fn='__linux', md5='12345678901234567890123456789012', package_type='virtual_system')

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/tom/mambaforge/lib/python3.10/site-packages/conda/_vendor/boltons/setutils.py", line 247, in remove
        didx = self.item_index_map.pop(item)
    KeyError: PackageRecord(_hash=-723053267294325033, name='__linux', version='6.2.0', build='0', build_number=0, channel=Channel("@"), subdir='linux-64', fn='__linux', md5='12345678901234567890123456789012', package_type='virtual_system')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/tom/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/tom/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/tom/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/tom/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/tom/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 756, in do_call
        exit_code = remove(args, parser)
      File "/home/tom/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 240, in remove
        conda_transaction = to_txn(
      File "/home/tom/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 447, in to_txn
        final_precs = compute_final_precs(
      File "/home/tom/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 373, in compute_final_precs
        final_precs.remove(i_rec)
      File "/home/tom/mambaforge/lib/python3.10/site-packages/conda/_vendor/boltons/setutils.py", line 249, in remove
        raise KeyError(item)
    KeyError: PackageRecord(_hash=-723053267294325033, name='__linux', version='6.2.0', build='0', build_number=0, channel=Channel("@"), subdir='linux-64', fn='__linux', md5='12345678901234567890123456789012', package_type='virtual_system')

`$ /home/tom/mambaforge/bin/mamba remove glue-core`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=test
                CONDA_EXE=/home/tom/mambaforge/bin/conda
             CONDA_PREFIX=/home/tom/mambaforge/envs/test
           CONDA_PREFIX_1=/home/tom/mambaforge/envs/glue-env
    CONDA_PROMPT_MODIFIER=(test)
         CONDA_PYTHON_EXE=/home/tom/mambaforge/bin/python
               CONDA_ROOT=/home/tom/mambaforge
              CONDA_SHLVL=2
                CRDS_PATH=/home/tom/crds_cache
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/tom/mambaforge/envs/test/bin:/home/tom/mambaforge/condabin:/usr/
                          lib/ccache:/home/tom/usr/bin:/home/tom/bin:/home/tom/.cargo/bin:/home/
                          tom/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : test
    active env location : /home/tom/mambaforge/envs/test
            shell level : 2
       user config file : /home/tom/.condarc
 populated config files : /home/tom/mambaforge/.condarc
                          /home/tom/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/tom/mambaforge  (writable)
      conda av data dir : /home/tom/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/tom/mambaforge/pkgs
                          /home/tom/.conda/pkgs
       envs directories : /home/tom/mambaforge/envs
                          /home/tom/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.31.0 CPython/3.10.12 Linux/6.2.0-26-generic ubuntu/22.04.3 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

### ~/.condarc

```yaml
auto_activate_base: false
```

**Comment by jonashaag** [comment]
Dupe of https://github.com/mamba-org/mamba/issues/1770
