### ISSUE TITLE
Multi-download failed. Reason: Transfer finalized, status: 404

### ISSUE THREAD

**Issue by nick-youngblut** [mamba-org/mamba#2788]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

Transfer finalized, status: 404; status: 404

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

mamba fails (reproducibly) to create a simple python env:

```
$ mamba create -n reflex python=3.9 pip

Looking for: ['python=3.9', 'pip']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache
pytorch/osx-arm64                                           Using cache
pytorch/noarch                                              Using cache
pkgs/main/osx-arm64                                           No change
pkgs/main/noarch                                              No change
pkgs/r/osx-arm64                                              No change
pkgs/r/noarch                                                 No change
warning  libmamba Package tarball '/Users/nickyoungblut/mambaforge/pkgs/libsqlite-3.43.0-hb31c410_0.conda' is invalid
warning  libmamba Extracted package cache '/Users/nickyoungblut/mambaforge/pkgs/openssl-3.1.2-h53f4e23_0' has invalid 'repodata_record.json' file: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
warning  libmamba Package tarball '/Users/nickyoungblut/mambaforge/pkgs/python-3.9.16-hea58f1e_0_cpython.conda' is invalid
warning  libmamba Package tarball '/Users/nickyoungblut/mambaforge/pkgs/wheel-0.41.2-pyhd8ed1ab_0.conda' is invalid
Transaction

  Prefix: /Users/nickyoungblut/mambaforge/envs/reflex

  Updating specs:

   - python=3.9
   - pip


  Package              Version  Build               Channel           Size
────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────

  + libffi               3.4.2  h3422bc3_5          conda-forge     Cached
  + libzlib             1.2.13  h53f4e23_5          conda-forge     Cached
  + ncurses                6.4  h7ea286d_0          conda-forge     Cached
  + xz                   5.2.6  h57fd34a_0          conda-forge     Cached
  + ca-certificates  2023.7.22  hf0a4a13_0          conda-forge     Cached
  + bzip2                1.0.8  h3422bc3_4          conda-forge     Cached
  + tk                  8.6.12  he1e0b03_0          conda-forge     Cached
  + libsqlite           3.43.0  hb31c410_0          conda-forge      834kB
  + readline               8.2  h92ec313_1          conda-forge     Cached
  + openssl              3.1.2  h53f4e23_0          conda-forge     Cached
  + tzdata               2023c  h71feb2d_0          conda-forge     Cached
  + python              3.9.16  hea58f1e_0_cpython  conda-forge       11MB
  + wheel               0.41.2  pyhd8ed1ab_0        conda-forge       57kB
  + setuptools          68.1.2  pyhd8ed1ab_0        conda-forge     Cached
  + pip                 23.2.1  pyhd8ed1ab_0        conda-forge     Cached

  Summary:

  Install: 15 packages

  Total download: 12MB

────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n]
[+] 0.1s
Downloading  (3) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /  12.0MB libsqlite                  0.1s
Extracting   (6) ━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━       0 /       9 ncurses                    0.1s
python                                             964.0 B @   9.8kB/s  0.1s
Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/python-3.9.16-hea58f1e_0_cpython.conda] 964 bytes

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 945, in exception_converter
        raise e
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 938, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 884, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 760, in do_call
        exit_code = create(args, parser)
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 601, in create
        return install(args, parser, "create")
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 557, in install
        transaction.fetch_extract_packages()
    RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/python-3.9.16-hea58f1e_0_cpython.conda] 964 bytes

`$ /Users/nickyoungblut/mambaforge/bin/mamba create -n reflex python=3.9 pip`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/nickyoungblut/mambaforge/bin/conda
             CONDA_PREFIX=/Users/nickyoungblut/mambaforge
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/nickyoungblut/mambaforge/bin/python
               CONDA_ROOT=/Users/nickyoungblut/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/opt/homebrew/bin:/Users/nickyoungblut/mambaforge/bin:/Users/nickyoung
                          blut/mambaforge/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:
                          /usr/bin:/bin:/usr/sbin:/sbin:/Applications/Privileges.app/Contents/Re
                          sources:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/us
                          r/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstra
                          p/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/
                          usr/appleinternal/bin:/Users/nickyoungblut/.fig/bin:/Users/nickyoungbl
                          ut/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nickyoungblu
                          t/.cargo/bin:/Users/nickyoungblut/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/nickyoungblut/mambaforge
            shell level : 1
       user config file : /Users/nickyoungblut/.condarc
 populated config files : /Users/nickyoungblut/mambaforge/.condarc
                          /Users/nickyoungblut/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.3=0
                          __unix=0=0
       base environment : /Users/nickyoungblut/mambaforge  (writable)
      conda av data dir : /Users/nickyoungblut/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/pytorch/osx-arm64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/nickyoungblut/mambaforge/pkgs
                          /Users/nickyoungblut/.conda/pkgs
       envs directories : /Users/nickyoungblut/mambaforge/envs
                          /Users/nickyoungblut/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/22.4.0 OSX/13.3
                UID:GID : 502:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

��"��X2-pyhd8ed1ab_0.conda extraction failed
```

...while conda creates the environment without issue:

```
$ conda create -n reflex python=3.9 pip
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.7.3

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.3



## Package Plan ##

  environment location: /Users/nickyoungblut/mambaforge/envs/reflex

  added / updated specs:
    - pip
    - python=3.9


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libsqlite-3.43.0           |       hb31c410_0         815 KB  conda-forge
    ncurses-6.4                |       h7ea286d_0         780 KB  conda-forge
    pip-23.2.1                 |     pyhd8ed1ab_0         1.3 MB  conda-forge
    python-3.9.16              |hea58f1e_0_cpython        10.6 MB  conda-forge
    tzdata-2023c               |       h71feb2d_0         115 KB  conda-forge
    wheel-0.41.2               |     pyhd8ed1ab_0          56 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        13.7 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h3422bc3_4
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2023.7.22-hf0a4a13_0
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5
  libsqlite          conda-forge/osx-arm64::libsqlite-3.43.0-hb31c410_0
  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-h53f4e23_5
  ncurses            conda-forge/osx-arm64::ncurses-6.4-h7ea286d_0
  openssl            conda-forge/osx-arm64::openssl-3.1.2-h53f4e23_0
  pip                conda-forge/noarch::pip-23.2.1-pyhd8ed1ab_0
  python             conda-forge/osx-arm64::python-3.9.16-hea58f1e_0_cpython
  readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1
  setuptools         conda-forge/noarch::setuptools-68.1.2-pyhd8ed1ab_0
  tk                 conda-forge/osx-arm64::tk-8.6.12-he1e0b03_0
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0
  wheel              conda-forge/noarch::wheel-0.41.2-pyhd8ed1ab_0
  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0


Proceed ([y]/n)?


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate reflex
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

### mamba info / micromamba info

```shell
mamba version : 1.5.0
     active environment : base
    active env location : /Users/nickyoungblut/mambaforge
            shell level : 1
       user config file : /Users/nickyoungblut/.condarc
 populated config files : /Users/nickyoungblut/mambaforge/.condarc
                          /Users/nickyoungblut/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.3=0
                          __unix=0=0
       base environment : /Users/nickyoungblut/mambaforge  (writable)
      conda av data dir : /Users/nickyoungblut/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/pytorch/osx-arm64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/nickyoungblut/mambaforge/pkgs
                          /Users/nickyoungblut/.conda/pkgs
       envs directories : /Users/nickyoungblut/mambaforge/envs
                          /Users/nickyoungblut/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/22.4.0 OSX/13.3
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

conda info:

```
    active environment : base
    active env location : /Users/nickyoungblut/mambaforge
            shell level : 1
       user config file : /Users/nickyoungblut/.condarc
 populated config files : /Users/nickyoungblut/mambaforge/.condarc
                          /Users/nickyoungblut/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.3=0
                          __unix=0=0
       base environment : /Users/nickyoungblut/mambaforge  (writable)
      conda av data dir : /Users/nickyoungblut/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/pytorch/osx-arm64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/nickyoungblut/mambaforge/pkgs
                          /Users/nickyoungblut/.conda/pkgs
       envs directories : /Users/nickyoungblut/mambaforge/envs
                          /Users/nickyoungblut/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/22.4.0 OSX/13.3
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
```


### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

```yaml
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
```

**Comment by jonashaag** [comment]
Ouch. I wonder if this is caused by #2300

Btw as you have seen in the Troubleshooting guide it is not supported to use the default channels with conda-forge. But I guess that's unrelated.

**Comment by wolfv** [comment]
Hmm, it seems that the `subdir` is missing in this URL:

`https://conda.anaconda.org/conda-forge/python-3.9.16-hea58f1e_0_cpython.conda`

**Comment by pxLi** [comment]
we saw similar issue
```
[2023-08-27T06:59:40.615Z] error    libmamba Failed to download package from https://conda.anaconda.org/conda-forge/ncurses-6.4-hcb278e6_0.conda (status 404)
[2023-08-27T06:59:40.615Z] 
[2023-08-27T06:59:40.615Z] Looking for: ['cuml=23.08', 'python=3.9', 'cuda-version=11.5']
[2023-08-27T06:59:40.615Z] 
[2023-08-27T06:59:40.615Z] Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/ncurses-6.4-hcb278e6_0.conda] 954 bytes
[2023-08-27T06:59:40.615Z] 
[2023-08-27T06:59:40.615Z] # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
[2023-08-27T06:59:40.615Z] 
[2023-08-27T06:59:40.615Z]     Traceback (most recent call last):
[2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/conda/exception_handler.py", line 16, in __call__
[2023-08-27T06:59:40.615Z]         return func(*args, **kwargs)
[2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 926, in exception_converter
[2023-08-27T06:59:40.615Z]         raise e
[2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 919, in exception_converter
[2023-08-27T06:59:40.615Z]         exit_code = _wrapped_main(*args, **kwargs)
[2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 877, in _wrapped_main
[2023-08-27T06:59:40.615Z]         result = do_call(parsed_args, p)
[2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 748, in do_call
[2023-08-27T06:59:40.615Z]         exit_code = install(args, parser, "install")
[2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 557, in install
[2023-08-27T06:59:40.615Z]         transaction.fetch_extract_packages()
[2023-08-27T06:59:40.615Z]     RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/ncurses-6.4-hcb278e6_0.conda] 954 bytes
[2023-08-27T06:59:40.615Z] 
[2023-08-27T06:59:40.615Z] `$ /root/miniconda3/bin/mamba install -y -c rapidsai -c conda-forge -c nvidia cuml=23.08 python=3.9 cuda-version=11.5`
```

and others
```
#0 467.2 error    libmamba Failed to download package from https://conda.anaconda.org/conda-forge/dlpack-0.5-h9c3ff4c_0.tar.bz2 (status 404)
#0 467.4 Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/dlpack-0.5-h9c3ff4c_0.tar.bz2] 955 bytes
```

our ENV are on mamba 1.4.9

**Comment by AntoinePrv** [comment]
I cannot reproduce this locally. Can you try thrashing `/Users/nickyoungblut/mambaforge/pkgs`?

**Comment by nick-youngblut** [comment]
@AntoinePrv now I cannot reproduce the error. Although the error was reproducible, I guess that that the 404 error was due to something beyond the setup on my machine.

**Comment by pxLi** [comment]
> we saw similar issue which missed subdir in URL
> 
> ```
> [2023-08-27T06:59:40.615Z] error    libmamba Failed to download package from https://conda.anaconda.org/conda-forge/ncurses-6.4-hcb278e6_0.conda (status 404)
> [2023-08-27T06:59:40.615Z] 
> [2023-08-27T06:59:40.615Z] Looking for: ['cuml=23.08', 'python=3.9', 'cuda-version=11.5']
> [2023-08-27T06:59:40.615Z] 
> [2023-08-27T06:59:40.615Z] Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/ncurses-6.4-hcb278e6_0.conda] 954 bytes
> [2023-08-27T06:59:40.615Z] 
> [2023-08-27T06:59:40.615Z] # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> [2023-08-27T06:59:40.615Z] 
> [2023-08-27T06:59:40.615Z]     Traceback (most recent call last):
> [2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/conda/exception_handler.py", line 16, in __call__
> [2023-08-27T06:59:40.615Z]         return func(*args, **kwargs)
> [2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 926, in exception_converter
> [2023-08-27T06:59:40.615Z]         raise e
> [2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 919, in exception_converter
> [2023-08-27T06:59:40.615Z]         exit_code = _wrapped_main(*args, **kwargs)
> [2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 877, in _wrapped_main
> [2023-08-27T06:59:40.615Z]         result = do_call(parsed_args, p)
> [2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 748, in do_call
> [2023-08-27T06:59:40.615Z]         exit_code = install(args, parser, "install")
> [2023-08-27T06:59:40.615Z]       File "/root/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 557, in install
> [2023-08-27T06:59:40.615Z]         transaction.fetch_extract_packages()
> [2023-08-27T06:59:40.615Z]     RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/ncurses-6.4-hcb278e6_0.conda] 954 bytes
> [2023-08-27T06:59:40.615Z] 
> [2023-08-27T06:59:40.615Z] `$ /root/miniconda3/bin/mamba install -y -c rapidsai -c conda-forge -c nvidia cuml=23.08 python=3.9 cuda-version=11.5`
> ```
> 
> and others
> 
> ```
> #0 467.2 error    libmamba Failed to download package from https://conda.anaconda.org/conda-forge/dlpack-0.5-h9c3ff4c_0.tar.bz2 (status 404)
> #0 467.4 Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/dlpack-0.5-h9c3ff4c_0.tar.bz2] 955 bytes
> ```
> 
> BTW our ENV are on mamba 1.4.9, conda 23.5.2

bump up mamba to 1.5.0 resolved our issue, seems there is some incompatible between the elder mamba version (1.4.9 in our case) vs newer conda (23.5.2).

**Comment by nick-youngblut** [comment]
> bump up mamba to 1.5.0 resolved our issue, seems there is some incompatible between the elder mamba version (1.4.9 in our case) vs newer conda (23.5.2).

@pxLi updating mamba did not help for me:

```
$ mamba --version
mamba 1.5.1
conda 23.7.3
```

```
$ mamba create -n py39 python=3.9 pip

Looking for: ['python=3.9', 'pip']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache
pytorch/osx-arm64                                           Using cache
pytorch/noarch                                              Using cache
pkgs/main/osx-arm64                                         Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/osx-arm64                                            Using cache
pkgs/r/noarch                                               Using cache
warning  libmamba Package tarball '/Users/nickyoungblut/mambaforge/pkgs/python-3.9.18-hfa1ae8a_0_cpython.conda' is invalid
Transaction

  Prefix: /Users/nickyoungblut/mambaforge/envs/py39

  Updating specs:

   - python=3.9
   - pip


  Package              Version  Build               Channel           Size
────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────

  + libffi               3.4.2  h3422bc3_5          conda-forge     Cached
  + libzlib             1.2.13  h53f4e23_5          conda-forge     Cached
  + xz                   5.2.6  h57fd34a_0          conda-forge     Cached
  + ncurses                6.4  h7ea286d_0          conda-forge     Cached
  + ca-certificates  2023.7.22  hf0a4a13_0          conda-forge     Cached
  + bzip2                1.0.8  h3422bc3_4          conda-forge     Cached
  + tk                  8.6.12  he1e0b03_0          conda-forge     Cached
  + libsqlite           3.43.0  hb31c410_0          conda-forge     Cached
  + readline               8.2  h92ec313_1          conda-forge     Cached
  + openssl              3.1.2  h53f4e23_0          conda-forge     Cached
  + tzdata               2023c  h71feb2d_0          conda-forge     Cached
  + python              3.9.18  hfa1ae8a_0_cpython  conda-forge       11MB
  + wheel               0.41.2  pyhd8ed1ab_0        conda-forge     Cached
  + setuptools          68.1.2  pyhd8ed1ab_0        conda-forge     Cached
  + pip                 23.2.1  pyhd8ed1ab_0        conda-forge     Cached

  Summary:

  Install: 15 packages

  Total download: 11MB

────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n]
[+] 0.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /  11.1MB                            0.0s
Extracting   (4) ━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━       0 /       5 ncurses                    0.0s
python                                             964.0 B @  11.8kB/s  0.1s
Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/python-3.9.18-hfa1ae8a_0_cpython.conda] 964 bytes

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 945, in exception_converter
        raise e
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 938, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 884, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 760, in do_call
        exit_code = create(args, parser)
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 601, in create
        return install(args, parser, "create")
      File "/Users/nickyoungblut/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 557, in install
        transaction.fetch_extract_packages()
    RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/python-3.9.18-hfa1ae8a_0_cpython.conda] 964 bytes

`$ /Users/nickyoungblut/mambaforge/bin/mamba create -n py39 python=3.9 pip`
```

**Comment by nick-youngblut** [comment]
> I cannot reproduce this locally. Can you try thrashing /Users/nickyoungblut/mambaforge/pkgs?

@AntoinePrv that worked. Thanks!
