### ISSUE TITLE
mamba build passes incorrect commandline on to boa

### ISSUE THREAD

**Issue by wence-** [mamba-org/mamba#2821]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

build

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

#2732 introduced special handling of `mamba build` (and `mamba env`). Unfortunately, the way `mamba build` is handled doesn't interface well with boa's `mambabuild.main()`.

```
$ mamba build path/to/recipe
Updating build index: /home/wence/Documents/apps/mambaforge/conda-bld

Glob /home/wence/Documents/src/rapids/cudf/build did not match in root_dir /home/wence/Documents/src/rapids/cudf
ERROR:conda_build.utils:Glob /home/wence/Documents/src/rapids/cudf/build did not match in root_dir /home/wence/Documents/src/rapids/cudf
Traceback (most recent call last):
  File "/home/wence/Documents/apps/mambaforge/bin/mamba", line 11, in <module>
    sys.exit(main())
  File "/home/wence/Documents/apps/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 928, in main
    return mambabuild.main()
  File "/home/wence/Documents/apps/mambaforge/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/home/wence/Documents/apps/mambaforge/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/home/wence/Documents/apps/mambaforge/lib/python3.10/site-packages/conda_build/api.py", line 249, in build
    raise ValueError(
ValueError: No valid recipes found for input: build
```

Whereas I expect this to build the provided recipe.

It looks like the problem is that boa's `mambabuild.main()` does this:
```python
def main():
    boa_config.is_mambabuild = True
    _, args = parse_args(sys.argv[1:])
```

So it expects that `sys.argv[0]` contains the executable name, and the rest contains the commandline.

When running `conda build path/to/recipe`, `sys.argv` is `["conda-mambabuild", "path/to/recipe"]`. However, when running `mamba build path/to/recipe` `sys.argv` is `["mamba", "build", "path/to/recipe"]`. Which then breaks the parser.

I suppose one should rewrite `sys.argv` before calling through to something like `["mamba-build", "path/to/recipe"]`.

### mamba info / micromamba info

```shell
mamba version : 1.5.1
     active environment : base
    active env location : /home/wence/Documents/apps/mambaforge
            shell level : 5
       user config file : /home/wence/.condarc
 populated config files : /home/wence/Documents/apps/mambaforge/.condarc
          conda version : 23.5.2
    conda-build version : 3.25.0
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/wence/Documents/apps/mambaforge  (writable)
      conda av data dir : /home/wence/Documents/apps/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/wence/Documents/apps/mambaforge/pkgs
                          /home/wence/.conda/pkgs
       envs directories : /home/wence/Documents/apps/mambaforge/envs
                          /home/wence/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.31.0 CPython/3.10.12 Linux/6.2.0-32-generic ubuntu/22.04.3 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by jakirkham** [comment]
cc @jaimergp (for awareness)

**Comment by kuepe-sl** [comment]
Are there any news on this?

It is still broken with:
- mamba 1.5.8
- boa 0.17.0
- conda 24.5.0
- conda-build 24.5.1

Just running `mamba mambabuild` already results in a failure

```
$ mamba mambabuild 
Unrecognized 'args' object: Namespace(verbosity=<conda.auxlib._Null object at 0x7ab94b6c7e20>, debug=<conda.auxlib._Null object at 0x7ab94b6c7e20>, trace=<conda.auxlib._Null object at 0x7ab94b6c7e20>, json=<conda.auxlib._Null object at 0x7ab94b6c7e20>, no_plugins=<conda.auxlib._Null object at 0x7ab94b6c7e20>, cmd='mambabuild', _executable='mambabuild', _args=())

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/miniconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 959, in exception_converter
        raise e
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 952, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 898, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/user/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 723, in do_call
        raise ValueError("Unrecognized 'args' object: %r" % args)
    ValueError: Unrecognized 'args' object: Namespace(verbosity=<conda.auxlib._Null object at 0x7ab94b6c7e20>, debug=<conda.auxlib._Null object at 0x7ab94b6c7e20>, trace=<conda.auxlib._Null object at 0x7ab94b6c7e20>, json=<conda.auxlib._Null object at 0x7ab94b6c7e20>, no_plugins=<conda.auxlib._Null object at 0x7ab94b6c7e20>, cmd='mambabuild', _executable='mambabuild', _args=())

`$ /home/user/miniconda3/bin/mamba mambabuild`
```

**Comment by jjerphan** [comment]
`mambabuild` does not exist and [`boa` has been deprecated and archived](https://github.com/mamba-org/boa), so this issue is not planned anymore now.

Feel free to comment or to reopen this issue if you still have some questions.
