### ISSUE TITLE
Upgrading to fmt 10.2.0 has broken mamba on Windows 11

### ISSUE THREAD

**Issue by owenlamont** [mamba-org/mamba#3095]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

I installed Miniconda originally then replaced all packages in my base environment with conda-forge versions and installed mamba from conda-forge (I only use Miniconda because I want the Powershell launcher on Windows which I can't get with Miniforge).

### Search tried in issue tracker

Yes I looked

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

Mamba was working fine for me, I updated my base environment and started getting DLL errors after updating fmt for all mamba commands:

```
Traceback (most recent call last):
  File "C:\Users\Owen\miniconda3\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Users\Owen\miniconda3\Lib\site-packages\mamba\mamba.py", line 44, in <module>
    import libmambapy as api
  File "C:\Users\Owen\miniconda3\Lib\site-packages\libmambapy\__init__.py", line 7, in <module>
    raise e
  File "C:\Users\Owen\miniconda3\Lib\site-packages\libmambapy\__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
```

These were the packages I updated in my base environment before mamba broke... but I determined fmt was the issue:

```
  Package       Version  Build         Channel           Size
---------------------------------------------------------------
  Upgrade:
---------------------------------------------------------------

  - setuptools   68.2.2  pyhd8ed1ab_0  conda-forge     Cached
  + setuptools   69.0.3  pyhd8ed1ab_0  conda-forge      471kB
  - grayskull     2.5.2  pyhd8ed1ab_0  conda-forge     Cached
  + grayskull     2.5.3  pyhd8ed1ab_0  conda-forge       87kB
  - fmt          10.1.1  h181d51b_1    conda-forge     Cached
  + fmt          10.2.0  h181d51b_0    conda-forge      185kB
```

I updated another Windows computer that didn't have grayskull installed (just setuptools and fmt) and ran into exactly the same problem. This dll problem has also partially broken conda (I can't downgrade fmt with conda using the default libmamba solver). I get these errors:

```
conda install  fmt=10.1.1 -c conda-forge
Error while loading conda entry point: conda-libmamba-solver (DLL load failed while importing bindings: The specified procedure could not be found.)
Retrieving notices: ...working... done

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
```

I was able to downgrade fmt with conda (after switching back to the classis solver):

```
conda install fmt=10.1.1 -c conda-forge --solver=classic
```

Once fmt was downgraded mamba appears to be working again. I originally suspected setuptools was the issue but I downgraded that first and it didn't fix the problem.

### mamba info / micromamba info

```shell
I can't run this as mamba is now broken, I'm using mamba version 1.5.6
```

### environment.yml

```yaml
# Name                    Version                   Build  Channel
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
argcomplete               3.2.1              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
blis                      0.9.0                hcfcfb64_1    conda-forge
boltons                   23.1.1             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py311h12c1d0e_1    conda-forge
brotlipy                  0.7.0           py311ha68e1ae_1006    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2023.11.17           h56e8100_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311ha68e1ae_0    conda-forge
chardet                   5.2.0           py311h1ea47a8_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
clang_variant             1.0                     default    conda-forge
clangdev                  5.0.0             h5aa907a_1012    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.11.0         py311h1ea47a8_1    conda-forge
conda-build               3.28.2          py311h1ea47a8_0    conda-forge
conda-content-trust       0.2.0              pyhd8ed1ab_0    conda-forge
conda-index               0.3.0              pyhd8ed1ab_1    conda-forge
conda-libmamba-solver     23.12.0            pyhd8ed1ab_0    conda-forge
conda-pack                0.7.1              pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
conda-souschef            2.2.3              pyhd8ed1ab_0    conda-forge
conda-verify              3.1.1           py311h1ea47a8_1006    conda-forge
console_shortcut          0.1.1                         4
cryptography              41.0.7          py311h7cb4080_1    conda-forge
distro                    1.8.0              pyhd8ed1ab_0    conda-forge
docutils                  0.20.1          py311h1ea47a8_3    conda-forge
doit                      0.36.0             pyhd8ed1ab_0    conda-forge
filelock                  3.13.1             pyhd8ed1ab_0    conda-forge
fmt                       10.2.0               h181d51b_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gh                        2.40.1               hd02998f_0    conda-forge
git                       2.43.0               h57928b3_0    conda-forge
glob2                     0.7                        py_0    conda-forge
grayskull                 2.5.3              pyhd8ed1ab_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.0.0         h57928b3_49840    conda-forge
jarowinkler               2.0.1              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py311h1ea47a8_3    conda-forge
jsonschema                4.20.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
libarchive                3.7.2                h6f8411a_0    conda-forge
libblas                   3.9.0             20_win64_blis    conda-forge
libcblas                  3.9.0             20_win64_blis    conda-forge
libcurl                   8.5.0                hd5e4a3a_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
liblief                   0.12.3               h63175ca_0    conda-forge
libmamba                  1.5.6                h3f09ed1_0    conda-forge
libmambapy                1.5.6           py311h0317a69_0    conda-forge
libopenblas               0.3.25          pthreads_hc140b1d_0    conda-forge
libsolv                   0.7.27               h12be248_0    conda-forge
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libxml2                   2.11.6               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
llvm-meta                 13.0.1               hd8ed1ab_0    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mamba                     1.5.6           py311h8cb466b_0    conda-forge
markupsafe                2.1.3           py311ha68e1ae_1    conda-forge
menuinst                  2.0.1           py311h12c1d0e_0    conda-forge
mkl                       2024.0.0         h66d3029_49657    conda-forge
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numpy                     1.26.2          py311h0b4df5a_0    conda-forge
openmp                    5.0.0                    vc14_0    conda-forge
openssl                   3.2.0                hcfcfb64_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pipx                      1.4.0              pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6              pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
powershell_shortcut       0.0.1                         3
progressbar2              4.3.2              pyhd8ed1ab_0    conda-forge
psutil                    5.9.7           py311ha68e1ae_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-lief                   0.12.3          py311h12c1d0e_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py311ha68e1ae_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyctdev                   0.7.0                      py_0    pyviz
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.3.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.11.7          h2628c8c_1_cpython    conda-forge
python-libarchive-c       5.0             py311h1ea47a8_2    conda-forge
python-utils              3.8.1              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pywin32                   306             py311h12c1d0e_2    conda-forge
pyyaml                    6.0.1           py311ha68e1ae_1    conda-forge
rapidfuzz                 3.6.1           py311h12c1d0e_0    conda-forge
referencing               0.32.0             pyhd8ed1ab_0    conda-forge
reproc                    14.2.4.post0         hcfcfb64_1    conda-forge
reproc-cpp                14.2.4.post0         h63175ca_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ripgrep                   14.0.3               h7f3b576_1    conda-forge
rpds-py                   0.16.2          py311hc37eb10_0    conda-forge
ruamel.yaml               0.18.5          py311ha68e1ae_0    conda-forge
ruamel.yaml.clib          0.2.7           py311ha68e1ae_2    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
ruamel_yaml               0.15.80         py311ha68e1ae_1009    conda-forge
semver                    3.0.2              pyhd8ed1ab_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sphinx                    7.2.6              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.7              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.5              pyhd8ed1ab_0    conda-forge
sphinxcontrib-htmlhelp    2.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.6              pyhd8ed1ab_0    conda-forge
sphinxcontrib-serializinghtml 1.1.9              pyhd8ed1ab_0    conda-forge
sqlite                    3.44.2               hcfcfb64_0    conda-forge
stdlib-list               0.8.0              pyhd8ed1ab_0    conda-forge
tbb                       2021.11.0            h91493d7_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomli-w                   1.0.0              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
userpath                  1.7.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wincertstore              0.2             pyhd8ed1ab_1009    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yaml-cpp                  0.8.0                h63175ca_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstandard                 0.22.0          py311he5d195f_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

### ~/.condarc

```yaml
channels:
  - conda-forge
  - microsoft
channel_priority: strict
changeps1: false
```

**Comment by JohanMabille** [comment]
The repodata has been [patched](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/628), reinstalling/upgrading mamba should not pull fmt 10.2 anymore.
