### ISSUE TITLE
mamba argument COMMAND: conflicting subparser: repoquery after trying to update all packages in conda base environment

### ISSUE THREAD

**Issue by yodar101** [mamba-org/mamba#3287]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

None found

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

After trying to do something with mamba like listing packages or updating all packages in conda base environment, I get the error listed in the mamba info. I installed mamba into an exisiting Anaconda installation and packages as well as package channels are managed by mamba since I installed it into base env, I did not change anything in the .condarc or in the environment.yml file manually. Using mamba 1.5.1 here.

### mamba info / micromamba info

```shell
argument COMMAND: conflicting subparser: repoquery

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 945, in exception_converter
        raise e
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 938, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 877, in _wrapped_main
        configure_parser_repoquery(p._subparsers._group_actions[0])
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 805, in configure_parser_repoquery
        p = sub_parsers.add_parser(
            ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr0y/anaconda3/lib/python3.11/argparse.py", line 1192, in add_parser
        raise ArgumentError(self, _('conflicting subparser: %s') % name)
    argparse.ArgumentError: argument COMMAND: conflicting subparser: repoquery

`$ /home/dr0y/anaconda3/bin/mamba update mamba`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=dst_python3
                CONDA_EXE=/home/dr0y/anaconda3/bin/conda
             CONDA_PREFIX=/home/dr0y/anaconda3/envs/dst_python3
           CONDA_PREFIX_1=/home/dr0y/anaconda3
    CONDA_PROMPT_MODIFIER=(dst_python3)
         CONDA_PYTHON_EXE=/home/dr0y/anaconda3/bin/python
               CONDA_ROOT=/home/dr0y/anaconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/dr0y/anaconda3/envs/dst_python3/bin:/home/dr0y/anaconda3/condabi
                          n:/home/dr0y/*:/home/dr0y/.local/bin:/home/dr0y/.local/bin/android:/ho
                          me/dr0y/.local/bin/android/platform-
                          tools:/home/dr0y/.local/bin/android/platform-tools:/home/dr0y/.local/b
                          in/android:/home/dr0y/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/loc
                          al/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : dst_python3
    active env location : /home/dr0y/anaconda3/envs/dst_python3
            shell level : 2
       user config file : /home/dr0y/.condarc
 populated config files : 
          conda version : 23.7.4
    conda-build version : 24.1.2
         python version : 3.11.8.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.36=0
                          __linux=6.1.0=0
                          __unix=0=0
       base environment : /home/dr0y/anaconda3  (writable)
      conda av data dir : /home/dr0y/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dr0y/anaconda3/pkgs
                          /home/dr0y/.conda/pkgs
       envs directories : /home/dr0y/anaconda3/envs
                          /home/dr0y/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.8 Linux/6.1.0-20-amd64 linuxmint/6 glibc/2.36
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
```

### Logs

```shell
argument COMMAND: conflicting subparser: repoquery

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 945, in exception_converter
        raise e
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 938, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 877, in _wrapped_main
        configure_parser_repoquery(p._subparsers._group_actions[0])
      File "/home/dr0y/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 805, in configure_parser_repoquery
        p = sub_parsers.add_parser(
            ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr0y/anaconda3/lib/python3.11/argparse.py", line 1192, in add_parser
        raise ArgumentError(self, _('conflicting subparser: %s') % name)
    argparse.ArgumentError: argument COMMAND: conflicting subparser: repoquery

`$ /home/dr0y/anaconda3/bin/mamba update mamba`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=dst_python3
                CONDA_EXE=/home/dr0y/anaconda3/bin/conda
             CONDA_PREFIX=/home/dr0y/anaconda3/envs/dst_python3
           CONDA_PREFIX_1=/home/dr0y/anaconda3
    CONDA_PROMPT_MODIFIER=(dst_python3)
         CONDA_PYTHON_EXE=/home/dr0y/anaconda3/bin/python
               CONDA_ROOT=/home/dr0y/anaconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/dr0y/anaconda3/envs/dst_python3/bin:/home/dr0y/anaconda3/condabi
                          n:/home/dr0y/*:/home/dr0y/.local/bin:/home/dr0y/.local/bin/android:/ho
                          me/dr0y/.local/bin/android/platform-
                          tools:/home/dr0y/.local/bin/android/platform-tools:/home/dr0y/.local/b
                          in/android:/home/dr0y/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/loc
                          al/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : dst_python3
    active env location : /home/dr0y/anaconda3/envs/dst_python3
            shell level : 2
       user config file : /home/dr0y/.condarc
 populated config files : 
          conda version : 23.7.4
    conda-build version : 24.1.2
         python version : 3.11.8.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.36=0
                          __linux=6.1.0=0
                          __unix=0=0
       base environment : /home/dr0y/anaconda3  (writable)
      conda av data dir : /home/dr0y/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dr0y/anaconda3/pkgs
                          /home/dr0y/.conda/pkgs
       envs directories : /home/dr0y/anaconda3/envs
                          /home/dr0y/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.8 Linux/6.1.0-20-amd64 linuxmint/6 glibc/2.36
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
```

### environment.yml

```yaml
name: ds
channels:
 - conda-forge

dependencies:
 - bokeh
 - cartopy
 - colorcet
 - graphviz
 - python-graphviz
 - dask
 - datashader
 - distributed
 - fastparquet
 - holoviews
 - ipython
 - jupyter
 - matplotlib
 - networkx>=2.0
 - numba
 - numpy
 - pandas >=0.24.1
 - param
 - python-snappy
 - python
 - rasterio
 - requests
 - scikit-image
 - scipy
 - shapely
 - snappy
 - statsmodels
 - streamz
 - xarray
 - ipympl
```

### ~/.condarc

```yaml
channels:
  - conda-forge
  - defaults
ssl_verify: true
```

**Comment by csjiyw** [comment]
conda intall conda-libmamba-solver=23.7.0
mamba --help

**Comment by wenhaoli-wenhaoli** [comment]
> conda intall conda-libmamba-solver=23.7.0 mamba --help

no any help. IT can not solve this problem

**Comment by jjerphan** [comment]
Hi, this error should not exist in 2.0 since mamba does not depend on conda anymore.

I am closing this issue since we are not developing 1.x but for security issues.
