### ISSUE TITLE
Installation of xmlschema library fails for an issue with locale setting

### ISSUE THREAD

**Issue by brunato** [mamba-org/mamba#3553]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

Searched but nothing that matches the reported error

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

Since the version v2.5.0 of *xmlschema* the package is not installable due to an error in extraction of the files:

```bash
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━       0 /       1                            0.0scritical libmamba Pathname can't be converted from UTF-8 to current locale.
error    libmamba Error opening for reading "/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/pkgs/xmlschema-2.5.0-pyhd8ed1ab_0/info/index.json": No such file or directory
xmlschema                                          361.8kB @   1.4MB/s  0.3s
xmlschema-2.5.0-pyhd8ed1ab_0.conda extraction failed
Found incorrect download: xmlschema. Aborting
```

I'm the maintainer of *xmlschema*, one year ago a user of the library [opened an issue](https://github.com/sissaschool/xmlschema/issues/370) about that problem. Now, checking this i see that the problem persists and also with all the following versions of *xmlschema*.

After an analysis of changes of between v2.3.0 and v2.5.0 i found the difference that causes of the error. In version v2.5.0 i added a set of test cases under the path `tests/test_cases/examples/menù/`. 

My hypothesis is that the error is generated by the library *libarchive* that mamba probably uses for extraction, that is not able to extract the files for an issue with locale setting https://github.com/libarchive/libarchive/issues/587.

Best regards

### Logs

```shell
Looking for: ['xmlschema==2.5.0']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.9.*


Transaction

  Prefix: /home/brunato/.pyenv/versions/mambaforge-4.12.0-0

  Updating specs:

   - xmlschema==2.5.0
   - ca-certificates
   - certifi
   - openssl


  Package      Version  Build         Channel                 Size
────────────────────────────────────────────────────────────────────
  Upgrade:
────────────────────────────────────────────────────────────────────

  - xmlschema    2.3.0  pyhd8ed1ab_0  conda-forge                 
  + xmlschema    2.5.0  pyhd8ed1ab_0  conda-forge/noarch     362kB

  Summary:

  Upgrade: 1 packages

  Total download: 362kB

────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] y
[+] 0.2s
Downloading  (1) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.7kB / 361.8kB xmlschema                  0.2s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━       0 /       1                            0.0scritical libmamba Pathname can't be converted from UTF-8 to current locale.
error    libmamba Error opening for reading "/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/pkgs/xmlschema-2.5.0-pyhd8ed1ab_0/info/index.json": No such file or directory
xmlschema                                          361.8kB @   1.4MB/s  0.3s
xmlschema-2.5.0-pyhd8ed1ab_0.conda extraction failed
Found incorrect download: xmlschema. Aborting

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/lib/python3.9/site-packages/mamba/mamba.py", line 938, in exception_converter
        raise e
      File "/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/lib/python3.9/site-packages/mamba/mamba.py", line 931, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/lib/python3.9/site-packages/mamba/mamba.py", line 889, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/lib/python3.9/site-packages/mamba/mamba.py", line 752, in do_call
        exit_code = install(args, parser, "install")
      File "/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/lib/python3.9/site-packages/mamba/mamba.py", line 588, in install
        transaction.fetch_extract_packages()
    RuntimeError: Found incorrect download: xmlschema. Aborting

`$ /home/brunato/.pyenv/versions/mambaforge-4.12.0-0/bin/mamba install xmlschema==2.5.0`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/brunato/.pyenv/versions/mambaforge-4.12.0-0
           CURL_CA_BUNDLE=<not set>
             MOZ_GMP_PATH=/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed
                     PATH=/home/brunato/.pyenv/versions/mambaforge-4.12.0-0/bin:/home/brunato/.p
                          yenv/libexec:/home/brunato/.pyenv/plugins/python-build/bin:/home/bruna
                          to/.pyenv/shims:/home/brunato/.pyenv/bin:/home/brunato/.local/bin:/hom
                          e/brunato/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
          PYENV_HOOK_PATH=/home/brunato/.pyenv/pyenv.d:/usr/etc/pyenv.d:/usr/local/etc/pyenv.d:/
                          etc/pyenv.d:/usr/lib/pyenv/hooks
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/brunato/.condarc
 populated config files : /home/brunato/.pyenv/versions/mambaforge-4.12.0-0/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __linux=6.11.3=0
                          __glibc=2.39=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/brunato/.pyenv/versions/mambaforge-4.12.0-0  (writable)
      conda av data dir : /home/brunato/.pyenv/versions/mambaforge-4.12.0-0/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/brunato/.pyenv/versions/mambaforge-4.12.0-0/pkgs
                          /home/brunato/.conda/pkgs
       envs directories : /home/brunato/.pyenv/versions/mambaforge-4.12.0-0/envs
                          /home/brunato/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.16 Linux/6.11.3-200.fc40.x86_64 fedora/40 glibc/2.39
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by jjerphan** [comment]
Hi,

This seems to duplicate https://github.com/sissaschool/xmlschema/issues/370.

**Comment by jjerphan** [comment]
This might be due to the usage of `libarchive` from Anaconda's default channels. We recommend against using them because they are incompatible with conda-forge's.
