### ISSUE TITLE
Inconsistencies with globs in `MatchSpec` parsing

### ISSUE THREAD

**Issue by jaimergp** [mamba-org/mamba#3601]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

matchspec glob

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I have detected some parsing / roundtrip issues with libmamba `MatchSpec` objects:

This should be valid (although it's a redundant version glob):

```python
>>> print(MatchSpec.parse("name *,*.* build*"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
libmambapy.bindings.specs.ParseError: Found invalid version predicate in "*.*"
>>> print(MatchSpecConda("name *,*.* build*"))
name[version='*,*.*',build=build*]
```

Also, when passing this spec to the solver, the error message is lossy. Note how the trailing `*` is lost in the build string:

```python
 {
  "Install": [
    "accelerate[version=\"=*,=*\",build=\"np17py27*\"]"
  ]
}
```

```
Could not solve for environment specs
The following package could not be installed
└─ accelerate =*,=* np17py27 does not exist (perhaps a typo or a missing channel).
```

### mamba info / micromamba info

```shell
libmamba version : 2.0.3
          mamba version : 2.0.3
           curl version : libcurl/8.10.1 OpenSSL/3.4.0 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.6
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /root/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /root/.mambarc
 populated config files : /opt/conda/.condarc
       virtual packages : __unix=0=0
                          __linux=5.15.49=0
                          __glibc=2.31=0
                          __archspec=1=aarch64
               channels : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
```

**Comment by jaimergp** [comment]
If you ask _me_, I understanding as "any version that has at least two components". So `*` would match `[1, 2, 1.2, 2.3.4]`, but `*.*` would only match `[1.2, 2.3.4]` in the same list. 

I checked and `conda` seems to do that:

```
$ conda search -c bioconda "anvio=*"
Loading channels: done
# Name                       Version           Build  Channel             
anvio                              6               0  bioconda            
anvio                            6.1               0  bioconda            
anvio                            6.1               1  bioconda            
anvio                            6.2               0  bioconda            
anvio                              7               0  bioconda            
anvio                              7      hdfd78af_1  bioconda            
$ conda search -c bioconda "anvio=*.*"
Loading channels: done
# Name                       Version           Build  Channel             
anvio                            6.1               0  bioconda            
anvio                            6.1               1  bioconda            
anvio                            6.2               0  bioconda            
```

**Comment by jdblischak** [comment]
>  In `mamba 2`, it seems that the version is not handled as a regex at all.

This seems like a substantial backwards incompatibility that should be added to the [list of breaking changes](https://mamba.readthedocs.io/en/latest/developer_zone/changes-2.0.html) introduced in mamba 2. Should I submit a PR?

**Comment by jdblischak** [comment]
> Or said differently, what are the concrete cases where a regex expression cannot be expressed with an operator and numbers to be handled?

My use case is nightly feedstock builds. We build the latest version of our C++ library and upload it as a conda binary with the version string `X.X.X.YYYY_MM_DD`. Then we build the latest version of our Python client, and the recipe pins the C++ library with the requirement `*.YYYY_MM_DD`. This allows us to always install the nightly version of the C++ library without worrying about the current version of the C++ library (which is always changing).

**Comment by Hind-M** [comment]
> > In `mamba 2`, it seems that the version is not handled as a regex at all.
> 
> This seems like a substantial backwards incompatibility that should be added to the [list of breaking changes](https://mamba.readthedocs.io/en/latest/developer_zone/changes-2.0.html) introduced in mamba 2. Should I submit a PR?

Yes a PR is most welcome, thank you!

**Comment by jdblischak** [comment]
Actually I am a little confused. I was going to write that the breaking change was that you could no longer use globs in version restrictions because the version parsing was no longer handled as a regex. However, looking at the documentation for [`VersionSpec`](https://mamba.readthedocs.io/en/latest/usage/specs.html#versionspec), it appears that it isn't that straightforward.

From my experiments (code below), I found that:

* Trailing globs work as expected
* Internal globs are accepted but do not work
* Leading globs fail with `invalid version predicate`

```python
import libmambapy

libmambapy.version.version_info
## ('2', '0', '4')

import libmambapy.specs as specs

specs.VersionSpec.parse("0.0.*")
specs.VersionSpec.parse("0.*.0")
specs.VersionSpec.parse("*.0.0")
## Traceback (most recent call last):
##   File "<stdin>", line 1, in <module>
## libmambapy.bindings.specs.ParseError: Found invalid version predicate in "*.0.0"

# Trailing glob works as expected
specs.VersionSpec.parse("0.0.*").contains(specs.Version.parse("0.0.1"))
## True
specs.VersionSpec.parse("0.0.*").contains(specs.Version.parse("1.0.0"))
## False

# Internal glob accepted but does not work
specs.VersionSpec.parse("0.*.0").contains(specs.Version.parse("0.1.0"))
## False
specs.VersionSpec.parse("0.*.0").contains(specs.Version.parse("1.0.0"))
## False
```

**Comment by AntoinePrv** [comment]
Hello, it's been a while since I made these changes.

Internal (or leading) globs work more like a regex than simple version comparisons.
If we wish to support it, we need to add another variant to the `VersionSpec` and adapt the parsing to create it as needed. From a quick glance at the code it's doable.

> Internal glob accepted but does not work

> Leading globs fail with invalid version predicate

I think this is just a matter of where the parsing fails. It is possible `0.*.0` is understood as `0.0*.0` (where the `*` is this special number mentioned in the CEP).

> Trailing globs work as expected

Trailing globs are much easier, I think they are handled as `=0.0`. Note that there is not check on the "number of components" here.

**Comment by AntoinePrv** [comment]
@jaimergp @jdblischak what are needed use cases case here? Is `*.0.*` patterns enough here or do you also need to mix glob and numbers in a single version segment, like `20*.*` (That could currently have other meanings)?

**Comment by jdblischak** [comment]
> what are needed use cases case here?

@AntoinePrv My use case is nightly feedstock builds (explained in more detail above in https://github.com/mamba-org/mamba/issues/3601#issuecomment-2515496337). Essentially I want to be able to use a leading glob to require the latest nightly  conda binary (`*.YYYY_MM_DD`). That way I don't need to update my setup code every time the version number is bumped.
