### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\xf6' in position 8: illegal multibyte sequence

### ISSUE THREAD

**Issue by aswordok** [mamba-org/mamba#3608]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

critical libmamba could not load prefix data

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

(311) D:\+AI\myComfyUI>conda install mamba
Channels:
 - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
 - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2
 - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
 - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(311) D:\+AI\myComfyUI>mamba list | findstr mamba
ERROR: Exception:
Traceback (most recent call last):
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_internal\commands\inspect.py", line 62, in run
    print_json(data=output)
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\__init__.py", line 106, in print_json
    get_console().print_json(
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\console.py", line 1782, in print_json
    self.print(json_renderable, soft_wrap=True)
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\console.py", line 1673, in print
    with self:
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\console.py", line 865, in __exit__
    self._exit_buffer()
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "D:\+AI\miniconda3\envs\311\Lib\site-packages\pip\_vendor\rich\_win32_console.py", line 403, in write_text
    self.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\xf6' in position 8: illegal multibyte sequence
critical libmamba could not load prefix data
(311) D:\+AI\myComfyUI>conda list | findstr mamba
libmamba                  2.0.3                h81425b0_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
mamba                     2.0.3                hde45397_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
(311) D:\+AI\myComfyUI>conda config --show solver
solver: libmamba

### mamba info / micromamba info

```shell
(311) D:\+AI\myComfyUI>mamba info

       libmamba version : 2.0.3
          mamba version : 2.0.3
           curl version : libcurl/8.10.1 Schannel zlib/1.3.1 libssh2/1.11.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.6
       envs directories : D:\+AI\miniconda3\envs\311\Library\envs
          package cache : D:\+AI\miniconda3\envs\311\Library\pkgs
                          C:\Users\user\.mamba\pkgs
                          C:\Users\user\AppData\Roaming\.mamba\pkgs
            environment : D:\+AI\miniconda3\envs\311 (active)
           env location : D:\+AI\miniconda3\envs\311
      user config files : C:\Users\user\.mambarc
 populated config files : C:\Users\user\.condarc
       virtual packages : __win=10.0.26100=0
                          __archspec=1=x86_64
                          __cuda=12.7=0
               channels : https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/win-64
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
       base environment : D:\+AI\miniconda3\envs\311\Library
               platform : win-64
```

### ~/.condarc

```yaml
(311) D:\+AI\myComfyUI>type "C:\Users\user\.condarc"
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
show_channel_urls: true
ssl_verify: true
channel_priority: strict
```

**Comment by aswordok** [comment]
The issue has been resolved and mamba needs to be installed in the base environment.
