### ISSUE TITLE
conda-forge repodata files getting truncated?

### ISSUE THREAD

**Issue by pbradz** [mamba-org/mamba#442]
I'm not 100% sure whether the problem here is with mamba or with conda-forge, but installing packages through conda works fine for me. However, just after installing mamba, I tried to run `mamba install wget` and got the following error:

```
    Traceback (most recent call last):
      File "/home/pbradz/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/pbradz/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 814, in exception_converter
        raise e
      File "/home/pbradz/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 808, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/pbradz/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 773, in _wrapped_main
        result = do_call(args, p)
      File "/home/pbradz/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 663, in do_call
        exit_code = install(args, parser, 'install')
      File "/home/pbradz/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 478, in install
        repo = subdir.create_repo(pool)
    RuntimeError: Could not read JSON repodata file (/home/pbradz/miniconda3/pkgs/cache/b556ea5a.json) parse error line 648291

`$ /home/pbradz/miniconda3/bin/mamba install wget`


  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/pbradz/miniconda3/bin/conda
             CONDA_PREFIX=/home/pbradz/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/pbradz/miniconda3/bin/python
               CONDA_ROOT=/home/pbradz/miniconda3
              CONDA_SHLVL=1
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/pbradz/miniconda3/bin:/home/pbradz/miniconda3/condabin:/home/pbr
                          adz/bin:/home/pbradz/.local/bin:/usr/local/go/bin:/usr/local/sbin:/usr
                          /local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/
                          snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/pbradz/miniconda3
            shell level : 1
       user config file : /home/pbradz/.condarc
 populated config files : /home/pbradz/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.27
       base environment : /home/pbradz/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/pbradz/miniconda3/pkgs
                          /home/pbradz/.conda/pkgs
       envs directories : /home/pbradz/miniconda3/envs
                          /home/pbradz/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.5 Linux/4.15.0-109-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

I opened the offending json file and it seemed like it had gotten truncated partway through (i.e., it just stopped dead at a comma). I removed that cache file and tried again, but got the same error; this time it got truncated in a different place.

Finally, I removed conda-forge from my channels in my ~/.condarc. This time everything worked. I've tried adding other channels in there and so far none of them have broken mamba except for conda-forge. The conda-forge .json file does seem to be much larger than the others, since when I clear the cache directory it finishes that one last.

Any ideas what could be going on? I'm running Ubuntu 18.04 LTS here, if that's relevant.

**Comment by wolfv** [comment]
thanks for opening this issue... I haven't seen this so far and I was using mamba quite extensively the last couple of days. Let's see if this keeps popping up. are you on the latest mamba version?

**Comment by pbradz** [comment]
I think so, I just tried installing mamba again from conda-forge and it seems to be up to date. I'm not sure what the actual version number is; `mamba -V` returns `conda 4.8.3`.

**Comment by pbradz** [comment]
Hey, the issue seems fixed -- maybe there was a problem on conda-forge's side? I still don't understand why regular conda would have worked in that situation, but I'll take it.

**Comment by wolfv** [comment]
Hmm, actually mamba should now print its own version, too. Latest should be 0.4.4

Maybe with --version?

**Comment by pbradz** [comment]
Yup, that works:
```
mamba 0.4.4
conda 4.8.3
```
Thanks for looking into it!

**Comment by siebrenf** [comment]
I had the same problem. The issue was fixed by removing conda entirely and starting over.

**Cause**
The issue started after interrupting `mamba env create -f environment.yaml`. Either I disconnected from the server while the process was terminating, or I was spamming ctrl+C. So yea... only myself to blame.

**Details**
The error originated within the same json file. Removing and rerunning did not change anything. Neither did commenting out conda-forge packages (it then hung on bioconda). 

The json file was always truncated after a comma, and contained no whitespaces or newlines (contrary to the other json files in `pkgs/cache`).

The error occurred regardless of the conda and mamba versions and persisted after removing all environments, resetting the base environment to revision 1 and running `conda clean --all`. 

Finally, running the same command from conda took hours, and ended with a "Solving environment: Failed", or somesuch.

**Comment by mezhaka** [comment]
Same problem.  It might be that I ran out of space on / while `mamba env create`.

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/disks/repo/bin/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/mnt/disks/repo/bin/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/mnt/disks/repo/bin/miniconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 118, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/mnt/disks/repo/bin/miniconda3/lib/python3.8/site-packages/mamba/mamba_env.py", line 42, in mamba_install
        index = load_channels(
      File "/mnt/disks/repo/bin/miniconda3/lib/python3.8/site-packages/mamba/utils.py", line 133, in load_channels
        repo = subdir.create_repo(pool)
    RuntimeError: Could not read JSON repodata file (/mnt/disks/repo/bin/miniconda3/pkgs/cache/585bcc15.json) parse error line 1107963

`$ /mnt/disks/repo/bin/miniconda3/bin/mamba create`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/mnt/disks/repo/bin/miniconda3/bin/conda
             CONDA_PREFIX=/mnt/disks/repo/bin/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/mnt/disks/repo/bin/miniconda3/bin/python
               CONDA_ROOT=/mnt/disks/repo/bin/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/mnt/disks/repo/bin/miniconda3/bin:/mnt/disks/repo/bin/miniconda3/cond
                          abin:/home/ant/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/
                          games
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /mnt/disks/repo/bin/miniconda3
            shell level : 1
       user config file : /home/ant/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/disks/repo/bin/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/disks/repo/bin/miniconda3/pkgs
                          /home/ant/.conda/pkgs
       envs directories : /mnt/disks/repo/bin/miniconda3/envs
                          /home/ant/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.23.0 CPython/3.8.3 Linux/4.19.0-10-cloud-amd64 debian/10 glibc/2.28
                UID:GID : 1010:1011
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

reinstalling miniconda helped

**Comment by wolfv** [comment]
I think this is much more stable now. Thanks for the bug report!
