### ISSUE TITLE
mamba throws error while conda doesn't

### ISSUE THREAD

**Issue by Rohit-Satyam** [mamba-org/mamba#495]
Hi everyone!!

I really like the speed of mamba however, in many cases it throws error than conda. Below mentioned is an example. I tried downloading the  soapdenovo2 assembler but using mamba it got aborted but conda didn't find any conflicts. Why is it so?

`conda 4.8.4
mamba 4.8.4
`

`mamba install -c bioconda soapdenovo2`  
```
Getting  https://conda.anaconda.org/bioconda/linux-64
Getting  https://conda.anaconda.org/bioconda/noarch
Getting  https://conda.anaconda.org/conda-forge/linux-64
Getting  https://conda.anaconda.org/conda-forge/noarch
Getting  https://repo.anaconda.com/pkgs/main/linux-64
Getting  https://repo.anaconda.com/pkgs/main/noarch
Getting  https://repo.anaconda.com/pkgs/r/linux-64
Getting  https://repo.anaconda.com/pkgs/r/noarch


Looking for: ['soapdenovo2']


Parsing /home/baadalvm/miniconda3/pkgs/cache/ffeee55f.json
32501 packages in https://conda.anaconda.org/bioconda/linux-64
Parsing /home/baadalvm/miniconda3/pkgs/cache/2a957770.json
17680 packages in https://conda.anaconda.org/bioconda/noarch
Parsing /home/baadalvm/miniconda3/pkgs/cache/497deca9.json
118577 packages in https://conda.anaconda.org/conda-forge/linux-64
Parsing /home/baadalvm/miniconda3/pkgs/cache/09cdf8bf.json
38842 packages in https://conda.anaconda.org/conda-forge/noarch
Parsing /home/baadalvm/miniconda3/pkgs/cache/47929eba.json
17659 packages in https://repo.anaconda.com/pkgs/main/linux-64
Parsing /home/baadalvm/miniconda3/pkgs/cache/3e39a7aa.json
1939 packages in https://repo.anaconda.com/pkgs/main/noarch
Parsing /home/baadalvm/miniconda3/pkgs/cache/2ce54b42.json
6620 packages in https://repo.anaconda.com/pkgs/r/linux-64
Parsing /home/baadalvm/miniconda3/pkgs/cache/4ea078d6.json
5025 packages in https://repo.anaconda.com/pkgs/r/noarch
Allowing downgrade: 1
Creating the solver...
Job: soapdenovo2

Encountered 0 problems.

3 installed packages:
  - libgcc-7.2.0.2-h69d50b8_2
  - samtools-0.1.19.7-hf89b575_7
  - soapdenovo2-2.40.0.1-1

Solution:


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/baadalvm/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/baadalvm/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 250, in _wrapped_main
        exit_code = do_call(args, p)
      File "/home/baadalvm/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 229, in do_call
        exit_code = install(args, parser, 'install')
      File "/home/baadalvm/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 179, in install
        update_specs  = specs
    TypeError: __new__() missing 1 required positional argument: 'neutered_specs'

`$ /home/baadalvm/miniconda3/bin/mamba install -c bioconda soapdenovo2`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/baadalvm/miniconda3/bin/conda
             CONDA_PREFIX=/home/baadalvm/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/baadalvm/miniconda3/bin/python
               CONDA_ROOT=/home/baadalvm/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/baadalvm/miniconda3/bin:/home/baadalvm/miniconda3/condabin:/usr/
                          local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
                          r/local/games:/snap/bin:/home/baadalvm/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>

     active environment : base
    active env location : /home/baadalvm/miniconda3
            shell level : 1
       user config file : /home/baadalvm/.condarc
 populated config files : /home/baadalvm/.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 3.7.8.final.0
       virtual packages : __glibc=2.27
       base environment : /home/baadalvm/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/baadalvm/miniconda3/pkgs
                          /home/baadalvm/.conda/pkgs
       envs directories : /home/baadalvm/miniconda3/envs
                          /home/baadalvm/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.8 Linux/4.15.0-109-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

However with conda it get's installed successfully

`conda install -c bioconda soapdenovo2`

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/baadalvm/miniconda3

  added / updated specs:
    - soapdenovo2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    samtools-0.1.19            |       hf89b575_7         3.2 MB  bioconda
    soapdenovo2-2.40           |                1         993 KB  bioconda
    ------------------------------------------------------------
                                           Total:         4.1 MB

The following NEW packages will be INSTALLED:

  libgcc             conda-forge/linux-64::libgcc-7.2.0-h69d50b8_2
  samtools           bioconda/linux-64::samtools-0.1.19-hf89b575_7
  soapdenovo2        bioconda/linux-64::soapdenovo2-2.40-1


Proceed ([y]/n)? y


Downloading and Extracting Packages
soapdenovo2-2.40     | 993 KB    | ############################################################################################# | 100%
samtools-0.1.19      | 3.2 MB    | ############################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by wolfv** [comment]
When and how did you install mamba? You have a pretty old version I believe.

**Comment by kevinrue** [comment]
Can you check your version of `mamba` again?

You cannot have `mamba 4.8.4` as the latest version is `0.4.1`

I have:
```
% mamba --version
mamba 0.3.3
conda 4.8.3
```

and I get 

```
% mamba create --name soapdenovo2 -c bioconda soapdenovo2

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.3.3) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

pkgs/main/osx-64         [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:00s) No change
bioconda/noarch          [====================] (00m:00s) Done
pkgs/r/osx-64            [====================] (00m:00s) No change
bioconda/osx-64          [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
conda-forge/noarch       [====================] (00m:01s) Done
conda-forge/osx-64       [====================] (00m:03s) Done

Looking for: ['soapdenovo2']

Transaction

  Prefix: /Users/kevin/opt/anaconda3/envs/soapdenovo2



  No specs added or removed.

  Package      Version  Build          Channel                  Size
──────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────

  libcxx        10.0.1  h5f48129_0     conda-forge/osx-64     Cached
  ncurses          6.2  hb1e8313_1     conda-forge/osx-64     Cached
  samtools      0.1.19  h96d0757_8     bioconda/osx-64          2 MB
  soapdenovo2     2.40  ha92aebf_2     bioconda/osx-64        572 KB
  zlib          1.2.11  h7795811_1009  conda-forge/osx-64     Cached

  Summary:

  Install: 5 packages

  Total download: 3 MB

──────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
Finished samtools                             (00m:00s)               2 MB      4 MB/s
Finished soapdenovo2                          (00m:00s)             572 KB    939 KB/s
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate soapdenovo2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

```

**Comment by Rohit-Satyam** [comment]
Seems I referred to a blog post and ended up having old version of mamba. The Mamba initially showed the conda version only I guess
`conda install mamba -c conda-forge/label/mamba-alpha -c conda-forge`

I have removed and doing a fresh installation. It's working fine now. Sorry for the trouble. I will close this.

**Comment by wolfv** [comment]
No problem!
