### ISSUE TITLE
attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by saraedum** [mamba-org/mamba#503]
There seems to be an issue with error handling in mamba.

When I run the following (invalid) command, I get a failing relative import:

```
mamba create -n crash python=3.6.9-2_73_pypy
```

produces

```
    Traceback (most recent call last):
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 935, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 894, in _wrapped_main
        result = do_call(args, p)
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 782, in do_call
        exit_code = create(args, parser)
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 661, in create
        install(args, parser, "create")
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 399, in install
        specs.extend(specs_from_args(args_packages, json=context.json))
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 120, in specs_from_args
        return [arg2spec(arg, json=json) for arg in args]
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 120, in <listcomp>
        return [arg2spec(arg, json=json) for arg in args]
      File "/home/jule/proj/conda/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 103, in arg2spec
        from ..exceptions import CondaValueError
    ValueError: attempted relative import beyond top-level package
```

**Comment by saraedum** [comment]
This is with mamba 0.5.1 from conda-forge.

**Comment by wolfv** [comment]
indeed that looks like a seldomly executed code path. do you want to contribute a fix? This error needs to be imported from conda.

**Comment by saraedum** [comment]
Sure. I'll give it a try.
