### ISSUE TITLE
Mamba 0.7 crashes on windows

### ISSUE THREAD

**Issue by olivier-lacroix** [mamba-org/mamba#586]
Hi there,

Since updating to mamba 0.7, I have a traceback:

```
Traceback (most recent call last):
  File "***\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "***\mamba\mamba.py", line 52, in <module>
    import mamba.mamba_api as api
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by wolfv** [comment]
Thanks! 
I just tried on Windows, Python 3.7 seems to be fine. What version of Python are you on?

**Comment by wolfv** [comment]
I just tried on Win 10, with a fresh Miniconda 3 (Python 3.8) installation and couldn't reproduce.
Sorry!
Can you post a `conda list`?

**Comment by olivier-lacroix** [comment]
Sure

```
brotlipy                  0.7.0           py37h0013d47_1001    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.11.8            h5b45459_0    conda-forge
certifi                   2020.11.8        py37h03978a9_0    conda-forge
cffi                      1.14.3           py37hd6b71e5_1    conda-forge
chardet                   3.0.4           py37hf50a25e_1008    conda-forge
conda                     4.9.2            py37h03978a9_0    conda-forge
conda-package-handling    1.7.2            py37h6dbccfb_0    conda-forge
console_shortcut          0.1.1                         4
cryptography              3.2.1            py37hd8e9650_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               hc04afaa_3    conda-forge
libarchive                3.3.3             h793d221_1008    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libsolv                   0.7.16               h200bbdf_0    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
lzo                       2.10              hfa6e2cd_1000    conda-forge
mamba                     0.6.4            py37h6eabccc_0    conda-forge
menuinst                  1.4.16           py37hc8dfbb8_1    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pycosat                   0.6.3           py37h0013d47_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pysocks                   1.7.1            py37hf50a25e_2    conda-forge
python                    3.7.3                h510b542_1    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pywin32                   228              py37h4ab8f01_0    conda-forge
reproc                    14.2.0               h8ffe710_0    conda-forge
reproc-cpp                14.2.0               h0e60522_0    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.87          py37he774522_1
setuptools                50.3.1           py37haa95532_1
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               he774522_1    conda-forge
tk                        8.6.10               he774522_1    conda-forge
tqdm                      4.51.0             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
win_inet_pton             1.1.0            py37hc8dfbb8_1    conda-forge
wincertstore              0.2             py37hc8dfbb8_1005    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge
```

**Comment by olivier-lacroix** [comment]
I have the same issue after upgrading to python 3.8

```
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38hab1e662_1001    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.11.8            h5b45459_0    conda-forge
certifi                   2020.11.8        py38haa244fe_0    conda-forge
cffi                      1.14.3           py38h0e640b1_1    conda-forge
chardet                   3.0.4           py38h9bdc248_1008    conda-forge
conda                     4.9.2            py38haa244fe_0    conda-forge
conda-package-handling    1.7.2            py38h8934438_0    conda-forge
console_shortcut          0.1.1                         4
cryptography              3.2.1            py38hd8c33c5_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               hc04afaa_3    conda-forge
libarchive                3.3.3             h793d221_1008    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libsolv                   0.7.16               h200bbdf_0    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
lzo                       2.10              hfa6e2cd_1000    conda-forge
mamba                     0.7.0            py38he5b3c69_0    conda-forge
menuinst                  1.4.16           py38h32f6830_1    conda-forge
openssl                   1.1.1h               he774522_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pycosat                   0.6.3           py38hab1e662_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                   py38_0    conda-forge
pysocks                   1.7.1            py38h9bdc248_2    conda-forge
python                    3.8.6           h60c2a47_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pywin32                   228              py38h1e8a9f7_0    conda-forge
reproc                    14.2.0               h8ffe710_0    conda-forge
reproc-cpp                14.2.0               h0e60522_0    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.87          py38he774522_1
setuptools                50.3.1           py38haa95532_1
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               he774522_1    conda-forge
tk                        8.6.10               he774522_1    conda-forge
tqdm                      4.51.0             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
win_inet_pton             1.1.0            py38h32f6830_1    conda-forge
wincertstore              0.2             py38h32f6830_1005    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge
```

**Comment by dhirschfeld** [comment]
`mamba` 0.7 seems to work fine for me. I suspect a failed upgrade, most likely due to Windows holding references to DLLs preventing them being deleted/updated during an install. On Windows, you're much safer if you make sure no python processes are running at the same time as you do an update.

If that is the case then your package cache is corrupt and you need to remove all traces of `mamba` before reinstalling it. In ***powershell*** you can do this like below (***this will kill all existing python processes!***):
```powershell
ps python | kill
conda remove mamba --force --yes
ls "$env:CONDA_PREFIX\pkgs\mamba*" | Remove-Item -Recurse -Force
conda install mamba --yes
```

**Comment by olivier-lacroix** [comment]
Thanks @wolfv and @dhirschfeld for your answers.

@dhirschfeld , what you propose does not change a thing unfortunately. I still end up with the same traceback.

**Comment by dhirschfeld** [comment]
Yeah. I actually just ran into this in a Windows container so it does point to some issue with `mamba` on Windows :(

I can't dig into it just yet but will try to have a look this weekend...

**Comment by olivier-lacroix** [comment]
Ah! Not sure if this is a good or a bad thing :-D !

Thanks @dhirschfeld !

**Comment by wolfv** [comment]
I tried really hard to reproduce the issue:

I used 

mamba install -c conda-forge --strict-channel-priority brotlipy=0.7.0=py38hab1e662_1001 bzip2=1.0.8=he774522_3 ca-certificates=2020.11.8=h5b45459_0 certifi=2020.11.8=py38haa244fe_0 cffi=1.14.3=py38h0e640b1_1 chardet=3.0.4=py38h9bdc248_1008 conda=4.9.2=py38haa244fe_0 conda-package-handling=1.7.2=py38h8934438_0 console_shortcut=0.1.1=4 cryptography=3.2.1=py38hd8c33c5_0 idna=2.10=pyh9f0ad1d_0 krb5=1.17.1=hc04afaa_3 libarchive=3.3.3=h793d221_1008 libcurl=7.71.1=h4b64cdc_8 libiconv=1.16=he774522_0 libsolv=0.7.16=h200bbdf_0 libssh2=1.9.0=hb06d900_5 libxml2=2.9.10=h1006b36_2 lz4-c=1.9.2=h62dcd97_2 lzo=2.10=hfa6e2cd_1000 mamba=0.7.0=py38he5b3c69_0 menuinst=1.4.16=py38h32f6830_1 openssl=1.1.1h=he774522_0 pip=20.2.4=py_0 pycosat=0.6.3=py38hab1e662_1005 pycparser=2.20=pyh9f0ad1d_2 pyopenssl=19.1.0=py38_0 pysocks=1.7.1=py38h9bdc248_2 python=3.8.6=h60c2a47_0_cpython python_abi=3.8=1_cp38 pywin32=228=py38h1e8a9f7_0 reproc=14.2.0=h8ffe710_0 reproc-cpp=14.2.0=h0e60522_0 requests=2.25.0=pyhd3deb0d_0 ruamel_yaml=0.15.87=py38he774522_1 setuptools=50.3.1=py38haa95532_1 six=1.15.0=pyh9f0ad1d_0 sqlite=3.33.0=he774522_1 tk=8.6.10=he774522_1 tqdm=4.51.0=pyh9f0ad1d_0 urllib3=1.25.11=py_0 vc=14.1=h869be7e_1 vs2015_runtime=14.16.27012=h30e32a0_2 wheel=0.35.1=pyh9f0ad1d_0 win_inet_pton=1.1.0=py38h32f6830_1 wincertstore=0.2=py38h32f6830_1005 xz=5.2.5=h62dcd97_1 yaml=0.2.5=he774522_0 zlib=1.2.11=h62dcd97_1010 zstd=1.4.5=h1f3a1b7_2

to install the env you said was broken, but it still works for me :/

I think we're sure that you're activating the environment correctly, yes?

Did you reboot between tests? Some old dll's / filehandlers might only get really deleted after reboot ... 

I would gladly pull the build if I could reproduce the issue but I tried with python 3.7 and 3.8 and it worked :/

Btw your python 3.7 version in your first test is quite dated.

If your environment is still broken, can you use `conda env export` and / or `conda list --explicit`
```
name: base                                                                                                                                                                                                                                                  channels:                                                                                                                                                                                                                                                     - robostack                                                                                                                                                                                                                                                 - conda-forge                                                                                                                                                                                                                                               - defaults                                                                                                                                                                                                                                                dependencies:                                                                                                                                                                                                                                                 - brotlipy=0.7.0=py38hab1e662_1001                                                                                                                                                                                                                          - bzip2=1.0.8=he774522_3                                                                                                                                                                                                                                    - ca-certificates=2020.11.8=h5b45459_0                                                                                                                                                                                                                      - certifi=2020.11.8=py38haa244fe_0                                                                                                                                                                                                                          - cffi=1.14.3=py38h0e640b1_1                                                                                                                                                                                                                                - chardet=3.0.4=py38h9bdc248_1008                                                                                                                                                                                                                           - conda=4.9.2=py38haa244fe_0                                                                                                                                                                                                                                - conda-package-handling=1.7.2=py38h8934438_0                                                                                                                                                                                                               - console_shortcut=0.1.1=4                                                                                                                                                                                                                                  - cryptography=3.2.1=py38hd8c33c5_0                                                                                                                                                                                                                         - idna=2.10=pyh9f0ad1d_0                                                                                                                                                                                                                                    - krb5=1.17.1=hc04afaa_3                                                                                                                                                                                                                                    - libarchive=3.3.3=h793d221_1008                                                                                                                                                                                                                            - libcurl=7.71.1=h4b64cdc_8                                                                                                                                                                                                                                 - libiconv=1.16=he774522_0                                                                                                                                                                                                                                  - libsolv=0.7.16=h200bbdf_0                                                                                                                                                                                                                                 - libssh2=1.9.0=hb06d900_5                                                                                                                                                                                                                                  - libxml2=2.9.10=h1006b36_2                                                                                                                                                                                                                                 - lz4-c=1.9.2=h62dcd97_2                                                                                                                                                                                                                                    - lzo=2.10=hfa6e2cd_1000                                                                                                                                                                                                                                    - mamba=0.7.0=py38he5b3c69_0                                                                                                                                                                                                                                - menuinst=1.4.16=py38h32f6830_1                                                                                                                                                                                                                            - openssl=1.1.1h=he774522_0                                                                                                                                                                                                                                 - pip=20.2.4=py_0                                                                                                                                                                                                                                           - powershell_shortcut=0.0.1=3                                                                                                                                                                                                                               - pycosat=0.6.3=py38hab1e662_1005                                                                                                                                                                                                                           - pycparser=2.20=pyh9f0ad1d_2                                                                                                                                                                                                                               - pyopenssl=19.1.0=py38_0                                                                                                                                                                                                                                   - pysocks=1.7.1=py38h9bdc248_2                                                                                                                                                                                                                              - python=3.8.6=h60c2a47_0_cpython                                                                                                                                                                                                                           - python_abi=3.8=1_cp38                                                                                                                                                                                                                                     - pywin32=228=py38h1e8a9f7_0                                                                                                                                                                                                                                - reproc=14.2.0=h8ffe710_0                                                                                                                                                                                                                                  - reproc-cpp=14.2.0=h0e60522_0                                                                                                                                                                                                                              - requests=2.25.0=pyhd3deb0d_0                                                                                                                                                                                                                              - ruamel_yaml=0.15.87=py38he774522_1                                                                                                                                                                                                                        - setuptools=50.3.1=py38haa95532_1                                                                                                                                                                                                                          - six=1.15.0=pyh9f0ad1d_0                                                                                                                                                                                                                                   - sqlite=3.33.0=he774522_1                                                                                                                                                                                                                                  - tk=8.6.10=he774522_1                                                                                                                                                                                                                                      - tqdm=4.51.0=pyh9f0ad1d_0                                                                                                                                                                                                                                  - urllib3=1.25.11=py_0                                                                                                                                                                                                                                      - vc=14.1=h869be7e_1                                                                                                                                                                                                                                        - vs2015_runtime=14.16.27012=h30e32a0_2                                                                                                                                                                                                                     - wheel=0.35.1=pyh9f0ad1d_0                                                                                                                                                                                                                                 - win_inet_pton=1.1.0=py38h32f6830_1                                                                                                                                                                                                                        - wincertstore=0.2=py38h32f6830_1005                                                                                                                                                                                                                        - xz=5.2.5=h62dcd97_1                                                                                                                                                                                                                                       - yaml=0.2.5=he774522_0                                                                                                                                                                                                                                     - zlib=1.2.11=h62dcd97_1010                                                                                                                                                                                                                                 - zstd=1.4.5=h1f3a1b7_2                                                                                                                                                                                                                                   prefix: C:\Users\wolfv\Miniconda3 
```


```
# This file may be used to create an environment using:                                                                                                                                                                                                     # $ conda create --name <env> --file <this file>                                                                                                                                                                                                            # platform: win-64                                                                                                                                                                                                                                          @EXPLICIT                                                                                                                                                                                                                                                   https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2020.11.8-h5b45459_0.tar.bz2                                                                                                                                                                  https://conda.anaconda.org/conda-forge/win-64/vs2015_runtime-14.16.27012-h30e32a0_2.tar.bz2                                                                                                                                                                 https://conda.anaconda.org/conda-forge/win-64/vc-14.1-h869be7e_1.tar.bz2                                                                                                                                                                                    https://conda.anaconda.org/conda-forge/win-64/bzip2-1.0.8-he774522_3.tar.bz2                                                                                                                                                                                https://conda.anaconda.org/conda-forge/win-64/libiconv-1.16-he774522_0.tar.bz2                                                                                                                                                                              https://conda.anaconda.org/conda-forge/win-64/lz4-c-1.9.2-h62dcd97_2.tar.bz2                                                                                                                                                                                https://conda.anaconda.org/conda-forge/win-64/lzo-2.10-hfa6e2cd_1000.tar.bz2                                                                                                                                                                                https://conda.anaconda.org/conda-forge/win-64/openssl-1.1.1h-he774522_0.tar.bz2                                                                                                                                                                             https://conda.anaconda.org/conda-forge/win-64/reproc-14.2.0-h8ffe710_0.tar.bz2                                                                                                                                                                              https://conda.anaconda.org/conda-forge/win-64/sqlite-3.33.0-he774522_1.tar.bz2                                                                                                                                                                              https://conda.anaconda.org/conda-forge/win-64/tk-8.6.10-he774522_1.tar.bz2                                                                                                                                                                                  https://conda.anaconda.org/conda-forge/win-64/xz-5.2.5-h62dcd97_1.tar.bz2                                                                                                                                                                                   https://conda.anaconda.org/conda-forge/win-64/yaml-0.2.5-he774522_0.tar.bz2                                                                                                                                                                                 https://conda.anaconda.org/conda-forge/win-64/zlib-1.2.11-h62dcd97_1010.tar.bz2                                                                                                                                                                             https://conda.anaconda.org/conda-forge/win-64/krb5-1.17.1-hc04afaa_3.tar.bz2                                                                                                                                                                                https://conda.anaconda.org/conda-forge/win-64/libsolv-0.7.16-h200bbdf_0.tar.bz2                                                                                                                                                                             https://conda.anaconda.org/conda-forge/win-64/libssh2-1.9.0-hb06d900_5.tar.bz2                                                                                                                                                                              https://conda.anaconda.org/conda-forge/win-64/libxml2-2.9.10-h1006b36_2.tar.bz2                                                                                                                                                                             https://conda.anaconda.org/conda-forge/win-64/python-3.8.6-h60c2a47_0_cpython.tar.bz2                                                                                                                                                                       https://conda.anaconda.org/conda-forge/win-64/reproc-cpp-14.2.0-h0e60522_0.tar.bz2                                                                                                                                                                          https://conda.anaconda.org/conda-forge/win-64/zstd-1.4.5-h1f3a1b7_2.tar.bz2                                                                                                                                                                                 https://conda.anaconda.org/conda-forge/win-64/libarchive-3.3.3-h793d221_1008.tar.bz2                                                                                                                                                                        https://conda.anaconda.org/conda-forge/win-64/libcurl-7.71.1-h4b64cdc_8.tar.bz2                                                                                                                                                                             https://conda.anaconda.org/conda-forge/win-64/python_abi-3.8-1_cp38.tar.bz2                                                                                                                                                                                 https://conda.anaconda.org/conda-forge/win-64/pywin32-228-py38h1e8a9f7_0.tar.bz2                                                                                                                                                                            https://conda.anaconda.org/conda-forge/win-64/menuinst-1.4.16-py38h32f6830_1.tar.bz2                                                                                                                                                                        https://conda.anaconda.org/conda-forge/win-64/certifi-2020.11.8-py38haa244fe_0.tar.bz2                                                                                                                                                                      https://conda.anaconda.org/conda-forge/win-64/chardet-3.0.4-py38h9bdc248_1008.tar.bz2                                                                                                                                                                       https://repo.anaconda.com/pkgs/main/win-64/console_shortcut-0.1.1-4.conda                                                                                                                                                                                   https://repo.anaconda.com/pkgs/main/win-64/powershell_shortcut-0.0.1-3.conda                                                                                                                                                                                https://conda.anaconda.org/conda-forge/win-64/pycosat-0.6.3-py38hab1e662_1005.tar.bz2                                                                                                                                                                       https://repo.anaconda.com/pkgs/main/win-64/ruamel_yaml-0.15.87-py38he774522_1.conda                                                                                                                                                                         https://conda.anaconda.org/conda-forge/win-64/win_inet_pton-1.1.0-py38h32f6830_1.tar.bz2                                                                                                                                                                    https://conda.anaconda.org/conda-forge/win-64/wincertstore-0.2-py38h32f6830_1005.tar.bz2                                                                                                                                                                    https://conda.anaconda.org/conda-forge/win-64/pysocks-1.7.1-py38h9bdc248_2.tar.bz2                                                                                                                                                                          https://repo.anaconda.com/pkgs/main/win-64/setuptools-50.3.1-py38haa95532_1.conda                                                                                                                                                                           https://conda.anaconda.org/conda-forge/noarch/idna-2.10-pyh9f0ad1d_0.tar.bz2                                                                                                                                                                                https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-pyh9f0ad1d_2.tar.bz2                                                                                                                                                                           https://conda.anaconda.org/conda-forge/win-64/cffi-1.14.3-py38h0e640b1_1.tar.bz2                                                                                                                                                                            https://conda.anaconda.org/conda-forge/win-64/brotlipy-0.7.0-py38hab1e662_1001.tar.bz2                                                                                                                                                                      https://conda.anaconda.org/conda-forge/noarch/requests-2.25.0-pyhd3deb0d_0.tar.bz2                                                                                                                                                                          https://conda.anaconda.org/conda-forge/noarch/six-1.15.0-pyh9f0ad1d_0.tar.bz2                                                                                                                                                                               https://conda.anaconda.org/conda-forge/win-64/cryptography-3.2.1-py38hd8c33c5_0.tar.bz2                                                                                                                                                                     https://conda.anaconda.org/conda-forge/win-64/pyopenssl-19.1.0-py38_0.tar.bz2                                                                                                                                                                               https://conda.anaconda.org/conda-forge/noarch/tqdm-4.51.0-pyh9f0ad1d_0.tar.bz2                                                                                                                                                                              https://conda.anaconda.org/conda-forge/win-64/conda-package-handling-1.7.2-py38h8934438_0.tar.bz2                                                                                                                                                           https://conda.anaconda.org/conda-forge/win-64/conda-4.9.2-py38haa244fe_0.tar.bz2                                                                                                                                                                            https://conda.anaconda.org/conda-forge/win-64/mamba-0.7.0-py38he5b3c69_0.tar.bz2                                                                                                                                                                            https://conda.anaconda.org/conda-forge/noarch/urllib3-1.25.11-py_0.tar.bz2                                                                                                                                                                                  https://conda.anaconda.org/conda-forge/noarch/wheel-0.35.1-pyh9f0ad1d_0.tar.bz2                                                                                                                                                                             https://conda.anaconda.org/conda-forge/noarch/pip-20.2.4-py_0.tar.bz2                 
```

My system is Win 10 Pro Version 10.0.18363 Build 18363

**Comment by wolfv** [comment]
Okay, I was able to recreate it in a container.

I used stefanscherer/chocolatey, then installed `choco install miniconda3`, used that to install `conda install mamba -c conda-forge --strict-channel-priority` and running `mamba create -n tense xtensor -c conda-forge` crashes with the same issue.

**Comment by isuruf** [comment]
To debug this, run `depends.exe` on the conda activated environment and see if the `mamba_api.pyd` file gives errors when loaded in `depends.exe`

**Comment by olivier-lacroix** [comment]
@isuruf , it does. but so does it for version 0.6.4 so I may be doing something wrong here...

**Comment by dhirschfeld** [comment]
Since I could repro in a `miniconda` container I tried with one which includes the vs buildtools so I could use the `dumpbin` utility:
```
C:\Miniconda\Lib\site-packages\mamba>dumpbin /dependents mamba_api.cp37-win_amd64.pyd
Microsoft (R) COFF/PE Dumper Version 14.27.29112.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file mamba_api.cp37-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    archive.dll
    solv.dll
    solvext.dll
    reproc++.dll
    libcurl.dll
    libcrypto-1_1-x64.dll
    python37.dll
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll

  Summary

       16000 .data
        8000 .pdata
       43000 .rdata
        1000 .reloc
        1000 .rsrc
       C6000 .text
```

...unfortunately in this container `mamba` works just fine :/

**Comment by wolfv** [comment]
Ok i managed to use Dependencies.exe (the new kind of depends.exe) from choco in the container. Unfortunately can't really copy from the terminal :/

At the end it seems to look for MSVCP140**D**.dll an other `*d` libs. Could it be that these are debug versions of the libraries? That would explain why it works on some machiens. Or is this related to `/MD` vs `/MT`?

![image](https://user-images.githubusercontent.com/885054/99146395-fd71f600-2677-11eb-9f91-01560d0f6e05.png)


![image](https://user-images.githubusercontent.com/885054/99146374-c3a0ef80-2677-11eb-8235-31b17a1007f6.png)

**Comment by wolfv** [comment]
looks like I forgot to add `-DBUILD_TYPE=Release` here: https://github.com/conda-forge/reproc-feedstock/blob/f5da9d45807c5bb739c30cdab530145242756f5d/recipe/bld_c.bat#L11-L18

so that it apparently links to debug libraries. What do you think @dhirschfeld ?

**Comment by dhirschfeld** [comment]
Yeah, I don't think it should be depending on the debug libraries! I'm no expert in C++ or CMAKE but the fix *sounds* right...

**Comment by dhirschfeld** [comment]
That would also explain why it worked on my desktop and in a container with all the dev tools installed but failed in a vanilla container

**Comment by wolfv** [comment]
Hmm, I have to say ldd in cygwin might be my favorite:

```
Wolf Vollprecht@LAPTOP-7GSEN6I8 MINGW64 ~/Programs/reproc/build/reproc/lib (master)
$ ldd reproc.dll
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffe74340000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ffe73740000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ffe716e0000)
        apphelp.dll => /c/Windows/SYSTEM32/apphelp.dll (0x7ffe6a860000)
        WS2_32.dll => /c/Windows/System32/WS2_32.dll (0x7ffe729b0000)
        RPCRT4.dll => /c/Windows/System32/RPCRT4.dll (0x7ffe72560000)
        ucrtbase.dll => /c/Windows/System32/ucrtbase.dll (0x7ffe712c0000)
        VCRUNTIME140.dll => /c/Windows/SYSTEM32/VCRUNTIME140.dll (0x7ffe581d0000)
```

Anyways, I fixed the reproc recipe and going to make a new release shortly! Hopefully mamba won't crash anymore after that.

**Comment by wolfv** [comment]
@olivier-lacroix could you try again with mamba 0.7.1? Thanks!

**Comment by olivier-lacroix** [comment]
@wolfv , I can confirm it is resolved with 0.7.1
Thanks all for diagnosing and solving this issue this quickly!

**Comment by marscher** [comment]
On Python-3.8, win10 (container, 64bit) it crashes again, importing the binary extension. It seems to be an regression, since mamba is version 0.7.12.

Detailed output can be found here:
https://ci.appveyor.com/project/BAMWelDX/weldx/builds/37685084

**Comment by wolfv** [comment]
Thanks @marscher for reporting. I will check, but nothing on mamba side has changed, concerning this, as far as I am aware :/

One alternative, potentially even faster, could be to try micromamba. Since it is statically linked, you should not face issues like this. 

The provision-with-micromamba github action makes it's usage very simple (you can check the source code of that action for an idea on how to use micromamba on other CI services).

I'll try to have a look at these DLL problems. Just for confirmation, you didn't see that on other CI providers, right? Also, you're modifying the %PATH% in appveyor, correct?

**Comment by isuruf** [comment]
@marscher, you need to call `conda activate` beforehand. (Or add `C:\Miniconda38-x64\Library\bin` and other various paths that conda adds to `PATH`

**Comment by marscher** [comment]
With a call to conda activate it works like a charm. Thanks for the quick feedback. This can be closed again, I guess.

**Comment by wolfv** [comment]
Great! Thanks @isuruf and @marscher .
