### ISSUE TITLE
magic-wormhole: conda create works, mamba create fails

### ISSUE THREAD

**Issue by ericdill** [mamba-org/mamba#610]
Hey @wolfv, 

Came across a situation where the `mamba create -n wormhole magic-wormhole -y` appears to create an environment properly, but `python -c "import wormhole"` fails. `conda create -n wormhole2 magic-wormhole -y` produces an environment where `python -c "import wormhole"` works. Figured you might want to dig into this one a bit? Feel free to close if you're not interested!

```
$ python -c "import wormhole"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'wormhole'
```

Steps to reproduce.
1. On a mac
2. mamba 0.6.4 / conda 4.9.0
3. `mamba create -n wormhole magic-wormhole -y` creates a python 3.6 environment, oddly.
4. `conda create -n wormhole2 magic-wormhole -y` creates a python 3.9 environment
5. `mamba create -n wormhole3 magic-wormhole 'python>=3.8' -y` creates a python 3.9 environment.

The difference between environments created in steps 3 and 4 are minimal.

The environments created in steps 4 and 5 are identical. It seems that mamba may not be unpacking something correctly? I'm not totally sure.

**env from: `mamba create -n wormhole magic-wormhole -y`**
```
https://conda.anaconda.org/conda-forge/noarch/attrs-20.3.0-pyhd3deb0d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/autobahn-20.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/automat-20.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/constantly-15.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/humanize-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/hyperlink-20.0.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.10-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/incremental-17.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/magic-wormhole-0.12.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-20.2.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.8-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-pyh9f0ad1d_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyhamcrest-2.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/service_identity-18.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/six-1.15.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tqdm-4.53.0-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/txaio-20.3.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.35.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/bcrypt-3.2.0-py36h9de38fb_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2020.11.8-h033912b_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/certifi-2020.11.8-py36h79c6626_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cffi-1.14.3-py36hbc48b12_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cryptography-3.2.1-py36h564ae50_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/hkdf-0.0.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-11.0.0-h439d374_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.2.1-hb1e8313_1007.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libsodium-1.0.18-hbcb3906_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ncurses-6.2-h2e338ed_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.1.1h-haf1e3a3_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pynacl-1.4.0-py36h9de38fb_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pyopenssl-19.1.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-3.6.11-hc38f9c5_2_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.6-1_cp36m.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/readline-8.0-h0678c8f_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/setuptools-49.6.0-py36h2432673_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/spake2-0.8-0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.33.0-h960bd1c_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.10-hb0a8c7a_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/twisted-20.3.0-py36h9de38fb_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.5-haf1e3a3_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.11-h7795811_1010.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zope.interface-5.2.0-py36h6941dd6_0.tar.bz2
```

**env from: `conda create -n wormhole2 magic-wormhole -y`**
```
https://conda.anaconda.org/conda-forge/noarch/attrs-20.3.0-pyhd3deb0d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/autobahn-20.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/automat-20.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/constantly-15.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/hkdf-0.0.3-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/humanize-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/hyperlink-20.0.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.10-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/incremental-17.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/magic-wormhole-0.12.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-20.2.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.8-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-pyh9f0ad1d_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyhamcrest-2.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-19.1.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/service_identity-18.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/six-1.15.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/spake2-0.8-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tqdm-4.53.0-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/txaio-20.3.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tzdata-2020d-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.35.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/bcrypt-3.2.0-py39hb5aae12_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2020.11.8-h033912b_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/certifi-2020.11.8-py39h6e9494a_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cffi-1.14.3-py39h5f57d53_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cryptography-3.2.1-py39hed2902a_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-11.0.0-h439d374_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.2.1-hb1e8313_1007.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libsodium-1.0.18-hbcb3906_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ncurses-6.2-h2e338ed_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.1.1h-haf1e3a3_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pynacl-1.4.0-py39hb5aae12_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-3.9.0-ha017127_4_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.9-1_cp39.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/readline-8.0-h0678c8f_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/setuptools-49.6.0-py39h2c36a5b_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.33.0-h960bd1c_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.10-hb0a8c7a_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/twisted-20.3.0-py39hb5aae12_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.5-haf1e3a3_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.11-h7795811_1010.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zope.interface-5.2.0-py39h5a22ff9_0.tar.bz2
```

**env from: `mamba create -n wormhole3 magic-wormhole 'python>=3.8' -y`**
```
https://conda.anaconda.org/conda-forge/noarch/attrs-20.3.0-pyhd3deb0d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/autobahn-20.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/automat-20.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/constantly-15.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/hkdf-0.0.3-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/humanize-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/hyperlink-20.0.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.10-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/incremental-17.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/magic-wormhole-0.12.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-20.2.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.8-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-pyh9f0ad1d_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyhamcrest-2.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-19.1.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/service_identity-18.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/six-1.15.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tqdm-4.53.0-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/txaio-20.3.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tzdata-2020d-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.35.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/bcrypt-3.2.0-py39hb5aae12_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2020.11.8-h033912b_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/certifi-2020.11.8-py39h6e9494a_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cffi-1.14.3-py39h5f57d53_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cryptography-3.2.1-py39hed2902a_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-11.0.0-h439d374_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.2.1-hb1e8313_1007.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libsodium-1.0.18-hbcb3906_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ncurses-6.2-h2e338ed_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.1.1h-haf1e3a3_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pynacl-1.4.0-py39hb5aae12_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-3.9.0-ha017127_4_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.9-1_cp39.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/readline-8.0-h0678c8f_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/setuptools-49.6.0-py39h2c36a5b_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/spake2-0.8-0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.33.0-h960bd1c_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.10-hb0a8c7a_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/twisted-20.3.0-py39hb5aae12_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.5-haf1e3a3_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.11-h7795811_1010.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zope.interface-5.2.0-py39h5a22ff9_0.tar.bz2
```

**Comment by wolfv** [comment]
hey,thanks

we can debug the solutions using `-vvv`. Now we can see why the solver does what.

Interestingly, we can see:

```
prune_to_best_version 21
- pynacl-1.0.1-py27_0 [86714]
- pynacl-1.0.1-py35_0 [86715]
- pynacl-1.0.1-py36_0 [86716]
- pynacl-1.1.2-py27_0 [86717]
- pynacl-1.1.2-py35_0 [86718]
- pynacl-1.1.2-py36_0 [86719]
- pynacl-1.3.0-py27_0 [86720]
- pynacl-1.3.0-py27h14c3975_1000 [86721]
- pynacl-1.3.0-py27h470a237_0 [86722]
- pynacl-1.3.0-py27h516909a_1001 [86723]
- pynacl-1.3.0-py36_0 [86724]
- pynacl-1.3.0-py36h14c3975_1000 [86725]
- pynacl-1.3.0-py36h470a237_0 [86726]
- pynacl-1.3.0-py36h516909a_1001 [86727]
- pynacl-1.3.0-py37h14c3975_1000 [86728]
- pynacl-1.3.0-py37h470a237_0 [86729]
- pynacl-1.3.0-py37h516909a_1001 [86730]
- pynacl-1.3.0-py38h516909a_1001 [86731]
- pynacl-1.4.0-py36h8c4c3a4_0 [86732]
- pynacl-1.4.0-py36h8c4c3a4_1 [86733]
- pynacl-1.4.0-py36h8c4c3a4_2 [86734]
installing pynacl-1.4.0-py36h8c4c3a4_2
```

that for pynacl 1.4 we only got python 3.6 builds. weird! That's why mamba chooses python 3.6 since it's  a backtracking solver and nothing constrains python otherwise.

Okay, I am getting called to dinner right now -- will have to debug this further later on.

**Comment by wolfv** [comment]
actually what I wrote up there isn't true as conda / mamba search show versions of pynacl for python 3.8 and 3.9... I need to investigate :)

**Comment by RaverJay** [comment]
Ran into this today, after `mamba install magic-wormhole` into my base miniconda3 env:

```
$> wormhole
Traceback (most recent call last):
  File "/home/ya86gul/miniconda3/bin/wormhole", line 6, in <module>
    from wormhole.cli.cli import wormhole
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/wormhole/__init__.py", line 2, in <module>
    from .wormhole import create, __version__
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/wormhole/wormhole.py", line 11, in <module>
    from ._boss import Boss
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/wormhole/_boss.py", line 15, in <module>
    from ._dilation.manager import Dilator
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/wormhole/_dilation/manager.py", line 22, in <module>
    from .._key import derive_key
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/wormhole/_key.py", line 12, in <module>
    from spake2 import SPAKE2_Symmetric
ModuleNotFoundError: No module named 'spake2'
```

But spake2 is clearly in the env:

```
$> conda list
...
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0                     py_0  
spake2                    0.8                           0    conda-forge
spectra                   0.0.11                     py_1    conda-forge
sqlite                    3.27.2               h7b6447c_0  
...
```

And now it appears this env is totally blasted:

```
$> conda uninstall magic-wormhole
Collecting package metadata (repodata.json): done
Solving environment: - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::python==3.7.3=h0371630_0
  - conda-forge/noarch::attrs==20.3.0=pyhd3deb0d_0
  - defaults/noarch::backcall==0.2.0=py_0
  - defaults/linux-64::chardet==3.0.4=py37_1003
  - defaults/noarch::click==7.1.2=py_0
...
```

The list goes on and on O_O

**Comment by RaverJay** [comment]
reverted my env, then ran

```
$> conda install magic-wormhole
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ya86gul/miniconda3

  added / updated specs:
    - magic-wormhole


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bcrypt-3.2.0               |   py37h5e8e339_1          44 KB  conda-forge
    libsodium-1.0.18           |       h36c2ea0_1         366 KB  conda-forge
    pyasn1-modules-0.2.7       |             py_0          60 KB  conda-forge
    pynacl-1.4.0               |   py37h5e8e339_2         1.3 MB  conda-forge
    spake2-0.8                 |             py_3          37 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following NEW packages will be INSTALLED:

  attrs              conda-forge/noarch::attrs-20.3.0-pyhd3deb0d_0
  autobahn           conda-forge/noarch::autobahn-21.2.1-pyhd8ed1ab_0
  automat            conda-forge/noarch::automat-20.2.0-py_0
  bcrypt             conda-forge/linux-64::bcrypt-3.2.0-py37h5e8e339_1
  constantly         conda-forge/noarch::constantly-15.1.0-py_0
  hkdf               conda-forge/noarch::hkdf-0.0.3-py_2
  humanize           conda-forge/noarch::humanize-3.2.0-pyhd8ed1ab_0
  hyperlink          conda-forge/noarch::hyperlink-21.0.0-pyhd3deb0d_0
  incremental        conda-forge/noarch::incremental-17.5.0-py_0
  libsodium          conda-forge/linux-64::libsodium-1.0.18-h36c2ea0_1
  magic-wormhole     conda-forge/noarch::magic-wormhole-0.12.0-pyh9f0ad1d_0
  pip                conda-forge/noarch::pip-21.0.1-pyhd8ed1ab_0
  pyasn1             conda-forge/noarch::pyasn1-0.4.8-py_0
  pyasn1-modules     conda-forge/noarch::pyasn1-modules-0.2.7-py_0
  pyhamcrest         conda-forge/noarch::pyhamcrest-2.0.2-py_0
  pynacl             conda-forge/linux-64::pynacl-1.4.0-py37h5e8e339_2
  service_identity   conda-forge/noarch::service_identity-18.1.0-py_0
  spake2             conda-forge/noarch::spake2-0.8-py_3
  twisted            conda-forge/linux-64::twisted-20.3.0-py37h5e8e339_2
  txaio              conda-forge/noarch::txaio-21.2.1-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  zope.interface     conda-forge/linux-64::zope.interface-5.2.0-py37h5e8e339_1

The following packages will be UPDATED:

  openssl                                 1.1.1i-h7f98852_0 --> 1.1.1j-h7f98852_0


Proceed ([y]/n)? y
```

and that worked.

Compare to mamba's package plan:

```
Transaction

  Prefix: /home/ya86gul/miniconda3

  Updating specs:

   - magic-wormhole


  Package             Version  Build           Channel                    Size
────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────

  attrs                20.3.0  pyhd3deb0d_0    conda-forge/noarch       Cached
  autobahn             21.2.1  pyhd8ed1ab_0    conda-forge/noarch       274 KB
  automat              20.2.0  py_0            conda-forge/noarch        30 KB
  bcrypt                3.2.0  py37h8f50634_1  conda-forge/linux-64      44 KB
  constantly           15.1.0  py_0            conda-forge/noarch         9 KB
  hkdf                  0.0.3  py_2            conda-forge/noarch         7 KB
  humanize              3.2.0  pyhd8ed1ab_0    conda-forge/noarch        38 KB
  hyperlink            21.0.0  pyhd3deb0d_0    conda-forge/noarch        71 KB
  incremental          17.5.0  py_0            conda-forge/noarch        14 KB
  libsodium            1.0.18  h516909a_1      conda-forge/linux-64     366 KB
  magic-wormhole       0.12.0  pyh9f0ad1d_0    conda-forge/noarch       137 KB
  pip                  21.0.1  pyhd8ed1ab_0    conda-forge/noarch       Cached
  pyasn1                0.4.8  py_0            conda-forge/noarch       Cached
  pyasn1-modules        0.2.8  py_0            pkgs/main/noarch         Cached
  pyhamcrest            2.0.2  py_0            conda-forge/noarch        29 KB
  pynacl                1.4.0  py37h8f50634_2  conda-forge/linux-64       1 MB
  service_identity     18.1.0  py_0            conda-forge/noarch        12 KB
  spake2                  0.8  0               conda-forge/linux-64      65 KB
  twisted              20.3.0  py37h5e8e339_2  conda-forge/linux-64       5 MB
  txaio                21.2.1  pyhd8ed1ab_0    conda-forge/noarch        21 KB
  wheel                0.36.2  pyhd3deb0d_0    conda-forge/noarch       Cached
  zope.interface        5.2.0  py37h5e8e339_1  conda-forge/linux-64     293 KB

  Upgrade:
────────────────────────────────────────────────────────────────────────────────

  ca-certificates   2020.12.5  ha878542_0      installed                      
  ca-certificates   2021.1.19  h06a4308_0      pkgs/main/linux-64       Cached
  openssl              1.1.1i  h7f98852_0      installed                      
  openssl              1.1.1j  h7f98852_0      conda-forge/linux-64     Cached

  Summary:

  Install: 22 packages
  Upgrade: 2 packages

  Total download: 8 MB
```

**Comment by wolfv** [comment]
@raverjay i think it would be better to create new environments (also makes it easier to _wipe_ them afterwards).

The package plans on a first glance look pretty similar, so I am not sure why one should work vs the other. Any ideas?

For creating new envs: `conda / mamba create -n testenv magic-wormhole ...; conda activate magic-wormhole`

**Comment by RaverJay** [comment]
Surely that would be more reasonable, but I can't shake the desire to have the day-to-day things in my base :D

At least the spake2 builds are different, does that matter?
Also there is this: https://github.com/magic-wormhole/magic-wormhole/issues/405

**Comment by jonashaag** [comment]
I‘m closing this due to inactivity. Let me know if we should reopen.
