### ISSUE TITLE
Mamba frequently crashes

### ISSUE THREAD

**Issue by DavidMertz** [mamba-org/mamba#715]
When Mamba succeeds it is many times faster than conda.  But for me, it crashes about 50% of the time I try to use it (for all the various operations: creating environments, removing them, installing or removing packages, etc).

The SSL complaint is common, but not universal.  Moreover, if this is the only underlying issue, I'd expect to succeed *never* not 50% of the time.  Moreover, while conda is painfully slow, it NEVER makes the same SSL cert complaint.

```
% mamba --version
mamba 0.7.14
conda 4.9.2

% uname -a
Linux popkdm 5.8.0-7630-generic #32~1606339263~20.10~61c3910-Ubuntu SMP Thu Nov 26 00:10:35 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

For example:

```
% mamba env create

EnvironmentFileNotFound: '/home/dmertz/git/cleaning-data/environment.yml' file not found

(Pearson-PyTorch) 1351-cleaning-data [main|✚ 2…1]
% mamba env create -f environment-test.yml
intel/linux-64           [====================] (00m:06s) 0 Failed
r/linux-64               [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
intel/noarch             [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
conda-forge/linux-64     [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
conda-forge/noarch       [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
r/noarch                 [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
bioconda/linux-64        [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
bioconda/noarch          [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
pkgs/main/linux-64       [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
pkgs/main/noarch         [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
pkgs/r/linux-64          [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
pkgs/r/noarch            [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
davidmertz/linux-64      [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)
davidmertz/noarch        [>] (00m:06s) Problem with the SSL CA cert (path? access rights?)

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/dmertz/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/dmertz/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/dmertz/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 118, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/dmertz/miniconda3/lib/python3.9/site-packages/mamba/mamba_env.py", line 42, in mamba_install
        index = load_channels(
      File "/home/dmertz/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 93, in load_channels
        index = get_index(
      File "/home/dmertz/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 74, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Download error (77) Problem with the SSL CA cert (path? access rights?) [https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/repodata.json]

`$ /home/dmertz/miniconda3/condabin/mamba create -f environment-test.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
   CONDA_BACKUP_ADDR2LINE=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          addr2line
          CONDA_BACKUP_AR=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-ar
          CONDA_BACKUP_AS=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-as
       CONDA_BACKUP_BUILD=x86_64-conda-linux-gnu
          CONDA_BACKUP_CC=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-cc
CONDA_BACKUP_CC_FOR_BUILD=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-cc
      CONDA_BACKUP_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
CONDA_BACKUP_CMAKE_PREFIX_PATH=/home/dmertz/miniconda3/envs/cleaning3.9:/home/dmertz/miniconda3/envs/
                          cleaning3.9/x86_64-conda-linux-gnu/sysroot/usr
CONDA_BACKUP_CONDA_BUILD_SYSROOT=/home/dmertz/miniconda3/envs/cleaning3.9/x86_64-conda-linux-
                          gnu/sysroot
         CONDA_BACKUP_CPP=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          cpp
    CONDA_BACKUP_CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
         CONDA_BACKUP_CXX=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-
                          gnu-c++
     CONDA_BACKUP_CXXFILT=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-
                          gnu-c++filt
    CONDA_BACKUP_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0
                          -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
CONDA_BACKUP_CXX_FOR_BUILD=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-
                          gnu-c++
CONDA_BACKUP_DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
CONDA_BACKUP_DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
CONDA_BACKUP_DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0
                          -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
CONDA_BACKUP_DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
CONDA_BACKUP_DEBUG_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
     CONDA_BACKUP_ELFEDIT=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          elfedit
         CONDA_BACKUP_F77=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gfortran
         CONDA_BACKUP_F90=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gfortran
         CONDA_BACKUP_F95=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-
                          gnu-f95
          CONDA_BACKUP_FC=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gfortran
      CONDA_BACKUP_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
CONDA_BACKUP_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /home/dmertz/miniconda3/envs/cleaning3.9/include
         CONDA_BACKUP_GCC=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gcc
      CONDA_BACKUP_GCC_AR=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gcc-ar
      CONDA_BACKUP_GCC_NM=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gcc-nm
  CONDA_BACKUP_GCC_RANLIB=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gcc-ranlib
    CONDA_BACKUP_GFORTRAN=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gfortran
       CONDA_BACKUP_GPROF=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          gprof
         CONDA_BACKUP_GXX=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-
                          gnu-g++
        CONDA_BACKUP_HOST=x86_64-conda-linux-gnu
          CONDA_BACKUP_LD=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-ld
     CONDA_BACKUP_LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,
                          --disable-new-dtags -Wl,--gc-sections
                          -Wl,-rpath,/home/dmertz/miniconda3/envs/cleaning3.9/lib -Wl,-rpath-
                          link,/home/dmertz/miniconda3/envs/cleaning3.9/lib
                          -L/home/dmertz/miniconda3/envs/cleaning3.9/lib
     CONDA_BACKUP_LD_GOLD=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          ld.gold
          CONDA_BACKUP_NM=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-nm
     CONDA_BACKUP_OBJCOPY=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          objcopy
     CONDA_BACKUP_OBJDUMP=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          objdump
      CONDA_BACKUP_RANLIB=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          ranlib
     CONDA_BACKUP_READELF=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          readelf
        CONDA_BACKUP_SIZE=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          size
     CONDA_BACKUP_STRINGS=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          strings
       CONDA_BACKUP_STRIP=/home/dmertz/miniconda3/envs/cleaning3.9/bin/x86_64-conda-linux-gnu-
                          strip
CONDA_BACKUP__CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
 CONDA_BACKUP_build_alias=x86_64-conda-linux-gnu
  CONDA_BACKUP_host_alias=x86_64-conda-linux-gnu
        CONDA_DEFAULT_ENV=Pearson-PyTorch
                CONDA_EXE=/home/dmertz/miniconda3/bin/conda
             CONDA_PREFIX=/home/dmertz/miniconda3/envs/Pearson-PyTorch
    CONDA_PROMPT_MODIFIER=(Pearson-PyTorch)
         CONDA_PYTHON_EXE=/home/dmertz/miniconda3/bin/python
               CONDA_ROOT=/home/dmertz/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
            DEFAULTS_PATH=/usr/share/gconf/gnome.default.path
           MANDATORY_PATH=/usr/share/gconf/gnome.mandatory.path
                     PATH=/home/dmertz/miniconda3/envs/Pearson-PyTorch/bin:/home/dmertz/.poetry/
                          bin:/home/dmertz/perl5/bin:/home/dmertz/bin:/home/dmertz/.local/bin:/h
                          ome/dmertz/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbi
                          n:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/d
                          art/bin
               PYTHONPATH=
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
 TMUX_PLUGIN_MANAGER_PATH=/home/dmertz/.tmux/plugins/
               WINDOWPATH=2

     active environment : Pearson-PyTorch
    active env location : /home/dmertz/miniconda3/envs/Pearson-PyTorch
            shell level : 1
       user config file : /home/dmertz/.condarc
 populated config files : /home/dmertz/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __glibc=2.32=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/dmertz/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/davidmertz/linux-64
                          https://conda.anaconda.org/davidmertz/noarch
          package cache : /home/dmertz/miniconda3/pkgs
                          /home/dmertz/.conda/pkgs
       envs directories : /home/dmertz/miniconda3/envs
                          /home/dmertz/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.9.2 Linux/5.8.0-7630-generic pop/20.10 glibc/2.32
                UID:GID : 1000:1000
             netrc file : /home/dmertz/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by wolfv** [comment]
Are you mixing channels/have a dirty bad environment?

Please make sure curl and OpenSSL are recent and come from conda forge (use strict channel priority).

Also mamba needs to live in the base env.

I see that you're using pytorch which might still use track_features instead of mutex packages to differentiate gpu/cpu packages (I need to check, not sure what the current state is). Track features aren't supported with mamba and won't be (deprecated in conda as well).

**Comment by DavidMertz** [comment]
@wolfv I'm confused by some of your comments, but others I can clarify:

```
% which mamba
/home/dmertz/miniconda3/condabin/mamba
```

So base env install.  The particular environment I tried to create for this example does not contain pytorch.  For some reason, the error log decided to display information about another environment that did (oh, I guess because I was in that PyTorch environment when I did the `mamba env create`).

Yes, I need libraries from several channels. Is there any way of guessing what restrictions apply about that?!

**Comment by DavidMertz** [comment]
I do I convince mamba to use the conda base `curl` rather than system `curl`:

**Comment by wolfv** [comment]
I think your comment got cut off.

But we might be getting closer to the root of the problem. Maybe it's loading the wrong shared libraries that don't come from your base env when you execute mamba with another env activated? 

Does mamba work reliably from the base env and with base env activated? 

I guess once we make 'mamba' a shell command (similar to conda) we can also fiddle with the path (instead of running mamba from 'condabin').

You could check with 'ldd' which dynamic libraries are linked. And the output of conda list would also be interesting to see from where the binaries are installed.

Last but not least if you're using conda-forge you should always use strict channel priority. Mixing channels isn't really supported since there can be binary incompatibilities, at least for low level stuff.

You might also want to check out mambaforge if you want to start from a clean slate.

**Comment by DavidMertz** [comment]
Hmm... there **is** a different location in base than by default.  It doesn't fix it, but the path changes:

```
(base) 3689-tmp % which mamba
/home/dmertz/miniconda3/bin/mamba
(base) 3690-tmp % mamba --version
mamba 0.7.14
conda 4.9.2
(base) 3691-tmp % mamba env create -f environment-mamba.yml
conda-forge/noarch       [>                  ] (00m:06s) Problem with the SSL CA cert (path? access rights?)
...
```

**Comment by DavidMertz** [comment]
It doesn't look like mamba is dynamically linked:

```
(base) 3693-tmp % ldd `which mamba`
        not a dynamic executable
```

**Comment by DavidMertz** [comment]
Also:

```
(base) 3704-tmp % conda list mamba
# packages in environment at /home/dmertz/miniconda3:
#
# Name                    Version                   Build  Channel
mamba                     0.7.14           py37h7f483ca_0    conda-forge
```

**Comment by DavidMertz** [comment]
So... this isn't a solution I **love**, but it is one that works.  If I run this:

```
conda config --set ssl_verify false
```

My problems with mamba go away (at least on initial efforts).  Of course, not verifying SSL certs means.... I'm not verifying SSL certs. So there's that.

**Comment by wolfv** [comment]
the python extension is `mamba_api` in your `lib/python3.x/site-packages/mamba/..` folder (which you could run ldd on).

For conda list it would be great to see the complete output (or at least the dependencies relevant to the problem at hand (curl, openssl...). Those dependencies should come from conda-forge (there are no strong binary compatibility guarantees across channels).

I think I know the fix to the cache invalidation issue you're describing.

**Comment by DavidMertz** [comment]
I'm not certain what is expected here, but this is mine:

```
% lss $HOME/miniconda3/lib/python3.7/site-packages/mamba/mamba_api*
Command 'lss' not found, did you mean:
  command 'lsw' from deb suckless-tools (45-1)
  command 'gss' from deb libgss-dev (1.0.3-4)
  command 'iss' from deb insilicoseq (1.4.6-1)
  command 'lssu' from deb nilfs-tools (2.2.8-1)
  command 'ss' from deb iproute2 (5.7.0-1ubuntu1)
  command 'ls' from deb coreutils (8.32-3ubuntu1)
  command 'lrs' from deb lrslib (0.71-6)
  command 'lsns' from deb util-linux (2.36-3ubuntu1)
  command 'lsc' from deb livescript (1.6.0+dfsg-1)
  command 'lsm' from deb lsm (1.0.4-1)
  command 'ass' from deb irpas (0.10-7)
  command 'les' from deb atm-tools (1:2.5.1-4)
  command 'less' from deb less (551-2)
  command 'lvs' from deb lvm2 (2.03.07-1ubuntu3)
  command 'lsh' from deb lsh-client (2.1-12build4)
Try: sudo apt install <deb name>
(base) 1425-PyTorch-webinar [master|✚ 8]
% ldd $HOME/miniconda3/lib/python3.7/site-packages/mamba/mamba_api*
        linux-vdso.so.1 (0x00007ffc3b0ca000)
        libarchive.so.13 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../libarchive.so.13 (0x00007f938a60a000)
        libsolv.so.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../libsolv.so.1 (0x00007f938a56f000)
        libsolvext.so.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../libsolvext.so.1 (0x00007f938a557000)
        libreproc++.so.14 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../libreproc++.so.14 (0x00007f938a551000)
        libcurl.so.4 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../libcurl.so.4 (0x00007f938a4c2000)
        libcrypto.so.1.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../libcrypto.so.1.1 (0x00007f938a1f4000)
        libstdc++.so.6 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../libstdc++.so.6 (0x00007f938a07f000)
        libgcc_s.so.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../libgcc_s.so.1 (0x00007f938a06b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f938a028000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9389e3e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f938a83e000)
        libiconv.so.2 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libiconv.so.2 (0x00007f9389d56000)
        liblzo2.so.2 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././liblzo2.so.2 (0x00007f9389d11000)
        liblzma.so.5 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././liblzma.so.5 (0x00007f9389ce8000)
        libzstd.so.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libzstd.so.1 (0x00007f9389c2d000)
        liblz4.so.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././liblz4.so.1 (0x00007f9389bf9000)
        libbz2.so.1.0 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libbz2.so.1.0 (0x00007f9389be3000)
        libz.so.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libz.so.1 (0x00007f9389bc9000)
        libxml2.so.2 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libxml2.so.2 (0x00007f9389a61000)
        libreproc.so.14 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libreproc.so.14 (0x00007f9389a58000)
        libnghttp2.so.14 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libnghttp2.so.14 (0x00007f9389a2f000)
        libssh2.so.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libssh2.so.1 (0x00007f93899eb000)
        libssl.so.1.1 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libssl.so.1.1 (0x00007f9389959000)
        libgssapi_krb5.so.2 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libgssapi_krb5.so.2 (0x00007f938990a000)
        libkrb5.so.3 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libkrb5.so.3 (0x00007f9389831000)
        libk5crypto.so.3 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libk5crypto.so.3 (0x00007f9389812000)
        libcom_err.so.3 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././libcom_err.so.3 (0x00007f938980c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9389801000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f93897f9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f93896aa000)
        libicuuc.so.68 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../././libicuuc.so.68 (0x00007f93894c0000)
        libkrb5support.so.0 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../../././libkrb5support.so.0 (0x00007f93894b1000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f9389494000)
        libicudata.so.68 => /home/dmertz/miniconda3/lib/python3.7/site-packages/mamba/../../.././././libicudata.so.68 (0x00007f9387953000)
```

**Comment by DavidMertz** [comment]
The root environment is likewise all conda-forge stuff:

```
% conda list
# packages in environment at /home/dmertz/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
brotlipy                  0.7.0           py37h5e8e339_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.5           py37hc58025e_0    conda-forge
chardet                   4.0.0            py37h89c1867_1    conda-forge
conda                     4.9.2            py37h89c1867_0    conda-forge
conda-package-handling    1.7.2            py37hb5d75c8_0    conda-forge
cryptography              3.4.4            py37hf1a17b8_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
decorator                 4.4.2                      py_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
ipython                   7.20.0           py37h888b3d9_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py37h89c1867_2    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libarchive                3.5.1                h3f442fb_1    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libsolv                   0.7.17               h780b84a_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.7.14           py37h7f483ca_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1j               h7f98852_0    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycosat                   0.6.3           py37h5e8e339_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.8.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py37h89c1867_3    conda-forge
python                    3.7.10          hffdb5ce_100_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
reproc                    14.2.1               h36c2ea0_0    conda-forge
reproc-cpp                14.2.1               h58526e2_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py37h5e8e339_1004    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.58.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
```

**Comment by wolfv** [comment]
looks fine. If you run `mamba` from the base env, does it work fine?

**Comment by DavidMertz** [comment]
@wolfv Nope.  The very same "Problem with the SSL CA cert (path? access rights?)" continues to occur. I have exactly the configuration detailed above. I've tried removing and reinstalling mamba (in the base environment), etc.  Conda finds SSL certs no problem.

**Comment by wolfv** [comment]
Mamba uses curl / libcurl and not requests and so the way they find ssl certificates is different. There are also some environment variables that can influence that (REQUESTS_SSL...) and curl has similar ones.

**Comment by DavidMertz** [comment]
I do not have any such environment variables set (but I'm happy to if it would fix things).:

```
(base) 5798-~ % env | grep -i ssl
(base) 5799-~ % env | grep -i curl
(base) 5800-~ % env | grep -i request
```

**Comment by wolfv** [comment]
Yeah i think that file should be in the ca-certificates package. Maybe that's somehow broken? Force reinstalling might help.

**Comment by DavidMertz** [comment]
Hmmm.... I manually downloaded `https://curl.se/ca/cacert.pem` and moved it to `$HOME/miniconda3/ssl/cacert.pem`.

That gets me past the ""Problem with the SSL CA cert" message.  But then when I run:

```
% time mamba env create -f ~/tmp/environment-mamba.yml
```
For a relatively complex environment I actually use, it first lists a lot of packages, in every case listing them as "Cached" (168 packages, one small one not listed as cached), then afterwards starts Downloading and Extracting them anew.  For the downloads to complete, I think will take a bit over 15 minutes.  So that's better, but still not good.

And the manual:

```
% mv ~/Downloads/cacert.pem /home/dmertz/miniconda3/ssl/
```

Feels fragile, of course.

**Comment by DavidMertz** [comment]
I forced reinstall of curl and certifi several times already.  Only manually copying the file seemed to "fix" it.

**Comment by wolfv** [comment]
for me the `$PREFIX/ssl/cacert.pem` file is in the ca-certificates package:

(excerpt from `find . | grep cacert.pem` in `miniconda3/pkgs/`:

```
./ca-certificates-2020.12.5-ha878542_0/ssl/cacert.pem
./ca-certificates-2020.6.20-hecda079_0/ssl/cacert.pem
./ca-certificates-2020.6.24-0/ssl/cacert.pem
./ca-certificates-2020.11.8-ha878542_0/ssl/cacert.pem
```

I can't tell what exactly happend but for some reason you must have either removed that file from the environment or from the packages cache (since conda list indicated that the package is properly installed).

Regarding the re-download of cached files, that's already fixed in master. We compare the "cleaned" URL now (you're using authenticated channels which makes mamba currently re-download these files).

A release with that fix will come early next week.

**Comment by wolfv** [comment]
I don't think there is anything actionable in here anymore (please correct me if I am wrong). Will close for now.

Hopefully the caching issue is solved with the upcomign release.

Thanks!
