### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by tdegeus** [mamba-org/mamba#723]
```
mamba search frictionqpotfem

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.7.14) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Loading channels: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 60, in __call__
        return cls._thread_local.session
    AttributeError: '_thread._local' object has no attribute 'session'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/mamba/mamba.py", line 882, in exception_converter
        raise e
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/mamba/mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/mamba/mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/mamba/mamba.py", line 714, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/cli/main_search.py", line 73, in execute
        matches = sorted(SubdirData.query_all(spec, channel_urls, subdirs),
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/core/subdir_data.py", line 120, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
        yield fs.pop().result()
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/concurrent/futures/_base.py", line 440, in result
        return self.__get_result()
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
        raise self._exception
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/core/subdir_data.py", line 112, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/core/subdir_data.py", line 125, in query
        self.load()
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/core/subdir_data.py", line 189, in load
        _internal_state = self._load()
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/core/subdir_data.py", line 259, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/core/subdir_data.py", line 485, in fetch_repodata_remote_request
        session = CondaSession()
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 62, in __call__
        session = cls._thread_local.session = super(CondaSessionType, cls).__call__()
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 97, in __init__
        self.headers['User-Agent'] = context.user_agent
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/base/context.py", line 744, in user_agent
        builder.append("%s/%s" % self.os_distribution_name_version)
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/base/context.py", line 786, in os_distribution_name_version
        from .._vendor.distro import id, version
    ImportError: cannot import name 'id' from partially initialized module 'conda._vendor.distro' (most likely due to a circular import) (/home/tdegeus/miniconda3/envs/code_collect_s6g1/lib/python3.9/site-packages/conda/_vendor/distro.py)

`$ /home/tdegeus/miniconda3/envs/code_collect_s6g1/bin/mamba search frictionqpotfem`

  environment variables:
                ALL_PROXY=<set>
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.
                          8.5/gcc-8.3.0-gxl43vsw2ra6mpvv6efabyjohlvn6psh
        CONDA_DEFAULT_ENV=code_collect_s6g1
                CONDA_EXE=/home/tdegeus/miniconda3/bin/conda
             CONDA_PREFIX=/home/tdegeus/miniconda3/envs/code_collect_s6g1
           CONDA_PREFIX_1=/home/tdegeus/miniconda3
    CONDA_PROMPT_MODIFIER=(code_collect_s6g1)
         CONDA_PYTHON_EXE=/home/tdegeus/miniconda3/bin/python
               CONDA_ROOT=/home/tdegeus/miniconda3/envs/code_collect_s6g1
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                EIGENPATH=/home/tdegeus/prog/clone/eigen
                FTP_proxy=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
             INCLUDE_PATH=/home/tdegeus/opt/include:
          LD_LIBRARY_PATH=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.
                          8.5/gcc-8.3.0-gxl43vsw2ra6mpvv6efabyjohlvn6psh/lib64:/ssoft/spack/huma
                          gne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-8.3.0-gxl
                          43vsw2ra6mpvv6efabyjohlvn6psh/lib
                  MANPATH=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.
                          8.5/gcc-8.3.0-gxl43vsw2ra6mpvv6efabyjohlvn6psh/share/man::
               MODULEPATH=/ssoft/spack/humagne/v1/share/spack/lmod/linux-rhel7-x86_E5v4_Mellanox
                          /gcc/8.3.0:/ssoft/spack/stable/share/spack/lmod/linux-
                          rhel7-x86_E5v4_Mellanox/Core
                 NO_PROXY=<set>
                     PATH=/home/tdegeus/miniconda3/envs/code_collect_s6g1/bin:/home/tdegeus/mini
                          conda3/condabin:/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4
                          _Mellanox/gcc-4.8.5/gcc-8.3.0-gxl43vsw2ra6mpvv6efabyjohlvn6psh/bin:/ho
                          me/tdegeus/opt/bin:/home/tdegeus/.local/bin:/usr/lib64/ccache:/usr/loc
                          al/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin
          PKG_CONFIG_PATH=/home/tdegeus/opt/share/pkgconfig:
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
__LMOD_REF_COUNT_CMAKE_PREFIX_PATH=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.
                          8.5/gcc-8.3.0-gxl43vsw2ra6mpvv6efabyjohlvn6psh:1
__LMOD_REF_COUNT_LD_LIBRARY_PATH=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.
                          8.5/gcc-8.3.0-gxl43vsw2ra6mpvv6efabyjohlvn6psh/lib64:1;/ssoft/spack/hu
                          magne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-8.3.0-g
                          xl43vsw2ra6mpvv6efabyjohlvn6psh/lib:1
 __LMOD_REF_COUNT_MANPATH=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.
                          8.5/gcc-8.3.0-gxl43vsw2ra6mpvv6efabyjohlvn6psh/share/man:1
__LMOD_REF_COUNT_MODULEPATH=/ssoft/spack/humagne/v1/share/spack/lmod/linux-rhel7-x86_E5v4_Mellanox
                          /gcc/8.3.0:1;/ssoft/spack/stable/share/spack/lmod/linux-
                          rhel7-x86_E5v4_Mellanox/Core:1
    __LMOD_REF_COUNT_PATH=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.
                          8.5/gcc-8.3.0-gxl43vsw2ra6mpvv6efabyjohlvn6psh/bin:1;/home/tdegeus/opt
                          /bin:1;/home/tdegeus/.local/bin:1;/usr/lib64/ccache:1;/usr/local/bin:1
                          ;/usr/bin:1;/usr/local/sbin:1;/usr/sbin:1;/opt/ibutils/bin:1
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : base
    active env location : /home/tdegeus/miniconda3/envs/code_collect_s6g1
            shell level : 2
       user config file : /home/tdegeus/.condarc
 populated config files : /home/tdegeus/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/tdegeus/miniconda3/envs/code_collect_s6g1  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/tdegeus/miniconda3/envs/code_collect_s6g1/pkgs
                          /home/tdegeus/.conda/pkgs
       envs directories : /home/tdegeus/miniconda3/envs/code_collect_s6g1/envs
                          /home/tdegeus/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.9.2 Linux/3.10.0-957.48.1.el7.x86_64 rhel/7.6 glibc/2.17
                UID:GID : 177478:10532
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by wolfv** [comment]
That's actually an upstream conda issue (https://github.com/conda/conda/issues/10490)

The mamba repoquery command should continue to work fine:

mamba repoquery search ...

**Comment by wolfv** [comment]
closign this one as it's an upstream / conda bug. Thanks though!

**Comment by wolfv** [comment]
equivalent repoquery: `mamba repoquery search frictionqpotfem`

**Comment by tdegeus** [comment]
Thanks @wolfv
