### ISSUE TITLE
[windows] Permission denied errors

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#730]
I just updated to the latest `mamba` and have started seeing unhandled access denied errors.

I'm running in an admin terminal. I rebooted my PC with no luck. I manually deleted the problematic folder (with no apparent trouble) and then `mamba` complained about a different folder.
```
Caught a filesystem error: Access is denied.
: 'C:\Miniconda3\pkgs\pywin32-300-py37hcc03f2d_0'
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 882, in exception_converter
        raise e
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 722, in do_call
        exit_code = update(args, parser)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 640, in update
        return install(args, parser, "update")
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 570, in install
        transaction.log_json()
    RuntimeError: Could not remove directory C:\Miniconda3\pkgs\pywin32-300-py37hcc03f2d_0
```
```
          mamba version : 0.7.14
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.7.9.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
```

I'll try and investigate further - just posting to keep track and in case others are also seeing this...

**Comment by dhirschfeld** [comment]
Reverting to 0.7.12 has *"fixed"* the problem

**Comment by dhirschfeld** [comment]
Possibly related #699?

**Comment by wolfv** [comment]
Hi @dhirschfeld we tried to fix this with the latest release. Please re-open if it still happens!
