### ISSUE TITLE
Truncated JSON file makes mamba unusable

### ISSUE THREAD

**Issue by rgerkin** [mamba-org/mamba#947]
The error is exactly as in #442 and #512, except on a different machine, OS, etc.  A common thread between @mezhaka from #442 and I is that some previous process (possibly from conda or mamba) encountered a full disk and so was not able to finish.  This most likely resulted in something being corrupted.  @siebrenf had a similar story, except stemming from a server disconnect.

Despite claims in the closing of #442, the problem has not been solved since I still observe this in mamba 0.13.0.  I have not yet found any way around it (i.e. making subsequent mamba install commands run successfully), but am hoping to avoid a full conda reinstallation (as @siebrenf reported was needed).

**Comment by jk000** [comment]
I got the same error:
```
critical libmamba Could not read JSON repodata file (/path/to/pkgs/cache/*.json) parse error line 1
```
because one of the channels in my `~/.condarc` was inaccessible (normally accessed through a firewall but I wasn't logged in).  The desired page redirected to a firewall login page, which then got copied into the JSON file making it invalid.

The ordering of the channels in the `.condarc` did not make a difference.

**Comment by jpfeuffer** [comment]
Wow, thank you. That saved me a lot of trouble. I had a local (probably inaccessible) channel in my condarc. Removing it solved the incredibly confusing error.

**Comment by ekungurov** [comment]
Also run into this issue. In my case local Artifactory is the necessary condition to reproduce. 

One of the channels gives 404 for /linux-64 like this:
```
Looking for: ['icu']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
...
artifactory/api/conda/conda-local/idse/linux-64     80.0 B @ 121.0 B/s 404 failed  0.1s
artifactory/api/conda/conda-local/idse/noarch                 No change
```

This is how channels shown in 'mamba info' output:
```
channel URLs : https://conda.anaconda.org/conda-forge/linux-64
               https://conda.anaconda.org/conda-forge/noarch
               ... 
               https://repo.example.org/artifactory/api/conda/conda-local/idse/linux-64
               https://repo.example.org/artifactory/api/conda/conda-local/idse/noarch
```

And global condarc has:
```
channel_priority: flexible
default_channels:
  - conda-forge
  ...
  - https://repo.example.org/artifactory/api/conda/conda-local/idse
```

Mamba 0.19.1 and 0.20.0 is unaffected, and I think that the issue appeared in mama 0.21 or 0.22
Is there a way to workaround it by specifying architecture, or specifying that 'linux-64' is not available?

**Comment by ekungurov** [comment]
The JSON file it is yelling to (in the error message "Could not read JSON repodata file") has the following:
```
{"_cache_control":"no-store","_etag":"66e2eaa19379c408492001533cd8fb87e0536840","_mod":"Fri, 02 Sep 2022 12:42:31 GMT","_url":https://repo.example.org/artifactory/api/conda/conda-local/sigma/linux-64/repodata.json,
  "info" : {
    "subdir" : "linux-64"
  },
  "packages" : {
     ...
     ...
     ...
  },
  "packages.conda" : { },
  "removed" : [ ]
}
```

**Comment by wolfv** [comment]
@ekungurov that's really weird because it's apparently missing quotes around the URL? Was that produced by mamba?

If the error message comes from the 404 we should check that we clean up the file ...

**Comment by ekungurov** [comment]
@wolfv I double-checked, the quotes was lost during copy-paste to email client (Outlook). So the original file has the quotes around URL. 

The error message I get is:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/kunguye1/.conda/envs/group_install_3/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/kunguye1/.conda/envs/group_install_3/lib/python3.8/site-packages/mamba/mamba.py", line 951, in exception_converter
        raise e
      File "/home/kunguye1/.conda/envs/group_install_3/lib/python3.8/site-packages/mamba/mamba.py", line 945, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/kunguye1/.conda/envs/group_install_3/lib/python3.8/site-packages/mamba/mamba.py", line 901, in _wrapped_main
        result = do_call(args, p)
      File "/home/kunguye1/.conda/envs/group_install_3/lib/python3.8/site-packages/mamba/mamba.py", line 763, in do_call
        exit_code = install(args, parser, "install")
      File "/home/kunguye1/.conda/envs/group_install_3/lib/python3.8/site-packages/mamba/mamba.py", line 507, in install
        index = load_channels(pool, channels, repos)
      File "/home/kunguye1/.conda/envs/group_install_3/lib/python3.8/site-packages/mamba/utils.py", line 171, in load_channels
        repo = subdir.create_repo(pool)
    RuntimeError: Could not read JSON repodata file (/home/kunguye1/.conda/pkgs/cache/664e96a8.json) parse error line 9416: subdir mismatch
```
I don't see anything strange at line 9416 of the JSON file. 
I begin to suspect that my error is caused by installing mamba into non-base environment...

**Comment by wolfv** [comment]
@ekungurov apparently

```
  "info" : {
    "subdir" : "linux-64"
  },
```

is at the top, and what does the `subdir` of that package say? It sounds like you might have invalid repodata (with mixed subdirs). Haven't seen that in the wild yet!

**Comment by ekungurov** [comment]
Indeed it says
```
    "<some-package-filename.tar.bz2>" : {
      ...
      "subdir" : "noarch"
      ...
    },
```
starting from line 9413

**Comment by wolfv** [comment]
Do you have control over that repository? You could correct that by removing the file, and reuploading it to the proper subdir (noarch).

**Comment by FHTMitchell** [comment]
I'm having the same problem, but in our case its from an old cache of conda-forge. Whilst I suspect we can fix it on our side, I think it's reasonable to expect mamba to handle this, conda does after all?

**Comment by wkerzendorf** [comment]
Having the same problem - looking forward to the fix (and thanks to the `mamba` team for all their efforts!!)

**Comment by jjerphan** [comment]
Duplicate of https://github.com/conda-forge/status/issues/144 which has been fixed.
