### ISSUE TITLE
Mamba not able to resolve host names

### ISSUE THREAD

**Issue by EJFielding** [mamba-org/mamba#980]
I am trying to install some packages with mamba, but it seems that it is not successfully looking up the host names for downloading the files.

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/fielding/opt/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/fielding/opt/anaconda3/lib/python3.8/site-packages/mamba/mamba.py", line 814, in exception_converter
        raise e
      File "/Users/fielding/opt/anaconda3/lib/python3.8/site-packages/mamba/mamba.py", line 808, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/fielding/opt/anaconda3/lib/python3.8/site-packages/mamba/mamba.py", line 773, in _wrapped_main
        result = do_call(args, p)
      File "/Users/fielding/opt/anaconda3/lib/python3.8/site-packages/mamba/mamba.py", line 663, in do_call
        exit_code = install(args, parser, 'install')
      File "/Users/fielding/opt/anaconda3/lib/python3.8/site-packages/mamba/mamba.py", line 532, in install
        downloaded = transaction.prompt(PackageCacheData.first_writable().pkgs_dir, repos)
    RuntimeError: Download error (6) Couldn't resolve host name [https://conda.anaconda.org/conda-forge/osx-64/anyio-3.1.0-py38h50d1736_0.tar.bz2]
```

It has this additional information:
```
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=insar
                CONDA_EXE=/Users/fielding/opt/anaconda3/bin/conda
             CONDA_PREFIX=/Users/fielding/opt/anaconda3/envs/insar
           CONDA_PREFIX_1=/Users/fielding/opt/anaconda3
    CONDA_PROMPT_MODIFIER=(insar)
         CONDA_PYTHON_EXE=/Users/fielding/opt/anaconda3/bin/python
               CONDA_ROOT=/Users/fielding/opt/anaconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/fielding/opt/anaconda3/envs/insar/bin:/Users/fielding/opt/anaco
                          nda3/condabin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/
                          bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : insar
    active env location : /Users/fielding/opt/anaconda3/envs/insar
            shell level : 2
       user config file : /Users/fielding/.condarc
 populated config files : /Users/fielding/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/fielding/opt/anaconda3  (writable)
      conda av data dir : /Users/fielding/opt/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/fielding/opt/anaconda3/pkgs
                          /Users/fielding/.conda/pkgs
       envs directories : /Users/fielding/opt/anaconda3/envs
                          /Users/fielding/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 503:20
             netrc file : /Users/fielding/.netrc
           offline mode : False
```

I checked that my computer is able to download `https://conda.anaconda.org/conda-forge/osx-64/anyio-3.1.0-py38h50d1736_0.tar.bz2` with `wget`.

**Comment by wolfv** [comment]
Can you try with curl? Mamba uses libcurl under the hood. 

The error suggests that you didn't have internet connection when trying. Sometimes the servers are down, too.

**Comment by EJFielding** [comment]
This works: ` curl https://conda.anaconda.org/conda-forge/osx-64/anyio-3.1.0-py38h50d1736_0.tar.bz2 >temp.out`

Is it a problem that `CURL_CA_BUNDLE=<not set>`?

**Comment by wolfv** [comment]
can you check `which curl` and make sure that it's from the same conda environment? (there is a system installed curl, too).

if it isn't installed, you can get it with `conda / mamba install curl -c conda-forge`

**Comment by EJFielding** [comment]
It was previously using the `/opt/local/bin/curl`, so I ran `mamba install curl` and it installed `curl` and several other components. Now "which curl" gives `/Users/fielding/opt/anaconda3/envs/insar/bin/curl` but it still fails with the same error when I try to run the big `mamba` installation.

**Comment by wolfv** [comment]
Yes, but the new curl -- does it work stand-alone?

**Comment by wolfv** [comment]
Also it looks like you have mamba in an env different from your base env. That's probably the issue. You need mamba installed __in__ your base env.

I'd suggest to start from scratch with mambaforge. The anaconda3 base env is too large. Miniforge or mambaforge are better choices.

**Comment by EJFielding** [comment]
I have `mamba` installed in my base environment, but maybe it is also installed in the `insar` environment.

The `curl` from the conda environment works stand-alone.

I tried installing all the packages with the regular `conda install` and it took a little while but it was successful, so I will try to look at `mamba` again later.

**Comment by wolfv** [comment]
Ok

**Comment by wolfv** [comment]
Let us know if it's still an issue for you
